City-of-Helsinki/yjdh

.editorconfig
.github/workflows/codeql-analysis.yml
.github/workflows/review.yml
.github/workflows/staging.yml
.github/workflows/stop_review.yml
README.md
backend/.prod/escape_json.c
backend/.prod/on_deploy.sh
backend/.prod/uwsgi.ini
backend/Dockerfile
backend/docker-entrypoint.sh
backend/kesaseteli/urls.py

- Update README.
- Add editorconfig.

Add github workflow

---

.github/workflows/review.yml
.github/workflows/staging.yml

fix backend url

---

.github/workflows/review.yml
.github/workflows/staging.yml

Fix backend not running migrations in review & staging

---

.github/workflows/review.yml

WIP: testing review pipeline

---

frontend/benefit/applicant/Dockerfile
frontend/kesaseteli/employer/Dockerfile

Support Arbitrary User IDs for OpenShift
https://docs.openshift.com/enterprise/3.2/creating_images/guidelines.html
https://helsinkisolutionoffice.atlassian.net/browse/YJDH-94

YJDH-94: Support Arbitrary User IDs for OpenShift

---

.github/workflows/bf-frontend-tests.yml
.github/workflows/bf-review.yml
.github/workflows/bf-staging.yml
.github/workflows/bf-stop_review.yml
.github/workflows/ks-frontend-tests.yml
.github/workflows/ks-review.yml
.github/workflows/ks-staging.yml
.github/workflows/ks-stop_review.yml
backend/kesaseteli/requirements-dev.in
backend/kesaseteli/requirements-dev.txt
backend/kesaseteli/requirements.in
backend/kesaseteli/requirements.txt

YJDH-106 | Fix kesäseteli review pipeline

---

backend/kesaseteli/oidc/urls.py

Update the url paths to match the original view paths.

KS-Backend | Update the OIDC mock view urls

---

.github/workflows/bf-frontend-tests.yml
.github/workflows/ks-frontend-tests.yml
frontend/.gitignore
frontend/package.json

fix code coverage check on pull requests. It was missing.

fix code coverage check on pull requests

---

docker-compose.benefit.yml
frontend/babel.config.js
frontend/benefit/applicant/Dockerfile
frontend/benefit/applicant/package.json
frontend/benefit/applicant/src/components/header/Header.tsx
frontend/benefit/applicant/src/components/header/extended.ts
frontend/package.json
frontend/shared/package.json
frontend/shared/src/components/header/Header.tsx
frontend/shared/src/styles/main.ts
frontend/yarn.lock

Fix localization, benefit navigation links

---

.github/workflows/bf-review.yml
.github/workflows/bf-staging.yml

Fix pipeline service name

---

docker-compose.benefit.yml

docker-compose up should work again

fix indent in docker-compose.benefit.yml

---

frontend/benefit/applicant/package.json
frontend/kesaseteli/employer/package.json
frontend/package.json
frontend/shared/package.json
frontend/yarn.lock

bumo frontend package versins + fix audit issues. Browser tests still fail but not related to this.

bump frontend versions + fix frotend audit issues

---

.env.kesaseteli.example
.gitignore
README.md
backend/kesaseteli/docker-entrypoint.sh
backend/kesaseteli/oidc/views/eauth_views.py
docker-compose.kesaseteli.yml
localdevelopment/kesaseteli/nginx/Dockerfile
localdevelopment/kesaseteli/nginx/nginx.conf

ADDS Local nginx with cert autogeneration for kesaseteli
YHDH-109

YHDH-109: Local https termination

---

frontend/benefit/applicant/src/components/applications/forms/application/step3/ApplicationFormStep3.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step4/ApplicationFormStep4.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step5/ApplicationFormStep5.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step6/ApplicationFormStep6.tsx
frontend/benefit/applicant/src/components/applications/pageContent/PageContent.tsx

Missing actions are added so that user can go through all wizard and back.

HL-16: Add wizard actions to each step

---

.pre-commit-config.yaml
backend/kesaseteli/requirements-dev.txt
backend/kesaseteli/requirements.txt

Bump requirements for ks-bknd.

KS-Backend: Bump requirements

---

.github/workflows/ks-pytest.yml
backend/kesaseteli/requirements-dev.in
backend/kesaseteli/requirements-dev.txt

Make sure that the backend service is stateless by running the tests randomized and in parallel
[YJDH-81](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-81)

YJDH-81 | Parallelize & randomize django tests

---

frontend/kesaseteli/employer/browser-tests/actions/employer-header.actions.ts
frontend/kesaseteli/employer/browser-tests/index-page/companyPage.components.ts
frontend/kesaseteli/employer/browser-tests/index-page/companyPage.testcafe.ts
frontend/kesaseteli/employer/browser-tests/index-page/indexPage.components.ts
frontend/kesaseteli/employer/browser-tests/index-page/indexPage.testcafe.ts
frontend/kesaseteli/employer/package.json
frontend/kesaseteli/employer/src/__tests__/index.test.tsx
frontend/kesaseteli/employer/src/pages/index.tsx
frontend/package.json
frontend/shared/browser-tests/actions/login-action.ts
frontend/shared/browser-tests/components/suomiFiValtuutus.components.ts
package.json

Create new application button which moves to company page. Also updated browser test including selecting company from suomifi valtuutuspage. Company test should also be now more robust without false negatives.
https://helsinkisolutionoffice.atlassian.net/browse/YJDH-121

YJDH-121: create new application button

---

.github/workflows/bf-frontend-tests.yml
.github/workflows/bf-py-coding-style.yml
.github/workflows/bf-pytest.yml
.github/workflows/codeql-analysis.yml
.github/workflows/ks-frontend-tests.yml
.github/workflows/ks-py-coding-style.yml
.github/workflows/ks-pytest.yml

Added `develop` branch that can be used in Azure Devops Pipeline from IBM infra
Updated workflows to trigger tests/builds in `develop` branch

HT-55 | Enable workflows for develop branch

---

frontend/benefit/applicant/package.json
frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/DeMinimisAidForm.tsx
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/extended.ts
frontend/benefit/applicant/src/constants.ts
frontend/benefit/applicant/src/utils/forms.ts
frontend/shared/src/components/forms/section/styled.ts
frontend/shared/src/utils/date.utils.ts
frontend/yarn.lock

- added translations for different types of validation errors.
- added validation for deminimis form
hds Date input component does not reset the value with resetForm (but is generic, does not work with setting the value with useState).

Error validation handling formik applicant

---

frontend/benefit/applicant/package.json
frontend/benefit/applicant/tsconfig.json
frontend/kesaseteli/employer/package.json
frontend/kesaseteli/employer/tsconfig.json
frontend/package.json
frontend/shared/browser-tests/utils/testcafe.utils.ts
frontend/shared/package.json
frontend/yarn.lock

- Upgrade TypeScript to v4.3.4

HL-100 | Upgrade TypeScript to v4.3.4

---

backend/benefit/README.md
backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/api/v1/views.py
backend/benefit/applications/models.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/factories.py
backend/benefit/companies/api/v1/views.py
backend/benefit/helsinkibenefit/settings.py
backend/benefit/helsinkibenefit/urls.py
backend/benefit/requirements-dev.txt
backend/benefit/requirements.in
backend/benefit/requirements.txt

* Add API documentation for application/company 
* Additional dependencies required for api documentation: pyyaml, uritemplate, drf-spectacular, django-filter
* Copied&modified a bit instructions in README.md from other city of helsinki project
* Changed application status filtering to use django-filter, so that schema can be generated automatically

Hl 74: api documentation

---

frontend/benefit/applicant/package.json
frontend/kesaseteli/employer/package.json
frontend/shared/package.json
frontend/yarn.lock

HL-81: Update HDS to 1.2.0

---

.github/workflows/ks-py-coding-style.yml
.github/workflows/ks-pytest.yml
backend/shared/setup.cfg
backend/shared/setup.py
backend/shared/shared/audit_log/audit_logging.py
backend/shared/shared/audit_log/tests/conftest.py
backend/shared/shared/audit_log/tests/test_audit_logging.py
backend/shared/shared/audit_log/tests/utils.py
backend/shared/shared/audit_log/viewsets.py
backend/shared/shared/azure_adfs/tests/test_adfs_login.py
backend/shared/shared/azure_adfs/urls.py
backend/shared/shared/common/tests/conftest.py
backend/shared/shared/oidc/admin.py
backend/shared/shared/oidc/auth.py
backend/shared/shared/oidc/jobs/hourly/clear_user_sessions.py
backend/shared/shared/oidc/models.py
backend/shared/shared/oidc/services.py
backend/shared/shared/oidc/tests/conftest.py
backend/shared/shared/oidc/tests/factories.py
backend/shared/shared/oidc/tests/test_auth_backend.py
backend/shared/shared/oidc/tests/test_clear_sessions_job.py
backend/shared/shared/oidc/tests/test_eauth_rest_auth.py
backend/shared/shared/oidc/tests/test_eauth_views.py
backend/shared/shared/oidc/tests/test_mock_views.py
backend/shared/shared/oidc/tests/test_oidc_views.py
backend/shared/shared/oidc/urls.py
backend/shared/shared/oidc/utils.py
backend/shared/shared/oidc/views/eauth_views.py
backend/shared/shared/oidc/views/hki_views.py
backend/shared/shared/oidc/views/mock_views.py

KS-Backend | Reformat shared & run tests on changes to shared

---

backend/benefit/applications/api/v1/serializers.py

HL-102 | Fix optional fields fallback value

---

backend/benefit/applications/api/v1/serializers.py

Fix optional fields fallback value

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/DeMinimisAidForm.tsx
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/useDeminimisAid.ts

For consistent styling (to follow the abstract design), the field is replaced with normal text field and will be validated with Yup.

HL-109: Fix deminimis aid amount field type

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/tests/test_applications_api.py

HL-123: add created_at field to the application api

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/helsinkibenefit/settings.py

HL-85 | Add max file size upload validation, enable private blob storage

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/Applications.sc.ts
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.tsx
frontend/benefit/applicant/src/components/applications/applicationList/useApplicationList.ts
frontend/benefit/applicant/src/components/applications/pageContent/PageContent.tsx
frontend/benefit/applicant/src/components/applications/pageContent/usePageContent.ts
frontend/benefit/applicant/src/types/application.d.ts
frontend/shared/src/utils/date.utils.ts

- created date value is shown in the applications drafts list instead of modified at value
- when application is in edit mode, the title of the application page should be Application
- when application is in edit mode, the creation date is shown under title as unique identifier
- when application is in edit mode, the helper text is shown under title to tell that its an edit mode

HL-112: Edit application layout changes

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/helsinkibenefit/settings.py

- Update all message to be localized using gettext
- Add LOCALE_PATH to settings to store compiled messages later
- Change message structure so it can be formatted with variables after translation
How Django determine translation can be found here: https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#how-django-discovers-language-preference

HL-117 | Update localized messages

---

backend/benefit/azure-pipelines-master.yml
backend/benefit/azure-pipelines-release.yml
frontend/benefit/azure-pipelines-master.yml
frontend/benefit/azure-pipelines-release.yml

Pipeline yamls for benefit application

---

backend/benefit/azure-pipelines-master.yml
backend/benefit/azure-pipelines-release.yml
frontend/benefit/azure-pipelines-master.yml
frontend/benefit/azure-pipelines-release.yml

Main: Pipeline yamls for benefit application

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/models.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/helsinkibenefit/settings.py

Validation rules:
- Working hour must be > 18 hour per week
- Salary must be > 0
- Vacation money and other expense must be >= 0

HL-66 | Validate employee data

---

.github/workflows/yarn-audit-scheduled.yml

Run once a day yarn audit check for security purposes. Github action promises that it creates Github Issue so that the developers can pick it up and work on it. https://github.com/pragatheeswarans/yarn-audit-action
[YJDH-146](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-146)

YJDH-146 | Scheduled Yarn audit check

---

frontend/benefit/applicant/.eslintrc.js
frontend/benefit/applicant/src/components/applications/applicationList/useApplicationList.ts
frontend/benefit/applicant/src/components/applications/forms/application/step1/useApplicationFormStep1.ts
frontend/benefit/applicant/src/components/applications/forms/application/step2/useApplicationFormStep2.ts
frontend/benefit/applicant/src/components/applications/forms/application/stepperActions/StepperActions.tsx
frontend/benefit/applicant/src/components/applications/pageContent/usePageContent.ts
frontend/benefit/applicant/src/constants.ts
frontend/benefit/applicant/src/context/ApplicationContext.tsx
frontend/benefit/applicant/src/context/ApplicationProvider.tsx
frontend/benefit/applicant/src/context/FrontPageContext.tsx
frontend/benefit/applicant/src/types/application.d.ts
frontend/benefit/applicant/src/utils/common.ts
frontend/shared/src/__tests__/utils/react-query/get-default-react-query-test-client.ts

- sets the application step when navigating the stepper
- sets the current application step when loading the existing application

HL-119,120: Application step backend value to UI logic

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/api/v1/views.py
backend/benefit/applications/models.py
backend/benefit/applications/tests/test_applications_api.py

Validation of attachment business rules
HL-79
backend/benefit/applications/tests/test_applications_api.py

Hl 79/attachment validation business rules

---

backend/benefit/applications/services/talpa_integration.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/factories.py
backend/benefit/applications/tests/test_talpa_integration.py

Talpa CSV integation
Actual data transfer to Talpa not included
HL-125
backend/benefit/applications/tests/test_talpa_integration.py

HL-125: Talpa csv output

---

frontend/benefit/applicant/src/components/applications/forms/application/step3/ApplicationFormStep3.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step3/attachmentsList/attachmentItem/AttachmentItem.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step3/attachmentsList/attachmentItem/AttachmentsItem.sc.ts
frontend/benefit/applicant/src/components/applications/forms/application/step3/attachmentsList/useAttachmentsList.ts

-attachment list can be navigated with keyboard
-keyboard actions (view/remove attachments)
-fixed bug with showing proper sections for salary benefit type

HL-116: Attachment accessibility improvements

---

.env.kesaseteli.example
backend/kesaseteli/kesaseteli/settings.py
backend/kesaseteli/requirements-dev.txt
backend/kesaseteli/requirements.in
backend/kesaseteli/requirements.txt
backend/shared/shared/oidc/auth.py
backend/shared/shared/oidc/views/hki_views.py

Add log handler for logging errors/warnings into Azure.
[YJDH-152](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-152)

YJDH-152 | Add Azure logging

---

frontend/package.json

Fix audit issues found on 01.09.2021

---

frontend/benefit/applicant/package.json
frontend/kesaseteli/employer/package.json
frontend/package.json
frontend/shared/package.json
frontend/yarn.lock

Bump frontend packages 08/09/2021

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/Application.sc.ts
frontend/benefit/applicant/src/components/applications/forms/application/step4/ApplicationFormStep4.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step4/attachmentsListView/AttachmentsListView.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step4/attachmentsListView/__tests__/AttachmentsListView.test.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step4/companyInfoView/CompanyInfoView.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step4/companyInfoView/__tests__/CompanyInfoView.test.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step4/employeeView/EmployeeView.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step4/employeeView/__tests__/EmployeeView.test.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step4/useApplicationFormStep4.ts
frontend/benefit/applicant/src/components/applications/pageContent/PageContent.tsx
frontend/benefit/applicant/src/types/application.d.ts
frontend/benefit/applicant/src/types/common.d.ts
frontend/shared/src/components/forms/section/FormSection.sc.ts
frontend/shared/src/components/forms/section/FormSection.tsx

HL-89: Summary application step

---

backend/benefit/applications/tests/snapshots/snap_test_ahjo_integration.py

Update snapshot data.
If the test failed randomly next time, we can consider switching to another method

Fix snapshot test

---

.github/workflows/bf-review.yml

Fix applicant review environment

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/step4/useApplicationFormStep4.ts
frontend/benefit/applicant/src/components/applications/forms/application/step5/ApplicationFormStep5.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step5/credentialsSection/CredentialsSection.sc.ts
frontend/benefit/applicant/src/components/applications/forms/application/step5/credentialsSection/CredentialsSection.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step5/useApplicationFormStep5.ts
frontend/benefit/applicant/src/components/applications/pageContent/PageContent.tsx
frontend/benefit/applicant/src/components/credentialsIngress/CredentialsIngress.sc.ts
frontend/benefit/applicant/src/components/credentialsIngress/CredentialsIngress.tsx
frontend/shared/src/components/forms/section/FormSection.sc.ts

HL-151: Application step 5 layout

---

frontend/benefit/applicant/src/components/applications/forms/application/step1/useApplicationFormStep1.ts
frontend/benefit/applicant/src/components/applications/forms/application/step2/useApplicationFormStep2.ts
frontend/benefit/applicant/src/components/applications/forms/application/step3/useApplicationFormStep3.ts
frontend/benefit/applicant/src/components/applications/forms/application/step4/useApplicationFormStep4.ts
frontend/benefit/applicant/src/components/applications/forms/application/step5/useApplicationFormStep5.ts
frontend/benefit/applicant/src/components/applications/pageContent/usePageContent.ts
frontend/benefit/applicant/src/context/ApplicationContext.tsx
frontend/benefit/applicant/src/context/ApplicationProvider.tsx
frontend/benefit/applicant/src/types/application.d.ts

Refactor benefit applicant current step logic

---

frontend/kesaseteli/employer/public/locales/en/common.json
frontend/kesaseteli/employer/public/locales/fi/common.json
frontend/kesaseteli/employer/public/locales/sv/common.json
frontend/kesaseteli/employer/src/pages/404.tsx
frontend/kesaseteli/employer/src/pages/login.tsx

- Add a custom 404 page for the app.
- Small reformat  of login page.
[YJDH-186](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-186)

YJDH-186 | KS-Employer: Add 404 page

---

.env.benefit.example
backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/api/v1/views.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/factories.py
backend/benefit/applications/tests/test_application_batch_api.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/common/permissions.py
backend/benefit/common/tests/conftest.py
backend/benefit/companies/api/v1/views.py
backend/benefit/companies/tests/conftest.py
backend/benefit/companies/tests/test_api.py
backend/benefit/helsinkibenefit/settings.py
backend/benefit/helsinkibenefit/urls.py
backend/benefit/users/models.py
backend/benefit/users/tests/conftest.py
backend/benefit/users/utils.py

HL-12 | Enable authentication

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/tests/test_applications_api.py

Add consent validation so only one employee consent is allowed to upload

HL-193 | Add employee consent validation

---

frontend/kesaseteli/employer/public/locales/en/common.json
frontend/kesaseteli/employer/public/locales/fi/common.json
frontend/kesaseteli/employer/public/locales/sv/common.json
frontend/kesaseteli/employer/src/pages/thankyou.tsx

Add a thank you page that is shown after the application is submitted by the user.
[YJDH-184](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-184)
Abstract: https://share.goabstract.com/888784a7-7dec-4b9b-9860-1a5e990a7e58?collectionLayerId=9ea33fe8-d53d-4170-8fc0-d694c1876102&mode=design&sha=latest

YJDH-184 | KS-Employer: Add thank you page

---

backend/kesaseteli/applications/jobs/monthly/clean_old_applications.py
backend/kesaseteli/applications/jobs/monthly/clean_old_attachments.py
backend/kesaseteli/applications/tests/test_cron_job.py

There is a need to delete attachments that are older than a year and applications older than 5 years. Add cron jobs to delete them.
[YJDH-203](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-203)

YJDH-203 | KS-Backend: Add cron jobs to clear old attachments & applications

---

backend/benefit/helsinkibenefit/settings.py
backend/kesaseteli/kesaseteli/settings.py
backend/kesaseteli/requirements.txt
backend/shared/shared/azure_adfs/README.md
backend/shared/shared/azure_adfs/auth.py

- Fix Azure ADFS settings so that the whole application won't crash if the setup is missing.
- Update django environ so that the database url can be read correctly in PLATTA environment.
-

Backend: Small fixes for PLATTA

---

.env.kesaseteli.example
backend/kesaseteli/kesaseteli/settings.py
backend/kesaseteli/requirements.in
backend/kesaseteli/requirements.txt

According to the latest information, we will be using a centralized Helsinki Sentry service for the error logging instead of the Azure application insights.
[YJDH-208](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-208)

YJDH-208 | KS-Backend: Roll back to sentry logging

---

backend/benefit/applications/api/v1/serializers.py

Fix "company matching query does not exist" error when DISABLE_AUTHENTICATION is set

---

frontend/package.json
frontend/yarn.lock

Version bumps made by dependabot gathered in one pr.

version bumps 27.9.2021

---

backend/benefit/requirements.txt

same change was done in Kesäseteli

Upgrade django-environ so that database url can be read correctly in PLATTA environment

---

backend/benefit/helsinkibenefit/settings.py

Also re-ordering of the settings.py lines so that comparison with Kesäseteli is easier in the future

Fix CORS errors in PLATTA.

---

backend/shared/shared/audit_log/models.py

Improve the audit log str so that it shows the status of the event and "UNKNOWN" instead of empty values.

Backend: Improve audit logging str

---

.env.kesaseteli.example
.github/workflows/ks-frontend-tests-push.yml
.github/workflows/ks-frontend-tests.yml
.github/workflows/ks-review.yml
.github/workflows/ks-staging.yml
backend/kesaseteli/kesaseteli/settings.py
frontend/.dockerignore
frontend/kesaseteli/employer/Dockerfile
frontend/kesaseteli/employer/next.config.js
frontend/kesaseteli/employer/package.json
frontend/kesaseteli/employer/sentry.client.config.js
frontend/kesaseteli/employer/sentry.properties
frontend/kesaseteli/employer/sentry.server.config.js
frontend/kesaseteli/employer/src/pages/_app.tsx
frontend/yarn.lock

- Add initial Sentry setup for the Employer UI.
- KS-Backend: Add support for a header used by the frontend sentry: "sentry-trace".
[YJDH-153](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-153)

YJDH-153 | KS-Employer: Add Sentry logging

---

frontend/kesaseteli/employer/public/locales/en/common.json
frontend/kesaseteli/employer/public/locales/fi/common.json
frontend/kesaseteli/employer/public/locales/sv/common.json

Yjdh-224 translate lorem ipsums

---

backend/benefit/README.md

Add instructions about loading the fixtures to README.md

---

backend/shared/shared/audit_log/audit_logging.py

In some edge cases `previous_record` does not exist and will throw an error when `latest_record` is diffed against NoneType.

Backend: Fix audit logging history changes

---

frontend/kesaseteli/employer/src/pages/404.tsx
frontend/kesaseteli/employer/src/pages/500.tsx
frontend/kesaseteli/employer/src/pages/_app.tsx
frontend/kesaseteli/employer/src/pages/application.tsx
frontend/kesaseteli/employer/src/pages/login.tsx
frontend/kesaseteli/employer/src/pages/thankyou.tsx

Add Head & title elements in each of the pages.
[YJDH-273](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-273)

YJDH-273 | KS-Employer: Add page titles

---

backend/kesaseteli/applications/exporters/excel_exporter.py
backend/kesaseteli/applications/views.py

Order the SummerVouchers based on the submitted date of the related application.
[YJDH-294](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-294)

YJDH-294 | KS-Backend: Change ordering of handler excel

---

frontend/shared/src/components/attachments/AttachmentsList.tsx

Fix attachments

---

backend/benefit/applications/api/v1/application_batch_views.py

Fix talpa file datetime format

---

frontend/benefit/applicant/src/hooks/useApplicationQuery.ts
frontend/benefit/applicant/src/hooks/useApplicationTemplateQuery.ts
frontend/benefit/applicant/src/hooks/useApplicationsQuery.ts
frontend/benefit/applicant/src/hooks/useCompanyQuery.ts

Fixes the issue with unsaved changes cleared when switching tabs

HL-307: Fix refetch in get queries

---

frontend/benefit/handler/azure-pipelines-master.yml
frontend/benefit/handler/azure-pipelines-release.yml

Main: pipeline ymls for main branch

---

frontend/benefit/handler/azure-pipelines-master.yml
frontend/benefit/handler/azure-pipelines-release.yml

pipeline ymls for develop branch

---

frontend/benefit/handler/Dockerfile

Removed i18 not existing file from docker

HL-325: Handlers docker file fix

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationHeader/ApplicationHeader.sc.ts
frontend/benefit/handler/src/components/applicationHeader/ApplicationHeader.tsx
frontend/benefit/handler/src/components/applicationReview/ApplicationReview.tsx
frontend/benefit/handler/src/components/reviewSection/ReviewSection.sc.ts
frontend/benefit/handler/src/components/reviewSection/ReviewSection.tsx
frontend/benefit/handler/src/components/reviewSection/useReviewSection.ts
frontend/benefit/handler/src/pages/application/index.tsx

Implements the layout and styling for the application review page:
-header
-review section
-review section with actions
Example:

HL-265: application review layout

---

frontend/benefit/handler/src/components/applicationList/useApplicationList.ts
frontend/benefit/handler/src/types/application.d.ts

-Extend handler application type with calculation
-Show handlers name in the applications list in the handlers front page

HL-324: Add handler types, update lists

---

backend/benefit/calculator/tests/test_calculator_api.py
backend/benefit/common/tests/conftest.py
backend/benefit/helsinkibenefit/urls.py
backend/benefit/messages/models.py
backend/benefit/messages/permissions.py
backend/benefit/messages/serializers.py
backend/benefit/messages/tests/conftest.py
backend/benefit/messages/tests/factories.py
backend/benefit/messages/tests/test_api.py
backend/benefit/messages/views.py
backend/benefit/requirements.in
backend/benefit/requirements.txt
backend/benefit/terms/tests/test_terms_of_service_api.py

HL-282 | Message API

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/Application.sc.ts
frontend/benefit/applicant/src/components/applications/forms/application/step5/ApplicationFormStep5.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step5/attachmentsListView/AttachmentsListView.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step5/companyInfoView/CompanyInfoView.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step5/employeeView/EmployeeView.tsx
frontend/benefit/applicant/src/components/summarySection/SummarySection.sc.ts
frontend/benefit/applicant/src/components/summarySection/SummarySection.tsx

Fixes:
HL-223: YT-tilanne is not visible 
HL-225: Strange comma before percentage
HL-238: Benefit type is missing
HL-239: Optional apprenticeship question (hidden if no pay subsidy)
HL-238: Benefit type is missing
HL-241: Hide empty attachments
HL-245: Fix font sizes
HL-246: Fix margins
HL-250: Fix margin on attachments
HL-260: Department information is missing
HL-250: Fix margin on attachments (cannot be fixed in last section, still margin is a bit bigger)

HL-245: applicant summary

---

backend/benefit/applications/api/v1/application_batch_views.py
backend/benefit/applications/api/v1/status_transition_validator.py
backend/benefit/applications/enums.py
backend/benefit/applications/tests/test_application_batch_api.py

HL-309 | Add ahjo_export_created status to Application Batches

---

.github/workflows/bf-review.yml

Temporary remove cronjob deployment in review env

---

frontend/kesaseteli/employer/public/locales/en/common.json
frontend/kesaseteli/employer/public/locales/fi/common.json
frontend/kesaseteli/employer/public/locales/sv/common.json
frontend/kesaseteli/employer/src/components/application/form/AttachmentInput.tsx
frontend/kesaseteli/employer/src/components/application/form/error-summary/ErrorNotificationRow.tsx
frontend/kesaseteli/employer/src/components/application/steps/step1/EmployerErrorSummary.tsx
frontend/kesaseteli/employer/src/components/application/steps/step2/error-notification/EmployeeErrorNotification.tsx
frontend/kesaseteli/employer/src/components/application/steps/step2/error-notification/EmploymentsErrorNotification.tsx
frontend/kesaseteli/employer/src/hooks/application/useApplicationFormField.ts
frontend/shared/src/__tests__/utils/component.utils.ts

Unify error messages in error notificaton box to match error messages next to field.

YJDH-319: better validation error messages

---

frontend/benefit/applicant/src/components/Notification/Notification.sc.ts
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/list/DeMinimisAidsList.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step1/companyInfo/CompanyInfo.sc.ts
frontend/benefit/applicant/src/components/applications/forms/application/step2/ApplicationFormStep2.tsx
frontend/benefit/applicant/src/components/attachmentsIngress/AttachmentsIngress.sc.ts
frontend/benefit/applicant/src/components/credentialsIngress/CredentialsIngress.sc.ts
frontend/benefit/applicant/src/components/mainIngress/MainIngress.sc.ts
frontend/benefit/applicant/src/components/mainIngress/MainIngress.tsx
frontend/benefit/applicant/src/pages/login.tsx

- Notifications body font sizes fix
- Ingress application step 3 and 4 text font size fix

HL-245: Fix font sizes

---

backend/benefit/companies/api/v1/views.py

There was a bug that when DISABLE_AUTHENTICATION set to `True`. Company API won't be able to extract the business_id from the user request. So it always returns 404
Small fix to change the logic so there is 1 company always be returned if authentication disabled

Fix company API when disable authentication

---

frontend/benefit/applicant/src/hooks/useFormActions.tsx

- Fix employee values attached to the update application requests

Fix update application values

---

.github/workflows/ks-review.yml
frontend/benefit/applicant/src/hooks/useLogoutQuery.ts
frontend/kesaseteli/employer/package.json
frontend/kesaseteli/employer/src/hooks/application/useApplicationApi.ts
frontend/kesaseteli/employer/src/pages/application.tsx
frontend/kesaseteli/employer/src/pages/thankyou.tsx

- Add certificate hashes from review environment to the browser-test script flag
- Fix production build bug that loads still the previous draft application after clicking "create new application"

kesaseteli/employer: Add let's encrypt staging -certificates + fix browser tests

---

frontend/benefit/applicant/src/components/applications/applicationList/useApplicationList.ts

- Add the application number to the draft list
- Fix a typo in the variable name
- After logging in, the draft applications list on the home page will show the application number

HL-293 | Add the application number to draft list

---

backend/benefit/helsinkibenefit/settings.py

Fix default YRTTI URL

---

README.md
package.json

Readme.md was out of date and doesnt match to current scripts. Now updated

Update readme + scripts

---

frontend/kesaseteli/youth/public/locales/en/common.json
frontend/kesaseteli/youth/public/locales/fi/common.json
frontend/kesaseteli/youth/public/locales/sv/common.json
frontend/kesaseteli/youth/src/components/footer/Footer.tsx

Footer links: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-338

YJDH-338: footer links

---

frontend/benefit/applicant/src/components/applications/forms/application/step5/companyInfoView/CompanyInfoView.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step5/employeeView/EmployeeView.tsx
frontend/benefit/handler/src/components/applicationReview/benefitView/BenefitView.tsx
frontend/benefit/handler/src/components/applicationReview/deminimisView/DeminimisView.tsx

1. fixed date formats in applicant summary view
2. fixed date formats in handlers review page
The fields fixed:
deminimis aid granted at (in the listing table)
startdate
enddate

HL-211: Summary page date formats

---

frontend/kesaseteli/youth/src/__tests__/index.test.tsx
frontend/kesaseteli/youth/src/components/forms/YouthForm.tsx

Frontend validation: Change max length of youth names

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/step6/ApplicationFormStep6.tsx
frontend/benefit/applicant/src/hooks/useDeleteApplicationQuery.ts

- Add missing translations
- Add the delete logic to the sixth step
- Invalidate the application list query

HL-99 | Delete application fixes

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.sc.ts
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.tsx
frontend/benefit/applicant/src/components/applications/applicationList/useApplicationList.ts
frontend/benefit/applicant/src/pages/index.tsx
frontend/benefit/applicant/src/types/application.d.ts
frontend/shared/src/__tests__/utils/setupTests.ts

New list added to the front page
The new messages info bar is mocked for future, when messaging is implemented
editEndDate is mocked, waiting the value from api (not implemented in backend yet)

HL-271: Application list additional info required

---

frontend/kesaseteli/employer/browser-tests/application-page/step2.components.ts

Fix Kesäseteli linting error

---

backend/benefit/applications/enums.py
backend/benefit/companies/api/v1/views.py
backend/benefit/companies/services.py
backend/benefit/companies/tests/conftest.py
backend/benefit/companies/tests/data/company_data.py
backend/benefit/companies/tests/test_api.py
backend/benefit/helsinkibenefit/settings.py
backend/shared/shared/service_bus/service_bus_client.py

HL-362 | Palveluväylä integration

---

frontend/benefit/applicant/src/components/applications/forms/application/step2/ApplicationFormStep2.tsx
frontend/benefit/applicant/src/utils/featureFlags.ts

HL-295: Remove commission based benefit option

---

frontend/benefit/applicant/src/components/applications/forms/application/step2/ApplicationFormStep2.tsx
frontend/benefit/applicant/src/utils/featureFlags.ts

The conditional comission radio broke the flow, so its now removed and will be added when needed

Application step 2 fix

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/header/Header.tsx
frontend/shared/src/components/drawer/Drawer.sc.tsx
frontend/shared/src/components/drawer/Drawer.tsx
frontend/shared/src/components/header/Header.tsx
frontend/shared/src/components/messaging/Actions.tsx
frontend/shared/src/components/messaging/Message.tsx
frontend/shared/src/components/messaging/MessagesForm.tsx
frontend/shared/src/components/messaging/Messaging.sc.tsx

- Implement Drawer component
- Support adding custom items to the Header and add the messaging drawer to the header
- Building main messaging components (add them to the shared folder for the time being)

HL-327 | Drawer component

---

frontend/README.md

Updated readme for instructions how to test on kuva infra

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/tests/test_applications_api.py

start_date on a previous year prevented saving a draft application.
backend/benefit/applications/tests/test_applications_api.py: test_application_date_range_on_submit

HL-385: validate start_date when submitting a draft application

---

.github/dependabot.yml

YJDH-403 | Remove duplicate entry from .github/dependabot.yml

---

frontend/kesaseteli/youth/public/locales/en/common.json
frontend/kesaseteli/youth/public/locales/fi/common.json
frontend/kesaseteli/youth/public/locales/sv/common.json
frontend/kesaseteli/youth/src/pages/activated.tsx

Static activation page. Routing logic will be added later.
https://helsinkisolutionoffice.atlassian.net/browse/YJDH-388
https://helsinkisolutionoffice.atlassian.net/browse/YJDH-395

YJDH-388: activated page

---

backend/kesaseteli/applications/migrations/0018_rename_application_to_employer_application.py
backend/kesaseteli/applications/migrations/0019_use_employer_applications_related_name.py
backend/kesaseteli/applications/migrations/0020_rename_summer_voucher_to_employer_summer_voucher.py

This migration conflict was caused by merging PR #579 into develop.
Fixes YJDH-404
YJDH-404

YJDH-404 | KS-Backend: Fix migration conflicts

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/components/applicationList/useApplicationList.ts
frontend/benefit/handler/src/pages/index.tsx
frontend/benefit/handler/src/types/application.d.ts

Add to the list of handling applications, applications with status more information required.
Show styled last modification date column

HL-273: More info list items to review frontpage

---

backend/benefit/calculator/rules.py

HL-375 | Only render training compensation row if amount > 0

---

backend/benefit/azure-pipelines-master.yml
backend/benefit/azure-pipelines-release.yml
frontend/benefit/azure-pipelines-master.yml
frontend/benefit/azure-pipelines-release.yml
frontend/benefit/handler/azure-pipelines-master.yml
frontend/benefit/handler/azure-pipelines-release.yml

HL-377 | Update azure trigger path

---

frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.sc.ts
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.tsx
frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/components/applicationList/useApplicationList.ts
frontend/benefit/handler/src/components/applicationReview/ApplicationReview.sc.ts
frontend/benefit/handler/src/components/applicationReview/ApplicationReview.tsx
frontend/benefit/handler/src/types/application.d.ts

-Replaced custom status alert label with HDS one
-Fixed the bug with appearing of additional info required status label in the applications list

HL-273: Fix status label

---

backend/benefit/messages/serializers.py
backend/benefit/messages/tests/test_api.py

* The allowed statuses are listed in APPLICANT_MESSAGE_ALLOWED_STATUSES
* Also add validation that the handler must send a message first,
before the applicant is able to do so.

HL-401: fix error that prevented applicant from sending messages

---

.github/workflows/bf-review.yml
.github/workflows/ks-review.yml
.github/workflows/te-review.yml

Database name doesnt match to the name path in the database url

Fix incorrect database url

---

frontend/kesaseteli/youth/azure-pipelines-devtest.yml
frontend/kesaseteli/youth/azure-pipelines-stageprod.yml

pipeline yaml files for youth ui develop branch

---

frontend/kesaseteli/youth/azure-pipelines-devtest.yml
frontend/kesaseteli/youth/azure-pipelines-stageprod.yml

Pipeline yaml files for youth ui main branch

---

frontend/benefit/applicant/src/components/applications/applicationList/ApplicationList.sc.ts
frontend/benefit/applicant/src/components/applications/applicationList/ApplicationList.tsx
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.sc.ts
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.tsx
frontend/benefit/applicant/src/components/applications/applicationList/useApplicationList.ts
frontend/benefit/applicant/src/components/applications/pageContent/usePageContent.ts
frontend/benefit/applicant/src/components/header/Header.tsx
frontend/benefit/applicant/src/components/header/useHeader.ts
frontend/benefit/applicant/src/context/AppContext.tsx
frontend/benefit/applicant/src/context/AppContextProvider.tsx
frontend/shared/src/components/messaging/Messaging.sc.tsx

-Adds line breaks to the messages
-shows message icon for applicant only in additional info required application status
-shows count of unread messages for each application list item in the list

HL-372: Fix messenger

---

frontend/benefit/applicant/src/components/applications/forms/application/step5/useApplicationFormStep5.ts
frontend/benefit/applicant/src/components/applications/forms/application/step6/useApplicationFormStep6.ts

HL-349 | Fix redirect after submitted application

---

.github/workflows/te-stop_review.yml
frontend/shared/.eslintignore

Fix db name on te-stop_review.yml

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/messages/automatic_messages.py

HL-365: automatically generate message when application is reopened

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/pages/index.tsx

Show handling application in sent list

HL-394: Show handling application in sent list

---

frontend/benefit/applicant/src/components/applications/forms/application/step5/useApplicationFormStep5.ts
frontend/benefit/applicant/src/components/applications/forms/application/step6/useApplicationFormStep6.ts
frontend/benefit/applicant/src/components/applications/pageContent/usePageContent.ts
frontend/benefit/applicant/src/components/header/useHeader.ts
frontend/benefit/applicant/src/components/mainIngress/MainIngress.tsx
frontend/benefit/applicant/src/components/mainIngress/useMainIngress.ts
frontend/benefit/applicant/src/context/AppContext.tsx
frontend/benefit/applicant/src/context/AppContextProvider.tsx
frontend/benefit/applicant/src/hooks/useFormActions.tsx

-Fix submitting of the application
-Fix notification for submitted application
-Fix resending application

HL-414: Application freezing on submit fix

---

frontend/benefit/handler/src/components/applicationReview/actions/editAction/EditAction.tsx
frontend/benefit/handler/src/hooks/useApplicationActions.ts

Use loading button to indicate update when open application for editing and lock application

HL-381: Add loading button for opening the application in the Handler UI

---

frontend/benefit/applicant/src/hooks/useFormActions.tsx

HL-419: Possible success notification fix

---

backend/benefit/azure-pipelines-master.yml
backend/benefit/azure-pipelines-release.yml
backend/kesaseteli/azure-pipelines-kesaseteli-api-master.yml
backend/kesaseteli/azure-pipelines-kesaseteli-api-release.yml
frontend/benefit/azure-pipelines-master.yml
frontend/benefit/handler/azure-pipelines-master.yml
frontend/benefit/handler/azure-pipelines-release.yml
frontend/kesaseteli/azure-pipelines-kesaseteli-ui-master.yml
frontend/kesaseteli/azure-pipelines-kesaseteli-ui-release.yml
frontend/kesaseteli/handler/azure-pipelines-devtest.yml
frontend/kesaseteli/handler/azure-pipelines-stageprod.yml
frontend/kesaseteli/youth/azure-pipelines-devtest.yml
frontend/kesaseteli/youth/azure-pipelines-stageprod.yml

- fixed paths to include to trigger specific pipelines. Especially shared code is forgotten that when it changes, most of the services should be built
- added pipelines for kesäseteli handler ui

Fix azure pipeline triggers

---

.github/workflows/bf-review.yml
frontend/benefit/handler/package.json

Run the handler UI in the KuVa review environment

HL-400: handler UI configuration for the KuVa review environment

---

localdevelopment/benefit/nginx/nginx.conf

Fix the changed port in nginx configuration

BF: fix local development nginx config for handler UI

---

backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py

Prevent a person with the same social security number from activating
more than one youth application.
Add test test_youth_applications_dual_activate_unexpired_inactive.
YJDH-461

YJDH-461 | KS-Backend: Prevent activating multiple youth applications

---

frontend/benefit/applicant/src/hooks/useFormActions.tsx

Applicant shallow fix test

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationReview/ApplicationReview.tsx
frontend/benefit/handler/src/components/applicationReview/employmentAppliedMoreView/EmploymentAppliedMoreView.tsx
frontend/benefit/handler/src/components/applicationReview/employmentAppliedMoreView/useEmploymentAppliedMoreView.ts
frontend/benefit/handler/src/components/applicationReview/employmentAppliedMoreView/utils/validation.ts
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryBenefitCalculatorView.tsx
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/useSalaryBenefitCalculatorData.ts
frontend/benefit/handler/src/constants.ts
frontend/benefit/handler/src/hooks/useHandlerReviewActions.ts
frontend/benefit/handler/src/types/application.d.ts
frontend/shared/src/components/forms/fields/dateFieldsSeparator/DateFieldsSeparator.sc.ts
frontend/shared/src/components/forms/fields/dateFieldsSeparator/DateFieldsSeparator.tsx

- Use real data for salary calculator
- Validate date fields

Hl 403/validate dates in calculator

---

backend/tet/azure-pipelines-devtest.yml
backend/tet/azure-pipelines-stageprod.yml
frontend/tet/admin/azure-pipelines-devtest.yml
frontend/tet/admin/azure-pipelines-stageprod.yml
frontend/tet/employer/azure-pipelines-devtest.yml
frontend/tet/employer/azure-pipelines-stageprod.yml
frontend/tet/youth/azure-pipelines-devtest.yml
frontend/tet/youth/azure-pipelines-stageprod.yml

Added pipeline config files. Please check if the triggers are the way you need them

Pipeline yaml files

---

backend/tet/azure-pipelines-devtest.yml
backend/tet/azure-pipelines-stageprod.yml
frontend/tet/admin/azure-pipelines-devtest.yml
frontend/tet/admin/azure-pipelines-stageprod.yml
frontend/tet/employer/azure-pipelines-devtest.yml
frontend/tet/employer/azure-pipelines-stageprod.yml
frontend/tet/youth/azure-pipelines-devtest.yml
frontend/tet/youth/azure-pipelines-stageprod.yml

Added pipeline config files. Please check if the triggers are the way you need them

Added pipeline yaml files

---

frontend/benefit/handler/src/components/applicationReview/employmentAppliedMoreView/EmploymentAppliedMoreView.tsx
frontend/shared/src/utils/__tests__/date.utils.test.ts
frontend/shared/src/utils/date.utils.ts

Copy the method days360 from backend and fix diffMonths method to follow Excel Days360 function

Hl 403/fix calculating duration in months

---

frontend/kesaseteli/handler/public/locales/en/common.json
frontend/kesaseteli/handler/public/locales/fi/common.json
frontend/kesaseteli/handler/public/locales/sv/common.json
frontend/kesaseteli/youth/browser-tests/index-page/indexPage.components.ts
frontend/kesaseteli/youth/browser-tests/index-page/indexPage.testcafe.ts
frontend/kesaseteli/youth/browser-tests/index-page/userActions.testcafe.ts
frontend/kesaseteli/youth/browser-tests/notification-page/activatedPage.components.ts
frontend/kesaseteli/youth/browser-tests/thank-you-page/thankYouPage.components.ts
frontend/kesaseteli/youth/public/locales/en/common.json
frontend/kesaseteli/youth/public/locales/fi/common.json
frontend/kesaseteli/youth/public/locales/sv/common.json
frontend/kesaseteli/youth/src/__tests__/utils/components/get-email-in-use-page-api.ts
frontend/kesaseteli/youth/src/__tests__/utils/components/get-thankyou-page-api.ts
frontend/kesaseteli/youth/src/pages/activated.tsx

Translations for Youth Service

YJDH-438: Youth service translations

---

backend/kesaseteli/applications/api/v1/views.py

PostgreSQL uses fi_FI.utf8 collation instead of fi_FI.UTF8. Checked
locally in Docker PostgreSQL pg_collation.collname.
Also simplify the transaction use in SchoolListView.preferred_sorter.
YJDH-473
Tested locally in Docker:
- `fi_FI.utf8` collation got used and `test_schools_list_returns_sorted_collection` passed with it.
- Using the "No collation override" by manually changing the tested collation list to start with inexistent collations and end with `None` also worked and `test_schools_list_returns_sorted_collection` passed with it.

YJDH-473 | KS-Backend: Fix fi_FI.utf8 collation name

---

frontend/benefit/handler/src/components/applicationReview/employmentAppliedMoreView/EmploymentAppliedMoreView.tsx
frontend/benefit/handler/src/components/applicationReview/employmentAppliedMoreView/useEmploymentAppliedMoreView.ts
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryBenefitCalculatorView.tsx
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/useSalaryBenefitCalculatorData.ts
frontend/benefit/handler/src/constants.ts
frontend/benefit/handler/src/hooks/useCalculatorData.ts
frontend/benefit/handler/src/hooks/useHandlerReviewActions.ts
frontend/benefit/handler/src/types/application.d.ts

Move common functions and values to a separate hook for getting calculator data

Refactor hooks for getting calculator data

---

frontend/kesaseteli/youth/public/locales/en/common.json
frontend/kesaseteli/youth/public/locales/fi/common.json
frontend/kesaseteli/youth/public/locales/sv/common.json
frontend/kesaseteli/youth/src/pages/already_assigned.tsx

- Remove untranslated message from already assigned page

Last minute translation fixes

---

backend/benefit/applications/api/v1/application_batch_views.py
backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/models.py
backend/benefit/applications/services/applications_csv_report.py
backend/benefit/applications/services/csv_export_base.py
backend/benefit/applications/services/talpa_integration.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/factories.py
backend/benefit/applications/tests/test_application_batch_api.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/applications/tests/test_applications_csv_report.py
backend/benefit/applications/tests/test_talpa_integration.py
backend/benefit/calculator/models.py
backend/benefit/calculator/tests/test_calculator_api.py

Includes HL-428: Finnish column headings for CSV data
Also includes HL-408: application cancellation reason.
Implementing CSV export this way also covers the functionality in
HL-425.

HL-426: CSV export of application data

---

frontend/benefit/handler/src/components/applicationReview/actions/editAction/EditAction.tsx

Fix loading button when opening application

---

backend/benefit/applications/api/v1/application_batch_views.py
backend/benefit/applications/api/v1/views.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/calculator/api/v1/views.py
backend/benefit/messages/views.py
backend/shared/shared/audit_log/viewsets.py

use AuditLoggingModelViewSet in the benefit backend

HL-366: use AuditLoggingModelViewSet in the benefit backend

---

backend/benefit/applications/api/v1/views.py
backend/benefit/applications/services/applications_csv_report.py
backend/benefit/applications/tests/factories.py
backend/benefit/applications/tests/test_applications_csv_report.py

Temporary solution for downloading application CSV data, so that application handling can be done in Excel in the MVP
backend/benefit/applications/tests/test_applications_csv_report.py

HL-427: API for downloading CSV

---

.github/workflows/bf-pytest.yml
backend/benefit/README.md
backend/benefit/common/tests/conftest.py
backend/benefit/locale/en/LC_MESSAGES/django.po
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/se/LC_MESSAGES/django.po
backend/docker/benefit.Dockerfile
docker-compose.benefit.yml

* translation files
* Run "compilemessages" at deployment time
* Ensure gettext is installed in the container

HL-466: add fi/se translations to backend

---

frontend/tet/admin/src/backend-api/linked-events-api.ts
frontend/tet/admin/src/components/editor/classification/Classification.tsx

TETP-121: Fix keywords labels disappearing

---

frontend/kesaseteli/handler/public/locales/fi/common.json
frontend/kesaseteli/handler/src/pages/403.tsx
frontend/shared/src/components/pages/ForbiddenPage.tsx

Add static forbidden page for kesäseteli handler application

YJDH-253: Add static forbidden page for handler application

---

backend/benefit/calculator/rules.py
backend/benefit/calculator/tests/test_models.py

If pay subsidy % is 100 then maximum monthly pay subsidy is 1800eur
otherwise the maximum is 1400eur
backend/benefit/calculator/tests/test_models.py: test_pay_subsidy_maximum

HL-476: Calculate maximum amount of pay subsidy based on pay subsidy percent

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationsArchive/ApplicationsArchive.sc.ts
frontend/benefit/handler/src/components/applicationsArchive/ApplicationsArchive.tsx
frontend/benefit/handler/src/components/applicationsArchive/useApplicationsArchive.ts
frontend/benefit/handler/src/components/header/useHeader.ts
frontend/benefit/handler/src/constants.ts
frontend/benefit/handler/src/pages/archive/index.tsx
frontend/benefit/handler/src/types/application.d.ts
frontend/benefit/handler/src/utils/common.ts
frontend/shared/src/utils/menu.utils.ts

-Archive page implemented with fetching data
-Fixed navigation bug

HL-440,441: Archive page for handler

---

backend/tet/events/api/v1/views.py
backend/tet/events/services.py
backend/tet/tet/urls.py
frontend/tet/admin/public/locales/en/common.json
frontend/tet/admin/public/locales/fi/common.json
frontend/tet/admin/public/locales/sv/common.json
frontend/tet/admin/src/components/base/ConfirmDialog.tsx
frontend/tet/admin/src/components/jobPostings/JobPostingsListItemMenu.tsx
frontend/tet/admin/src/hooks/backend/usePublishTetPosting.ts
frontend/tet/admin/src/hooks/context/useConfirm.ts
frontend/tet/admin/src/store/DialogContext.tsx

Implements backend operations for publishing and connects JobPostingsListItemMenu's publish button.
Note that preview's publish button still needs to be connected.

TETP-123: Publish TET Posting

---

frontend/tet/admin/public/locales/en/common.json
frontend/tet/admin/public/locales/fi/common.json
frontend/tet/admin/public/locales/sv/common.json
frontend/tet/admin/src/auth/AuthProvider.tsx
frontend/tet/admin/src/components/login/InfoboxContent.sc.ts
frontend/tet/admin/src/pages/_app.tsx
frontend/tet/admin/src/pages/editstatic.tsx
frontend/tet/admin/src/pages/index.tsx
frontend/tet/admin/src/pages/login.tsx
frontend/tet/admin/src/pages/new.tsx

TETP-99: Add AuthProvider and withAuth to pages

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationReview/companyInfoView/CompanyInfoView.tsx

Hl 472/handling view missing info

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationReports/ApplicationReports.tsx
frontend/benefit/handler/src/components/applicationReports/ReportsSection.tsx
frontend/benefit/handler/src/components/applicationReports/useApplicationReports.ts
frontend/benefit/handler/src/components/header/useHeader.ts
frontend/benefit/handler/src/components/reportView/ReportView.tsx
frontend/benefit/handler/src/constants.ts
frontend/benefit/handler/src/pages/reports/index.tsx
frontend/benefit/handler/src/types/application.d.ts
frontend/shared/src/utils/file.utils.ts

Hl 423/exporting applications UI

---

backend/tet/tet/settings.py

Fix tet django conf

---

backend/kesaseteli/applications/api/v1/views.py

Log errors in youth application creation:
- As info:
- already_assigned:
- "Youth application submission rejected. Return HTTP status code:
400. YouthApplicationRejectedReason: already_assigned."
- email_in_use:
- "Youth application submission rejected. Return HTTP status code:
400. YouthApplicationRejectedReason: email_in_use."
- As errors:
- ValidationError exceptions, listing the related fields' names and
their error codes, e.g. "Youth application submission rejected
because of validation error. Validation error codes:
{'social_security_number': ['invalid']}"
YJDH-502

YJDH-502 | KS-Backend: Add error logging to youth application creation

---

frontend/benefit/handler/src/hooks/useApplicationActions.ts
frontend/benefit/handler/src/types/application.d.ts

Fix updating application grantedAsDeMinimisAid

---

frontend/tet/admin/src/components/editor/DateInput.tsx

TETP-126 Change DateInput to use i18n settings

---

frontend/shared/src/components/content/Content.sc.ts
frontend/shared/src/components/layout/Layout.sc.ts

HL-496: Fix layout height

---

frontend/benefit/handler/src/components/applicationHeader/ApplicationHeader.tsx

- Header should not show when error, or application in draft mode

HL-492: Handler application header fix

---

frontend/benefit/handler/src/components/header/useHeader.ts

HL-495: Hide approved applications navi item

---

frontend/tet/admin/src/components/editor/form/ActionButtons.tsx

TETP-132 Admin can publish posting in edit view

---

frontend/shared/src/components/layout/Layout.sc.ts

Fix frontend shared layout height

---

backend/kesaseteli/applications/templates/youth_summer_voucher_email.html

Set youth summer voucher HTML email font to Arial Helvetica sans-serif.
YJDH-369

YJDH-369 | KS-Backend: Set font for youth summer voucher email

---

frontend/tet/admin/src/pages/copystatic.tsx

TETP-151 Load keywords and languageoptions in copy page

---

frontend/tet/admin/src/backend-api/linked-events-api.ts
frontend/tet/admin/src/components/editor/DateInput.tsx
frontend/tet/admin/src/components/editor/classification/Classification.tsx
frontend/tet/admin/src/components/editor/postingDetails/PostingDetails.tsx
frontend/tet/admin/src/pages/new.tsx

TETP-154 add keyword UI translations

---

frontend/tet/admin/src/hooks/backend/useDeleteTetPosting.ts
frontend/tet/admin/src/hooks/backend/useUpsertTetPosting.ts

TET: Append trailing slash to avoid CSRF issue

---

frontend/tet/admin/src/components/editor/Dropdown.tsx
frontend/tet/admin/src/components/editor/classification/Classification.tsx

TETP Add required rule for the language selector

---

frontend/benefit/applicant/src/pages/login.tsx
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/auth/AuthProvider.tsx
frontend/benefit/handler/src/components/layout/Layout.tsx
frontend/benefit/handler/src/hooks/useLogin.ts
frontend/benefit/handler/src/hooks/useUserQuery.ts
frontend/benefit/handler/src/pages/_app.tsx
frontend/benefit/handler/src/pages/login.tsx
frontend/benefit/shared/src/backend-api/backend-api.ts

-Login page with button click redirect to login (for AD users)
-Auth state and secure pages

HL-436: Handler authentication

---

frontend/shared/src/components/header/Header.tsx
frontend/tet/admin/src/components/header/Header.tsx

Allow title click handler on base header

---

backend/shared/shared/azure_adfs/auth.py
frontend/tet/admin/Dockerfile
frontend/tet/admin/src/backend-api/linked-events-api.ts
frontend/tet/youth/Dockerfile

* also adds a missing build arg
* also fixes an issue with AD login

TET Admin: read Linked Events URL from build args

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/step2/ApplicationFormStep2.tsx

Fix translations

---

frontend/tet/admin/Dockerfile
frontend/tet/youth/Dockerfile

TET: Fix youth public copy location

---

backend/benefit/applications/benefit_aggregation.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/applications/tests/test_benefit_aggregation.py
backend/benefit/locale/en/LC_MESSAGES/django.po
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/sv/LC_MESSAGES/django.po
backend/benefit/messages/automatic_messages.py

Fix errors in backend translations and update translation files:
* Add translation for the "application opened" message
* Update other translations, too, after running "makemessages"
* rename se -> sv in locale/

HL-487: update backend translations

---

backend/benefit/companies/services.py

Fix bug that prevented creation of company after logging in

Helsinki Benefit bugfix: fix creation of new companies after login

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/step2/ApplicationFormStep2.tsx

Fix workingHours label overflow when using Swedish

---

frontend/benefit/handler/src/components/applicationReports/ApplicationReports.tsx
frontend/benefit/handler/src/components/applicationReports/useApplicationReports.ts
frontend/benefit/handler/src/hooks/useReportsApplicationBatchesQuery.ts
frontend/benefit/shared/src/backend-api/backend-api.ts

Fix getting last export date for handler reports page

---

frontend/benefit/handler/src/components/applicationsArchive/ApplicationsArchive.tsx
frontend/shared/src/components/table/Table.tsx

Sort archive list by handledAt

---

frontend/benefit/handler/src/components/applicationReports/ApplicationReports.tsx
frontend/benefit/handler/src/components/applicationReports/useApplicationReports.ts

Fix getting last download date in reports page

---

.github/workflows/audit.yml
.github/workflows/bf-applicant-frontend-tests.yml
.github/workflows/bf-handler-frontend-tests.yml
.github/workflows/bf-py-coding-style.yml
.github/workflows/bf-pytest.yml
.github/workflows/bf-review.yml
.github/workflows/bf-shared-frontend-tests.yml
.github/workflows/codeql-analysis.yml
.github/workflows/ks-acceptance-tests-staging-env.yml
.github/workflows/ks-acceptance-tests-test-env.yml
.github/workflows/ks-empl-frontend-tests.yml
.github/workflows/ks-handler-frontend-tests.yml
.github/workflows/ks-py-coding-style.yml
.github/workflows/ks-pytest.yml
.github/workflows/ks-review.yml
.github/workflows/ks-shared-frontend-tests.yml
.github/workflows/ks-youth-frontend-tests.yml
.github/workflows/shared-frontend-tests.yml
.github/workflows/te-admn-frontend-tests.yml
.github/workflows/te-empl-frontend-tests.yml
.github/workflows/te-py-coding-style.yml
.github/workflows/te-pytest.yml
.github/workflows/te-review.yml
.github/workflows/te-yout-frontend-tests.yml
.github/workflows/yarn-audit-scheduled.yml
frontend/shared/src/components/app/BaseApp.tsx

Let's try if that has something to do with the failing browser tests

Revert actions/*@v3 upgrades

---

frontend/benefit/applicant/src/components/header/useHeader.ts
frontend/benefit/applicant/src/hooks/useApplicationQuery.ts

- Messenger is available for applicant already in handling more
- Fixed the new application count in the header
- Fixed the opening the application with new messages

HL-510,HL-512: Messenger improvements

---

backend/kesaseteli/applications/api/v1/views.py

Wrap additional_info endpoint with @transaction.atomic
YJDH-504

YJDH-504 | KS-Backend: Wrap additional_info endpoint with @transaction.atomic

---

.env.benefit-backend.example
backend/benefit/README.md
backend/benefit/helsinkibenefit/settings.py

Fix issues identified during Kesäseteli onboarding meeting:
* Helsinki benefit example environment file for the backend
* Also update the backend readme file
* Helsinki-benefit: configure DEFAULT_AUTO_FIELD

Fix issues identified during Kesäseteli onboarding meeting

---

backend/benefit/companies/tests/test_api.py
backend/shared/shared/service_bus/service_bus_client.py

In suomi.fi test env, Aktivenakusteri Oy does not have business line data in the YTJ response. It's possible similar issues would be encountered in production environment, too. Add guard against this.
backend/benefit/companies/tests/test_api.py:test_get_organisation_from_service_bus_missing_business_line

HL-513: handle missing business line data in YTJ response

---

frontend/benefit/applicant/src/hooks/useApplicationsQuery.ts
frontend/benefit/applicant/src/hooks/useCompanyQuery.ts
frontend/benefit/handler/src/hooks/useApplicationsQuery.ts
frontend/benefit/shared/src/backend-api/backend-api.ts

Use another endpoint to get application lists to reduce performance issues

HL-467: Application list improvements frontend

---

frontend/benefit/applicant/next.config.js
frontend/benefit/handler/next.config.js

HL-520: Disable x-powered-by header

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json

HL-514: Missing translations

---

frontend/tet/admin/src/components/editor/classification/Classification.tsx
frontend/tet/admin/src/components/editor/companyInfo/CompanyInfo.tsx
frontend/tet/shared/src/backend-api/linked-events-api.ts
frontend/tet/shared/src/hooks/backend/useKeywordType.ts
frontend/tet/shared/src/types/linkedevents.d.ts
frontend/tet/youth/src/backend-api/backend-api.ts
frontend/tet/youth/src/components/jobPostingSearch/JobPostingSearch.tsx
frontend/tet/youth/src/components/jobPostings/JobPostings.tsx

TET Add correct keyword list in youth event filter

---

frontend/benefit/handler/src/components/applicationsArchive/ApplicationsArchive.tsx
frontend/benefit/handler/src/components/applicationsArchive/useApplicationsArchive.ts

Cannot use react-table sortBy function because the date pass in is just a string, sort manually

Fix sorting handler archive list 

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/footer/Footer.sc.ts
frontend/benefit/applicant/src/components/layout/Layout.tsx
frontend/benefit/applicant/src/components/supportingContent/SupportingContent.sc.ts
frontend/benefit/applicant/src/components/supportingContent/SupportingContent.tsx
frontend/benefit/applicant/src/pages/index.tsx

Add contact supporting content

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/utils/validation.ts
frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/validation.ts
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/shared/src/constants.ts

HL-527: Fix number validation message

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json

Missing tooltip aria label translations in benefit applicant

---

frontend/benefit/applicant/src/hooks/useApplicationQuery.ts

HL-540: Add staletime

---

frontend/benefit/applicant/next-env.d.ts
frontend/benefit/handler/src/components/applicationHeader/ApplicationHeader.tsx

-Initials removed
-one column added with full name of the handler to the application header

HL-499: Replace handlers initials with full name in header

---

frontend/benefit/applicant/src/auth/AuthProvider.tsx
frontend/benefit/applicant/src/components/header/Header.tsx
frontend/benefit/applicant/src/components/layout/Layout.tsx
frontend/benefit/applicant/src/components/termsOfService/TermsOfService.tsx
frontend/benefit/applicant/src/constants.ts
frontend/benefit/applicant/src/hooks/useApproveTermsOfServiceMutation.ts
frontend/benefit/applicant/src/hooks/useTermsOfServiceData.ts
frontend/benefit/applicant/src/hooks/useUserQuery.ts
frontend/benefit/applicant/src/pages/login.tsx
frontend/benefit/applicant/src/types/application.d.ts

Show terms of service everytime user logins

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/step1/utils/validation.ts
frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/validation.ts
frontend/benefit/shared/src/constants.ts

Fix the error message for phone max length validation

---

frontend/shared/src/server/next-server.js

HL-520: Remove x-powered-by from express

---

frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/handler/public/locales/sv/common.json

HL-527: Translations typo fix

---

frontend/benefit/applicant/src/components/layout/Layout.tsx
frontend/benefit/applicant/src/components/termsOfService/TermsOfService.tsx

Show header in terms of service so user can change language

---

.env.kesaseteli.example
backend/kesaseteli/applications/api/v1/serializers.py
backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/enums.py
backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/tests/data/mock_vtj.py
backend/kesaseteli/applications/tests/test_misc.py
backend/kesaseteli/applications/tests/test_mock_vtj.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/common/tests/factories.py
backend/kesaseteli/common/tests/test_factories.py
backend/kesaseteli/common/tests/test_utils.py
backend/kesaseteli/common/utils.py
backend/kesaseteli/kesaseteli/settings.py
backend/kesaseteli/requirements-dev.txt
backend/kesaseteli/requirements.in
backend/kesaseteli/requirements.txt
backend/shared/shared/vtj/vtj_client.py

VTJ integration related environment variables:
- VTJ_PERSONAL_ID_QUERY_URL
- e.g. https://example.org/api/HenkilonTunnuskysely
- VTJ_USERNAME
- VTJ_PASSWORD
- VTJ_TIMEOUT
Add support for "Send anyway" button by the use of
request_additional_information parameter when submitting a new youth
application.
If not using "Send anyway" button when submitting a new youth
application a new error code "inadmissible_data" will be returned if
the social security number is not valid or the applicant is dead
according to VTJ data. Similarly "please_recheck_data" will be returned
if the last name doesn't match the last name in VTJ data.
Add support for automatic acceptance of youth applications on their
submittal if they pass the following tests:
- Social security number is valid according to VTJ data
- …

YJDH-364 | KS-Backend: Add real & mocked VTJ integration

---

backend/benefit/azure-pipelines-master.yml
backend/benefit/azure-pipelines-release.yml
backend/kesaseteli/azure-pipelines-kesaseteli-api-master.yml
backend/kesaseteli/azure-pipelines-kesaseteli-api-release.yml
backend/tet/azure-pipelines-devtest.yml
backend/tet/azure-pipelines-stageprod.yml
frontend/benefit/handler/azure-pipelines-master.yml
frontend/benefit/handler/azure-pipelines-release.yml
frontend/kesaseteli/azure-pipelines-kesaseteli-ui-master.yml
frontend/kesaseteli/azure-pipelines-kesaseteli-ui-release.yml
frontend/kesaseteli/handler/azure-pipelines-devtest.yml
frontend/kesaseteli/handler/azure-pipelines-stageprod.yml
frontend/tet/admin/azure-pipelines-devtest.yml
frontend/tet/admin/azure-pipelines-stageprod.yml
frontend/tet/employer/azure-pipelines-devtest.yml
frontend/tet/employer/azure-pipelines-stageprod.yml
frontend/tet/youth/azure-pipelines-devtest.yml
frontend/tet/youth/azure-pipelines-stageprod.yml

added batch processing to pipelines

added batch processing to pipelines

---

backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py

Disregard rejected youth applications when checking whether a social
security number or email is used already. Update related test.
YJDH-532

YJDH-532 | KS-Backend: Disregard rejected youth applications

---

frontend/tet/admin/src/components/editor/EditorErrorNotification.tsx

TETP Fix error toast before submit

---

frontend/tet/youth/src/components/jobPostingList/JobPostingList.tsx
frontend/tet/youth/src/components/jobPostings/JobPostings.tsx
frontend/tet/youth/src/hooks/backend/useGetPostings.ts
frontend/tet/youth/src/pages/postings.tsx

TETP Add page_size query param for the events. Change to correct list slicing

---

frontend/tet/admin/src/components/editor/companyInfo/CompanyInfo.tsx
frontend/tet/admin/src/store/PreviewContext.tsx
frontend/tet/shared/src/components/posting/postingContent/PostingContent.tsx
frontend/tet/shared/src/components/posting/postingHero/PostingHero.tsx

TETP-207 Fix required validation for the location field

---

frontend/tet/admin/public/locales/en/common.json
frontend/tet/admin/public/locales/fi/common.json
frontend/tet/admin/public/locales/sv/common.json
frontend/tet/admin/src/components/footer/Footer.tsx
frontend/tet/youth/public/locales/en/common.json
frontend/tet/youth/public/locales/fi/common.json
frontend/tet/youth/public/locales/sv/common.json
frontend/tet/youth/src/components/footer/Footer.tsx

TETP-84 Add more information link to tet youth footer

---

.github/workflows/bf-review.yml
.github/workflows/ks-review.yml
.github/workflows/te-review.yml

...because they cause harm on kuva infra: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-568

Yjdh-568: remove useless cron jobs

---

frontend/kesaseteli/youth/public/locales/en/common.json
frontend/kesaseteli/youth/public/locales/fi/common.json
frontend/kesaseteli/youth/public/locales/sv/common.json

YJDH-585: ks-youth translations for additional information application

---

.github/workflows/ks-acceptance-tests-staging-env.yml
frontend/kesaseteli/employer/public/locales/en/common.json
frontend/kesaseteli/employer/public/locales/sv/common.json

YJDH-584: Add new translations to kesäseteli/employer

---

frontend/tet/youth/src/components/jobPostingCard/JobPostingCardKeywords.tsx

TETP Show only method keywords on youth mobile list

---

frontend/tet/youth/public/locales/en/common.json
frontend/tet/youth/public/locales/fi/common.json
frontend/tet/youth/public/locales/sv/common.json
frontend/tet/youth/src/components/jobPostings/JobPostings.tsx
frontend/tet/youth/src/components/noResults/NoResults.tsx

TETP-170 Add tet youth zero results text

---

frontend/tet/youth/src/pages/_app.tsx

TETP-247 Matomo analytics script

---

frontend/tet/admin/src/pages/_app.tsx

TETP-246: Import css from React Toastify

---

backend/kesaseteli/kesaseteli/settings.py

csrf use sessions

---

frontend/tet/admin/src/backend-api/backend-api.ts

TETP fix image upload

---

frontend/tet/shared/src/components/posting/postingHero/PostingHero.tsx
frontend/tet/youth/public/locales/en/common.json
frontend/tet/youth/public/locales/fi/common.json
frontend/tet/youth/public/locales/sv/common.json
frontend/tet/youth/src/components/noResults/NoResults.tsx
frontend/tet/youth/src/pages/postings/show.tsx

Show number as falsy in photographer tag. Add correct 'few results' text

---

frontend/kesaseteli/shared/src/query-client/create-query-client.ts
frontend/shared/src/backend-api/BackendAPIProvider.tsx
frontend/shared/src/cookies/get-last-cookie-value.ts

read last cookie value for yjdhcrsftoken

---

frontend/tet/admin/public/locales/en/common.json
frontend/tet/admin/public/locales/fi/common.json
frontend/tet/admin/public/locales/sv/common.json
frontend/tet/youth/public/locales/en/common.json
frontend/tet/youth/public/locales/fi/common.json
frontend/tet/youth/public/locales/sv/common.json

This PR changes translations in TET source code. Keyword translations have been updated in Linked Events test and prod.

TETP-237: What kind of TET?

---

backend/tet/events/jobs/hourly/clean_unused_images.py
backend/tet/events/linkedevents.py

Add a job that removes images that are not used by any TET job posting.
When a user removes the image from a job posting, this only removes the link to the image. Thus this job is needed to actually remove the images.

TETP-223: Add job to clean unused uploads

---

backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/kesaseteli/settings.py

Temp csrf excemption

---

frontend/kesaseteli/employer/public/locales/en/common.json
frontend/kesaseteli/employer/public/locales/fi/common.json
frontend/kesaseteli/employer/public/locales/sv/common.json
frontend/kesaseteli/shared/src/backend-api/backend-api.ts
frontend/kesaseteli/shared/src/query-client/create-query-client.ts
frontend/shared/src/backend-api/BackendAPIProvider.tsx
frontend/shared/src/cookies/get-last-cookie-value.ts
frontend/tet/admin/src/backend-api/backend-api.ts

fix lint errors + translations

---

frontend/kesaseteli/shared/src/query-client/create-query-client.ts
frontend/shared/src/backend-api/BackendAPIProvider.tsx

Remove duplicated getLastCookieValue imports from main branch.
Related to PR #1258 and its merging to main in bf99100bbfb76c9e4eeac777fd9626e11e0be4b7.

YJDH-618 | Remove duplicated getLastCookieValue imports from main branch

---

backend/kesaseteli/applications/api/v1/views.py

Remove @csrf_exempt from:
- EmployerApplicationViewSet.create
- EmployerApplicationViewSet.update
- EmployerSummerVoucherViewSet.post_attachment
- EmployerSummerVoucherViewSet.handle_attachment

YJDH-620 | KS-Backend: Remove csrf_exempts

---

backend/kesaseteli/applications/tests/test_youth_applications_api.py

Suffix tests with "__vtj_disabled" because with VTJ integration enabled
processing email wouldn't be sent:
- test_youth_application_processing_email_sending_on_activate
- test_youth_application_processing_email_language_on_activate
Enable test cases with VTJ integration enabled:
- test_youth_application_processing_email_sending_after_additional_info
- test_youth_application_processing_email_language_after_additional_...
YJDH-542
YJDH-506

YJDH-542 | KS-Backend: Add more processing email related tests

---

frontend/kesaseteli/youth/public/locales/sv/common.json

Fix misspelled translation

---

backend/benefit/applications/api/v1/serializers.py

See details here: https://helsinkisolutionoffice.atlassian.net/browse/HL-562
This is hard to reproduce and probably concerns only local environment because user has changed to anonymous user after session has expired. The situation happens at least when the flag DISABLE_AUTHENTICATION is 1.

HL-562: Fix session expiration error

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/calculator/api/v1/serializers.py
backend/benefit/calculator/tests/test_calculator_api.py
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/hooks/useHandlerReviewActions.ts

HL-553: Error in manual calculator. Backend validation fails because both calculation and paysubsidies objects are sent to backend. Let's change it so that validation depends on checkbox value.

HL-553: Error in manual calculator 

---

backend/benefit/calculator/api/v1/serializers.py
backend/benefit/calculator/tests/test_calculator_api.py

Validate paysubsidies only when application is in handling state. Also added an unit test.
This branch is on the top of [hl-566-augment-authentication-disabling](https://github.com/City-of-Helsinki/yjdh/tree/hl-566-augment-authentication-disabling)

HL-553: Validate paysubsidies only when application is in handling state

---

frontend/kesaseteli/youth/azure-pipelines-stageprod.yml

The way yjdh repository is being used currently the main branch and develop branch should be codewise identical after the develop branch has been merged to the main branch. This change was only in the main branch so merging it into develop.
–

Merge 0d6c979afd5d80da29997fc361d3eaa1778d245b main changes to develop

---

backend/kesaseteli/applications/jobs/daily/clean_inactive_youth_applications.py
backend/kesaseteli/applications/jobs/daily/clean_old_attachments.py
backend/kesaseteli/applications/jobs/daily/clean_old_employer_applications.py
backend/kesaseteli/applications/jobs/daily/clean_old_youth_applications.py
backend/kesaseteli/applications/jobs/daily/clean_rejected_youth_applications.py
backend/kesaseteli/applications/jobs/daily/tests/test_clean_youth_applications.py
backend/kesaseteli/applications/tests/test_cron_job.py

- Clean all inactive youth applications older than week
- Clean all rejected youth applications older than one year
- Clean all youth applications older than five years

YJDH-422: Scheduled weekly Job to clean old youth applications

---

.github/workflows/bf-review.yml
.github/workflows/ks-review.yml
.github/workflows/te-review.yml
docker-compose.benefit.yml
docker-compose.employer.yml
docker-compose.handler.yml
docker-compose.tet-admin.yml
docker-compose.tet-youth.yml
docker-compose.tet.yml
docker-compose.youth.yml
frontend/Dockerfile
frontend/benefit/applicant/package.json
frontend/benefit/handler/package.json
frontend/kesaseteli/employer/package.json
frontend/kesaseteli/handler/package.json
frontend/kesaseteli/youth/package.json
frontend/start.js
frontend/tet/admin/package.json
frontend/tet/youth/package.json

Referring to discussion here: https://app.slack.com/client/T02DHG0DR/threads/thread/C02EHHFPQPL-1670827189.380059
and Platta ticket: https://helsinkisolutionoffice.atlassian.net/browse/PLATTA-4420
What is done:
- don't install lerna on production stage of dockerfile
- start server without using yarn script

yjdh-649: improve dockerfile for platta

---

frontend/kesaseteli/youth/browser-tests/youth-application.testcafe.ts

feat(yjdh-650): fix description in testcafe test

---

.env.tet.example

TET-backend: Set .env.tet.example HELSINKI_PROFILE_API_URL

---

backend/tet/tet/views.py

Logging level is set to warning so debugging is easy.
HL-600 (Debugging)

HL-600 | TET-Backend: Add debug printing to TetGDPRApiView.dispatch

---

backend/tet/tet/settings.py

TET-Backend: Adjust default GDPR API settings
HL-600

HL-600 | TET-Backend: Adjust default GDPR API settings

---

backend/benefit/README.md

HL-Backend: Link HL-582 in README.md related to NEXT_PUBLIC_MOCK_FLAG
HL-582

HL-582 | HL-Backend: Link HL-582 in README.md related to NEXT_PUBLIC_MOCK_FLAG

---

README.md

Refactor README a bit.
* Add description section
* Add requirements section
* Add "get started" section
* Add horizontal lines for each section
* Add and fix text formating
* Unify heading case

HL-610 | (WIP) Update README.md structure and fix formatting

---

backend/benefit/README.md
backend/benefit/applications/management/commands/seed.py
backend/benefit/applications/tests/factories.py
backend/benefit/applications/tests/test_application_tasks.py

Renamed and re-pushed the branch for the application seed command, because the build failed due to too long branch name.
Run pytest. 
Run the `python manage.py seed` and observe the created applications and their attachments

Hl 626 seed applications

---

backend/benefit/applications/api/v1/views.py
backend/benefit/applications/tests/test_applications_api.py
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.tsx
frontend/benefit/applicant/src/components/applications/applicationList/useApplicationList.ts
frontend/benefit/applicant/src/hooks/useApplicationsQuery.ts
frontend/benefit/handler/src/components/applicationList/useApplicationList.ts
frontend/benefit/handler/src/components/applicationsArchive/useApplicationsArchive.ts
frontend/benefit/handler/src/hooks/useApplicationsQuery.ts

* Reorder by date
* ~Might want to refactor to use a GET "sortby", "orderby" param from client~
* ☝️  Done
* Change label from 'created' to 'saved'

HL-229 | Reorder applications by date at handler and applicant list view 

---

backend/benefit/applications/management/commands/seed.py
frontend/benefit/applicant/src/components/applications/applicationList/useApplicationList.ts
frontend/benefit/handler/public/locales/fi/common.json

* "In Handling" applications were seeded with same date
* Draft applications would not be sorted by -created_at
* Add translations to handler footer

HL-634 | Small fixes for findings in sprint review

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/supportingContent/SupportingContent.tsx

* Remove phone numbers
* Add `mailto:` hyperlink
See specs at https://helsinkisolutionoffice.atlassian.net/browse/HL-628?atlOrigin=eyJpIjoiODQ0OWY0OGU5ZGM2NGVmYThmYmUyMGU2MDc4YzRlYzkiLCJwIjoiaiJ9

HL-628 | Replace phone numbers with email

---

frontend/benefit/handler/browser-tests/json/single-handling.json
frontend/benefit/handler/browser-tests/json/single-received.json
frontend/benefit/handler/browser-tests/page-model/ActionBarHandling.ts
frontend/benefit/handler/browser-tests/page-model/ActionBarReceived.ts
frontend/benefit/handler/browser-tests/page-model/ApplicationReview.ts
frontend/benefit/handler/browser-tests/pages/archive.testcafe.ts
frontend/benefit/handler/browser-tests/pages/index.testcafe.ts
frontend/benefit/handler/browser-tests/pages/single.testcafe.ts
frontend/benefit/handler/package.json

Add primitive test suite to check for application review and change it from:
* received 👉  handling
You need chrome.
```
cd frontend/benefit/handler
yarn
yarn browser-test 
yarn browser-test:ci # headless
```

HL-630 | Simple browser test for single received application

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/applications/tests/test_applications_report.py
backend/benefit/terms/api/v1/views.py
backend/benefit/terms/tests/factories.py

Fix naive datetime warning by using timezone-aware datetime objects. Ran black here, so a lot of formatting changes.

HL-622 Fix naive datetime warnings

---

frontend/benefit/applicant/src/components/applications/Applications.sc.ts
frontend/benefit/applicant/src/components/applications/forms/application/step3/ApplicationFormStep3.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step3/attachmentsList/AttachmentsList.tsx
frontend/benefit/applicant/src/components/attachmentsIngress/AttachmentsIngress.sc.ts
frontend/benefit/applicant/src/pages/_app.tsx
frontend/benefit/applicant/src/pages/application/index.tsx
frontend/benefit/applicant/src/pages/index.tsx
frontend/benefit/applicant/src/styles/globals.css
frontend/shared/src/components/attachments/AttachmentsList.tsx

* Change order of headings to incremental
* Change attachment list so that it's wrapped in `<ul>` and each item is a `<li>`
* Add `<title>` to every page (was previously undefined)

HL-532 | Fix bunch of accessability issues with attachments

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/header/Header.tsx
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/header/Header.tsx

Fix skip-to-content links for handler and applicant.

HL-312 | Fix skip-to-content texts

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json

Not much here, inspected a JIRA ticket that had been resolved in the past. Saw this and decided to add spaces 😬

HL-447 | Improve readability by adding space between dates

---

frontend/benefit/applicant/src/components/applications/pageContent/PageContent.tsx
frontend/benefit/applicant/src/components/applications/pageContent/usePageContent.ts
frontend/benefit/applicant/src/styles/globals.css
frontend/shared/src/styles/theme.ts
frontend/shared/src/types/styled-components.d.ts

Replace custom stepper with HDS version. This requires some pretty nasty hacks (looking at `pointer-events: none;`), but 🤷  no way to disable button behaviour from configuration. I will make a request to #designsystem team about the possible additions.

HL-535 | Replace custom Stepper with HDS version

---

backend/benefit/messages/views.py

New pull request as Maks was not available to give "passed" blessings.

HL-685 | Never send a note via email to an applicant

---

azure-pipelines/kesaseteli-api-master.yml
azure-pipelines/kesaseteli-api-release.yml
azure-pipelines/kesaseteli-api-review.yml
azure-pipelines/kesaseteli-employer-release.yml
azure-pipelines/kesaseteli-employer-review.yml
azure-pipelines/kesaseteli-employer-test.yml
azure-pipelines/kesaseteli-handler-release.yml
azure-pipelines/kesaseteli-handler-review.yml
azure-pipelines/kesaseteli-handler-test.yml
azure-pipelines/kesaseteli-youth-release.yml
azure-pipelines/kesaseteli-youth-review.yml
azure-pipelines/kesaseteli-youth-test.yml

New azure pipelines for kesaseteli, especially including the review pipeline

---

.github/workflows/audit.yml

Use audit check in prs instead of scheduled job

---

azure-pipelines/kesaseteli-api-review.yml
azure-pipelines/kesaseteli-api-test.yml
azure-pipelines/kesaseteli-employer-release.yml
azure-pipelines/kesaseteli-employer-review.yml
azure-pipelines/kesaseteli-employer-test.yml
azure-pipelines/kesaseteli-handler-release.yml
azure-pipelines/kesaseteli-handler-review.yml
azure-pipelines/kesaseteli-handler-test.yml
azure-pipelines/kesaseteli-youth-release.yml
azure-pipelines/kesaseteli-youth-review.yml
azure-pipelines/kesaseteli-youth-test.yml

- fix wrong project/repository 
- fix kesaseteli-api has wrong template

fix: azure pipelines

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationList/ApplicationList.sc.ts
frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/components/applicationsArchive/ApplicationsArchive.tsx
frontend/benefit/handler/src/components/footer/Footer.sc.ts
frontend/benefit/handler/src/components/footer/Footer.tsx
frontend/benefit/handler/src/context/AppContext.tsx
frontend/benefit/handler/src/pages/archive/index.tsx
frontend/benefit/handler/src/pages/index.tsx
frontend/benefit/handler/src/pages/reports/index.tsx
frontend/shared/src/components/table/Table.sc.ts

Add a tiny bit of contrast with background color on table views. There was a mechanism already in place to change background color per context but wires were not fully connected.

HL-678 | New looks for handler front page view

---

.github/workflows/release-please.yml
.release-please-manifest.json
release-please-config.json

Release-please configurations and workflow
[DEVOPS-534](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-534)
[DEVOPS-534]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: release-please configurations and workflow DEVOPS-534

---

.release-please-manifest.json
backend/kesaseteli/CHANGELOG.md

Merge develop to main (2023-06-02)

Merge develop to main (2023-06-02)

---

.github/workflows/release-please.yml

release-please set option target-branch that point to main

chore: release-please set target branch to main

---

.github/workflows/release-please.yml

release-please target-branch option

merge develop to main

---

backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/tests/test_security_with_anonymous_user.py
backend/kesaseteli/applications/tests/test_security_with_non_staff_user.py

refs YJDH-587 (fetch_employee_data backend endpoint)
refs YJDH-667 (audit logging)
refs YJDH-676 (frontend that will be using fetch_employee_data endpoint)
- [YJDH-587](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-587) (fetch_employee_data backend endpoint)
- [YJDH-667](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-667) (audit logging)
- [YJDH-676](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-676) (frontend that will be using fetch_employee_data endpoint)
[YJDH-587]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[YJDH-667]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …

feat(ks-backend): add summer voucher ID to fetch_employee_data I/O

---

frontend/kesaseteli/employer/public/locales/en/common.json
frontend/kesaseteli/employer/public/locales/fi/common.json
frontend/kesaseteli/employer/public/locales/sv/common.json
frontend/kesaseteli/employer/src/components/application/form/TextInput.tsx
frontend/kesaseteli/employer/src/components/application/steps/step2/accordions/EmploymentAccordion.tsx
frontend/kesaseteli/employer/src/hooks/application/useApplicationApi.ts
frontend/kesaseteli/employer/src/hooks/backend/useEmploymentQuery.ts
frontend/kesaseteli/shared/src/backend-api/backend-api.ts
frontend/shared/src/components/forms/inputs/TextInput.tsx
frontend/shared/src/components/forms/section/FormSection.sc.ts
frontend/shared/src/components/forms/section/FormSection.tsx
frontend/shared/src/types/employment.d.ts

Fetch employee data by Employee name and voucher serial number

YJDH-676: Fetch and autofill employee data

---

.github/workflows/release-please.yml
backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/tests/test_security_with_anonymous_user.py
backend/kesaseteli/applications/tests/test_security_with_non_staff_user.py
frontend/kesaseteli/employer/public/locales/en/common.json
frontend/kesaseteli/employer/public/locales/fi/common.json
frontend/kesaseteli/employer/public/locales/sv/common.json
frontend/kesaseteli/employer/src/components/application/form/TextInput.tsx
frontend/kesaseteli/employer/src/components/application/steps/step2/accordions/EmploymentAccordion.tsx
frontend/kesaseteli/employer/src/hooks/application/useApplicationApi.ts
frontend/kesaseteli/employer/src/hooks/backend/useEmploymentQuery.ts
frontend/kesaseteli/shared/src/backend-api/backend-api.ts
frontend/shared/src/components/forms/inputs/TextInput.tsx
frontend/shared/src/components/forms/section/FormSection.sc.ts
frontend/shared/src/components/forms/section/FormSection.tsx
frontend/shared/src/types/employment.d.ts

Merge develop to main (2023-06-07)

Merge develop to main (2023-06-07)

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json

Small text changes caused by new features.

HL-797 | Change confusing text when application is accepted or rejected

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/newApplication/companySearch/companyApi.ts
frontend/benefit/handler/src/components/newApplication/useApplicationForm.ts
frontend/benefit/handler/src/hooks/useSteps.ts

HL-852: Add authentication option

---

backend/benefit/applications/api/v1/application_batch_views.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/hooks/useRemoveAppFromBatch.ts

Removing one app from a batch no longer closes the whole batch listing. Also included a success toast if things go well!

HL-851 | Remove app from batch would result to batch closing animation

---

backend/benefit/applications/api/v1/views.py

Just add in a argument so that produced CSV does not have quotes anymore.

HL-854 cont. | Fix quoting issue when generating CSV

---

backend/benefit/applications/services/applications_csv_report.py
backend/benefit/applications/tests/test_applications_report.py

Fix some headers based on Janne's feedback.

Fix | Talpa CSV had wrong headers

---

frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/useHandlingApplicationActions.ts
frontend/benefit/shared/src/utils/common.ts

* Open sidebar with `openDrawer` param on application view
* Add link to the icon indicating there's new messages
* If there are new messages, add `openDrawer` param in the text and icon link

feat: use openDrawer param on application page to open sidebar

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json

HL-873 | Change text when adding applications to a batch

---

frontend/benefit/handler/src/components/newApplication/useApplicationForm.ts
frontend/benefit/handler/src/hooks/useApplicationQueryWithState.ts

Seems that the `formik`'s `initialValues` should be in local React state so that `enableReinitialize` options works correctly. Not pretty, but works.

HL-814: Fix form clearing bug when adding attachment

---

backend/benefit/helsinkibenefit/urls.py
backend/benefit/users/api/v1/views.py
frontend/benefit/applicant/src/components/header/useHeader.ts
frontend/benefit/shared/src/backend-api/backend-api.ts

On language change, update backend with selected language. To save devtime, I'm using fire and forget style here. I had some problems when using react-query hook.

HL-889 | Send user-selected value to backend on language change

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json

HL-913 | Toast had no translation for close button label

---

azure-pipelines/helsinkilisa-review.yml
azure-pipelines/kesaseteli-review.yml
backend/benefit/azure-pipelines-master.yml
backend/kesaseteli/azure-pipelines-kesaseteli-api-master.yml
backend/tet/azure-pipelines-devtest.yml
frontend/benefit/azure-pipelines-master.yml
frontend/benefit/handler/azure-pipelines-master.yml
frontend/kesaseteli/azure-pipelines-kesaseteli-ui-master.yml
frontend/kesaseteli/handler/azure-pipelines-devtest.yml
frontend/kesaseteli/youth/azure-pipelines-devtest.yml
frontend/tet/admin/azure-pipelines-devtest.yml
frontend/tet/youth/azure-pipelines-devtest.yml

Change pipelines trigger branch to main

chore: pipeline trigger branch to main DEVOPS-515

---

frontend/benefit/handler/src/components/applicationReview/employeeView/EmployeeActions/EmployeeActions.tsx
frontend/benefit/handler/src/components/applicationReview/paySubsidyView/PaySubsidyActions/PaysubsidyActions.tsx

Removed obsolete checkboxes "kohderyhmätarkistus" and "palkkatuki myönnetty vamman tai sairauden vuoksi".

HL-754: Remove obsolete checkboxes

---

backend/benefit/applications/tests/test_applications_report.py

remove unneeded pytest row

---

backend/benefit/companies/tests/test_api.py
backend/shared/shared/service_bus/service_bus_client.py

YTJ (service bus) integration failed when there was no company address.

HL-926: Handle case when there's no company address

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json

Forgot these from handler side.

HL-913 | Add toast's close notification text to handler side as well

---

frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryBenefitCalculatorView.tsx

Use the correct language for the salary benefit start date and end date datepicker components.

fix: salarybenefit datepicker lang

---

frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/validation.ts

Add validation for collective agreement.

fix: require collective agreement field

---

frontend/benefit/handler/src/components/newApplication/formContent/FormContent.tsx
frontend/benefit/handler/src/components/newApplication/utils/validation.ts

Apprenticeship question also needed with granted aged.

HL-984: ask apprenticeshipProgram also for GRANTED_AGED

---

backend/benefit/companies/services.py
backend/benefit/companies/tests/factories.py
frontend/benefit/handler/browser-tests/pages/new-application.testcafe.ts
frontend/benefit/handler/src/components/newApplication/companySearch/CompanySearch.tsx

fix: selector in handler browser tests (HL-997)

---

frontend/benefit/applicant/package.json
frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/DeMinimisAidForm.tsx
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/deMinimisAid.sc.ts
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/list/DeMinimisAidsList.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step1/ApplicationFormStep1.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step1/companyInfo/CompanyInfo.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step1/utils/validation.ts
frontend/benefit/applicant/src/hooks/useFormActions.tsx

Fixes various overlooked issues with deminimis and form save using pay subsidy percentage.

HL-1001, HL-1004 | Fix various issues regarding application step 1

---

frontend/benefit/applicant/package.json
frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/DeMinimisAidForm.tsx
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/deMinimisAid.sc.ts
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/list/DeMinimisAidsList.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step1/ApplicationFormStep1.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step1/companyInfo/CompanyInfo.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step1/utils/validation.ts
frontend/benefit/applicant/src/hooks/useFormActions.tsx

Reverts City-of-Helsinki/yjdh#2323

fix: revert, conditional commits for #2323

---

frontend/benefit/applicant/package.json
frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/DeMinimisAidForm.tsx
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/deMinimisAid.sc.ts
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/list/DeMinimisAidsList.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step1/ApplicationFormStep1.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step1/companyInfo/CompanyInfo.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step1/utils/validation.ts
frontend/benefit/applicant/src/hooks/useFormActions.tsx

Forgot conditional commit message from last PR 😢

fix: various bug fixes (HL-1001, HL-1004)

---

frontend/benefit/handler/src/components/newApplication/formContent/FormContent.tsx
frontend/benefit/handler/src/components/newApplication/review/employmentSection/EmploymentSection.tsx
frontend/benefit/handler/src/components/newApplication/utils/applicationForm.ts
frontend/benefit/shared/src/constants.ts

Fix attachment requirements logic. Some minor refactoring too.

fix: no need for paySubsidy attachment when no subsidies (HL-1011)

---

frontend/benefit/applicant/src/components/footer/Footer.sc.ts
frontend/benefit/applicant/src/components/pages/Login.sc.ts
frontend/benefit/applicant/src/pages/login.tsx

* Uniform button sizes
* Margin tweaks
* Font size tweaks
Press image to play ⏯️  animation:

feat: small tweaks to login styles (HL-940)

---

azure-pipelines/helsinkilisa-review.yml
frontend/benefit/applicant/browser-tests/pages/company.testcafe.ts
frontend/benefit/applicant/browser-tests/utils/fieldMaps.ts

Fix application tests. Still in debug mode to see what azure outputs.

fix: debug application tests

---

frontend/audit-ci.jsonc
frontend/benefit/handler/browser-tests/page-model/HandlerPageComponent.ts
frontend/benefit/handler/browser-tests/pages/single.testcafe.ts
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationReview/deminimisView/DeminimisView.tsx
frontend/benefit/handler/src/components/applicationReview/deminimisView/__tests__/DeminimisView.test.tsx

fix: sync translations (HL-1017)

---

release-please-config.json

build: release-please commit message skip azp

---

frontend/yarn.lock

Bump version to pass audit-ci.

fix: patch crypto-js dependency

---

frontend/benefit/applicant/src/components/applications/forms/application/step1/ApplicationFormStep1.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step2/ApplicationFormStep2.tsx

fix: lint files

---

frontend/benefit/applicant/package.json
frontend/benefit/handler/package.json
frontend/kesaseteli/handler/package.json
frontend/kesaseteli/shared/package.json
frontend/kesaseteli/youth/package.json
frontend/shared/package.json
frontend/yarn.lock

Update `finnish-ssn` package to both benefit handler and applicant frontends. This adds support for new format SSN's.

feat: update finnish-ssn (HL-662)

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationHeader/ApplicationHeader.sc.ts
frontend/benefit/handler/src/components/applicationHeader/ApplicationHeader.tsx
frontend/benefit/handler/src/components/applicationReview/ApplicationReview.tsx
frontend/benefit/handler/src/components/applicationReview/handledView/HandledView.sc.ts
frontend/benefit/handler/src/components/applicationReview/handledView/HandledView.tsx
frontend/benefit/handler/src/components/applicationReview/handledView/archivedView/ArchivedView.tsx
frontend/benefit/handler/src/components/statusLabel/StatusLabel.sc.ts
frontend/benefit/handler/src/components/statusLabel/StatusLabel.tsx
frontend/benefit/handler/src/components/statusLabel/utils.ts
frontend/benefit/shared/src/types/application.d.ts

feat: new archived view (HL-908)

---

backend/benefit/locale/fi/LC_MESSAGES/django.po

Fix: Some backend error message translated to finnish

---

frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/DoneModalContent/DoneModalContent.tsx
frontend/benefit/handler/src/components/applicationReview/applicationProcessingView/AplicationProcessingView.tsx

Fixes wrong amounts in handled view and handled confirmation modal.

fix: wrong calculator amounts in handling views (HL-1038)

---

frontend/yarn.lock

fix: downgrade kesaseteli ssn library as it's not compliant yet

---

frontend/audit-ci.jsonc

TET team should patch this sooner than later

chore!: whitelist sharp dependency to allow builds

---

frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/DoneModalContent/DoneModalContent.tsx
frontend/benefit/handler/src/components/applicationReview/handledView/HandledView.tsx

Did not show per month amounts if only one benefit period.

fix: per month amounts in handled view (HL-1046)

---

backend/benefit/requirements.in
backend/benefit/requirements.txt
backend/kesaseteli/requirements.in
backend/kesaseteli/requirements.txt
backend/tet/requirements.in
backend/tet/requirements.txt

refs YJDH-687
[YJDH-687](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-687)
[YJDH-687]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YJDH-687 | feat: upgrade django to 3.2.23 (i.e. latest 3.2.x) in all backends

---

frontend/tet/admin/src/components/editor/__tests__/Editor.test.tsx

Disable flaky test that prevents shared file changes. @tuomas777 might have to address this later.

chore: disable test that flakes on CI

---

backend/benefit/applications/api/v1/views.py
backend/benefit/applications/services/app_generated_files.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/common/permissions.py
backend/benefit/helsinkibenefit/urls.py
frontend/benefit/applicant/src/components/applications/forms/application/step5/ApplicationFormStep5.tsx

Various improvements requested by @rikuke

fix: application pdf summary improvements

---

frontend/yarn.lock

Dependabot does not upgrade yarn.lock 😢

chore: bump yarn.lock for sharp 0.33.0

---

backend/benefit/applications/api/v1/views.py
backend/benefit/applications/services/generate_application_summary.py
backend/benefit/applications/templates/application.html
backend/benefit/applications/templates/footer.html
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/sv/LC_MESSAGES/django.po
frontend/benefit/applicant/src/components/applications/forms/application/step5/ApplicationFormStep5.tsx

Small template fixes for PDF summary reported by @JanneJuhola 
FI:
[download (2).pdf](https://github.com/City-of-Helsinki/yjdh/files/13543760/download.2.pdf)
SV:
[download (1).pdf](https://github.com/City-of-Helsinki/yjdh/files/13543761/download.1.pdf)
EN:
[download.pdf](https://github.com/City-of-Helsinki/yjdh/files/13543762/download.pdf)

fix: order of lines; € per month; 55yr pay subsidy title if needed

---

frontend/benefit/handler/src/components/newApplication/formContent/companySection/CompanySection.tsx
frontend/benefit/handler/src/components/newApplication/utils/validation.ts
frontend/shared/src/utils/string.utils.ts

fix: handler application validations (HL-991)

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json

Add helper text for holiday pay input.

chore: change texts on holiday pay (HL-1084)

---

backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/additional-information-required_en.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/additional-information-required_fi.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/additional-information-required_sv.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/draft-notice_en.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/draft-notice_fi.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/draft-notice_sv.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/received-message_en.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/received-message_fi.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/received-message_sv.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/txt/draft-notice_en.txt
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/txt/draft-notice_fi.txt
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/txt/draft-notice_sv.txt
frontend/benefit/common/src/emails/i18n/en.json
frontend/benefit/common/src/emails/i18n/fi.json
frontend/benefit/common/src/emails/i18n/sv.json

fix: some urls were missing from email templates

---

frontend/benefit/applicant/src/hooks/useAnalytics.ts

fix: don't send application id to askem (HL-1089)

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/pageContent/PageContent.tsx
frontend/benefit/applicant/src/components/applications/pageContent/usePageContent.ts
frontend/benefit/applicant/src/components/cookieConsent/CookieConsent.tsx
frontend/benefit/applicant/src/components/cookieConsent/NoCookieConsentsNotification.tsx
frontend/benefit/applicant/src/components/notificationView/NotificationView.tsx
frontend/benefit/applicant/src/utils/cookie.ts
frontend/benefit/shared/src/constants.ts

Based on https://github.com/City-of-Helsinki/yjdh/pull/2616 so that should be merged first.
Allow modifying cookie settings in submitted view.

feat: modify cookies settings (HL-1078)

---

compose.benefit.yml
compose.employer.yml
compose.handler.yml
compose.tet-admin.yml
compose.tet-youth.yml
compose.tet.yml
frontend/Dockerfile
frontend/Dockerfile-localdevelopment

Experiment with docker file to speed up builds. No merging yet!

chore: remove development stage from docker file

---

backend/benefit/applications/api/v1/serializers/batch.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/batchProcessing/BatchApplicationList.tsx
frontend/benefit/handler/src/components/batchProcessing/useBatches.ts
frontend/benefit/shared/src/types/application.d.ts

* Add total amount of benefits in all instances of batch's application tables
* Remove duplicate handledAt

feat: show benefit amount in batch app listing (HL-1053)

---

frontend/benefit/applicant/package.json
frontend/benefit/handler/package.json
frontend/yarn.lock

Bump `axios` to newest version in `benefit`.

chore: upgrade to latest axios in benefit

---

backend/benefit/requirements.in
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/common/tests/test_utils.py
backend/kesaseteli/common/tests/utils.py
backend/kesaseteli/requirements.in
backend/kesaseteli/requirements.txt
backend/shared/shared/common/tests/test_utils.py
backend/shared/shared/common/tests/utils.py
backend/shared/shared/common/utils.py
backend/tet/requirements.in
backend/tet/requirements.txt
frontend/benefit/applicant/package.json
frontend/benefit/handler/package.json
frontend/kesaseteli/handler/package.json
frontend/kesaseteli/shared/package.json
frontend/kesaseteli/youth/package.json
frontend/shared/package.json
frontend/shared/src/__tests__/constants.test.ts
frontend/shared/src/constants.ts
frontend/shared/src/utils/__tests__/mask-gdpr-data.test.ts
frontend/shared/src/utils/mask-gdpr-data.ts
frontend/yarn.lock

refs YJDH-686
[YJDH-686](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-686)
[YJDH-686]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YJDH-686 | fix: upgrade all Finnish SSN related code to support new format

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_ahjo_payload.py

Update AHJO open case payload with the changes to the latest version (20-12-2023).
- Remove reference from attachment dicts
- Add draftsman role information
- Add  "MannerOfReceipt": "sähköinen asiointi" 
```
{
"Title": "Avustuksen myöntäminen, työllisyyspalvelut, työnantajan Helsinki-lisä vuonna 20xx, työnantaja x",
"Acquired": "2023-03-15T14:00:00+02:00",
"ClassificationCode": "02 05 01 00",
"ClassificationTitle": "Kunnan myöntämät avustukset",
"Language": "fi",
"PublicityClass": "Julkinen",
"InternalTitle": "Avustuksen myöntäminen, työllisyyspalvelut, työnantajan Helsinki-lisä vuonna 20xx, työnantaja x",
"Subjects": [
{
"Subject": "Helsinki-lisät",
"Scheme": "hki-yhpa"
},
{
"Subject": "kunnan myöntämät avustukset",
"Scheme": "hki-yhpa"
},
{
"Subject": "työnantajat",
"Scheme": …
```

feat: update open case payload to latest version

---

backend/benefit/applications/api/v1/application_batch_views.py
backend/benefit/applications/tests/test_application_batch_api.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/batchProcessing/BatchApplicationList.tsx
frontend/benefit/handler/src/components/batchProcessing/BatchProposals.tsx
frontend/benefit/handler/src/components/batchProcessing/batchFooter/BatchFooterCompletion.tsx
frontend/benefit/handler/src/components/batchProcessing/useBatchActionsInspected.ts
frontend/benefit/handler/src/components/batchProcessing/useBatches.ts
frontend/benefit/handler/src/components/table/TableExtras.sc.ts
frontend/benefit/handler/src/hooks/useBatchInspected.ts
frontend/benefit/handler/src/hooks/useBatchQuery.ts
frontend/benefit/handler/src/hooks/useBatchStatus.ts
frontend/benefit/handler/src/pages/batches/index.tsx
frontend/benefit/handler/src/types/applicationList.d.ts
frontend/benefit/handler/src/types/batchList.d.ts

Bunch of fixes that was requested by design and test personnel.

fix: an array of fixes for HL-1053

---

backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/common/tests/test_factories.py
frontend/kesaseteli/employer/public/locales/en/common.json
frontend/kesaseteli/employer/public/locales/fi/common.json
frontend/kesaseteli/employer/public/locales/sv/common.json
frontend/kesaseteli/youth/browser-tests/youth-application.testcafe.ts

also:
- remove dead code & inapplicable test cases after target group update
refs YJDH-670
[YJDH-670](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-670)
[YJDH-670]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YJDH-670 | feat(kesaseteli): update target groups for year 2024, update tests

---

frontend/kesaseteli/handler/src/__tests__/index.test.tsx
frontend/kesaseteli/handler/src/utils/map-vtj-data.ts
frontend/kesaseteli/shared/src/__tests__/utils/fake-objects.ts

refs YJDH-670
[YJDH-670](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-670)
[YJDH-670]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YJDH-670 | feat(kesaseteli): update year 2024's target groups' ages in frontend

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_ahjo_payload.py

The open case JSON payload had the MannerOfReceipt information in the wrong place, this PR puts it into the record dict if the record is the application (hakemus) as in the example payload below
```
{
"Title": "Avustuksen myöntäminen, työllisyyspalvelut, työnantajan Helsinki-lisä vuonna 20xx, työnantaja x",
"Acquired": "2023-03-15T14:00:00+02:00",
"ClassificationCode": "02 05 01 00",
"ClassificationTitle": "Kunnan myöntämät avustukset",
"Language": "fi",
"PublicityClass": "Julkinen",
"InternalTitle": "Avustuksen myöntäminen, työllisyyspalvelut, työnantajan Helsinki-lisä vuonna 20xx, työnantaja x",
"Subjects": [
{
"Subject": "Helsinki-lisät",
"Scheme": "hki-yhpa"
},
{
"Subject": "kunnan myöntämät avustukset",
"Scheme": "hki-yhpa"
},
{
"Subject": "työnantajat",
"Scheme": "hki-yhpa"
},
{ …
```

fix: move MannerOfReceipt into the record dict

---

README.md
backend/README.md
backend/shared/shared/audit_log/README.md
backend/shared/shared/helsinki_profile/hp_client.py
backend/shared/shared/oidc/views/eauth_views.py
frontend/README.md
frontend/benefit/README.md
frontend/kesaseteli/README.md

**Affects the whole YJDH monorepo**
`develop` branch should not be used for anything anymore, so it is a
good idea to remove references to `develop` branch completely

chore: update develop branch to main branch in README.md & docs

---

backend/kesaseteli/applications/templates/application_excel_download.html
backend/kesaseteli/applications/views.py

Tests are missing, product owner demanded this feature today.

feat(kesaseteli): add annual Excel download for previous year

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/conftest.py

Remove the year from the open case message title and add company business ID and application number.

feat: change open case message title

---

backend/shared/shared/azure_adfs/tests/test_adfs_login.py

refs YJDH-494
[YJDH-494](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-494)
[YJDH-494]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YJDH-494 | fix(adfs): make ADFS login tests work without real internet connection

---

backend/benefit/applications/api/v1/ahjo_integration_views.py
backend/benefit/applications/services/ahjo_integration.py

Fix headers not being created and log more info when ahjo downloads an attachment.

Ahjo decision debug and fix

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json

fix: remove text about adding file, not yet supported

---

backend/benefit/applications/api/v1/ahjo_decision_views.py
backend/benefit/applications/api/v1/serializers/decision_text.py
backend/benefit/applications/services/ahjo_integration.py
backend/benefit/applications/tests/test_ahjo_decisions.py
backend/benefit/helsinkibenefit/urls.py

Adds  api endpoints for submitting a decision text and for updating a decision text.

Hl 1144 decision api

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/conftest.py

"ExterOnal" should be "External"

fix: typo in Type

---

backend/benefit/applications/services/ahjo_integration.py
backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/templates/secret_decision.xml
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_ahjo_integration.py
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/sv/LC_MESSAGES/django.po

Add localization support to the secret AHJO XML attachment and to the open case JSON message.

feat: add localization for ahjo messages

---

frontend/package.json
frontend/yarn.lock

TestCafe started acting up on localhost. Upgrading solved the issue for me. Figured might as well bump version.

chore(frontend): update testcafe library

---

backend/benefit/applications/templates/secret_decision.xml
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/sv/LC_MESSAGES/django.po

[HL-1256 ](https://helsinkisolutionoffice.atlassian.net/browse/HL-1256?atlOrigin=eyJpIjoiZTlhZDViNDQyYTY1NDg0Zjk5ZTU1NDdhOThiNzhiNzciLCJwIjoiaiJ9) Fix formatting issues (see screenshot) in the secret decision XM

fix: secret decision xml formatting

---

frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.tsx
frontend/benefit/applicant/src/components/applications/applicationList/useApplicationList.ts
frontend/benefit/applicant/src/components/applications/pageContent/PageContent.tsx
frontend/benefit/applicant/src/pages/_app.tsx
frontend/benefit/applicant/src/pages/index.tsx

Invalidate applications cache on frontpage to prevent wrong state being loaded.

fix: applicant - invalidate cache to prevent wrong application mode (HL-1183)

---

frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/validation.ts

Change months like in backend.

fix: validation minimum for start date should be 4 months earlier, not 6

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/deMinimisAid.sc.ts

fix: added missing localizations and better de minimis text (Hl-1236)

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/test_ahjo_payload.py
backend/benefit/applications/tests/test_applications_api.py

Lowercase the "L" letter in Hakemuksen Liite Attribute.

fix: lowercase L in attachment title

---

backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/api/v1/serializers/application_alteration.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/locale/en/LC_MESSAGES/django.po
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/sv/LC_MESSAGES/django.po
frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/Applications.sc.ts
frontend/benefit/applicant/src/components/applications/alteration/AlterationAccordionItem.sc.ts
frontend/benefit/applicant/src/components/applications/alteration/AlterationAccordionItem.tsx
frontend/benefit/applicant/src/components/applications/alteration/AlterationDeleteModal.tsx
frontend/benefit/applicant/src/components/applications/alteration/AlterationPage.sc.ts
frontend/benefit/applicant/src/components/applications/alteration/AlterationPage.tsx
frontend/benefit/applicant/src/components/applications/forms/application/alteration/AlterationForm.sc.ts
frontend/benefit/applicant/src/components/applications/forms/application/alteration/AlterationForm.tsx
frontend/benefit/applicant/src/components/applications/pageContent/DecisionSummary.tsx
frontend/benefit/applicant/src/components/applications/pageContent/PageContent.sc.ts
frontend/benefit/applicant/src/components/applications/pageContent/usePageContent.ts
frontend/benefit/applicant/src/hooks/useDeleteApplicationAlterationQuery.ts
frontend/shared/src/components/forms/section/FormSection.sc.ts

In this PR, the DELETE REST endpoint is restricted for the use of the applicant only. It will be enabled for handlers later once the handler side progresses to that point.

feat: implement the existing alteration list and alteration deletion for the applicant (HL-1154)

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/applicationList/ApplicationList.tsx
frontend/benefit/applicant/src/components/applications/applicationList/ExpandableApplicationList.tsx
frontend/benefit/applicant/src/components/applications/applicationList/PaginatedApplicationList.tsx
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListContents.tsx
frontend/benefit/applicant/src/pages/index.tsx

Adds a reminder box about reporting changes to employment. Only shown with the feature flag on.
Swedish and final English translations are pending.

feat: add reminder about alterations to applicant main page (HL-1100)

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/components/applicationList/useApplicationListData.ts

fix(handler): add missing column "modifiedAt" for draft list (HL-914)

---

frontend/kesaseteli/youth/src/__tests__/index.test.tsx

Circumvent a real issue https://github.com/City-of-Helsinki/yjdh/issues/1998 by banging test's head into the wall.

test: retry certain ks test to get a flaky test through with better probability

---

frontend/benefit/handler/browser-tests/pages/4-make-decision.testcafe.ts
frontend/kesaseteli/youth/src/__tests__/additional_info.test.tsx

fix: try fixing failing tests

---

frontend/audit-ci.jsonc

chore: disallow a few packages

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryBenefitCalculatorView.tsx
frontend/benefit/handler/src/constants.ts
frontend/benefit/handler/src/hooks/useCalculatorData.ts
frontend/benefit/shared/src/constants.ts
frontend/shared/src/utils/date.utils.ts

Replace all form field values with ... nothing. Asks the user before doing anything.

feat: clear all calculation form fields from "clear" button

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationReview/ApplicationReview.sc.ts
frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/HandlingApplicationActionsAhjo.tsx
frontend/benefit/handler/src/components/applicationReview/handlingView/HandlingStep3.tsx
frontend/benefit/handler/src/constants.ts
frontend/benefit/handler/src/pages/index.tsx
frontend/shared/src/utils/dom.utils.ts

* Add ahjo id to decison draft preview; if case is opened
* Add missing (kk) month unit to table column header
* Use bold instead of semibold for table footer row (better contrast on Windows)
* Focus and scroll to failing part in decision drafting views
* Selecting a tab in index page results to query parameter update, keeping track of the tab selected (this is an OLD request)
* Return to the index page's handling tab from "save and close" and "close" buttons
* "Save and close" button needs a valid calculation

feat: minor additions and fixes to decision drafting (HL-1274)

---

frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/validation.ts
frontend/benefit/applicant/src/constants.ts
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationForm/formContent/FormContent.tsx
frontend/benefit/handler/src/components/applicationForm/formContent/useFormContent.ts
frontend/benefit/handler/src/components/applicationForm/utils/applicationForm.ts
frontend/benefit/handler/src/components/applicationForm/utils/validation.ts
frontend/benefit/handler/src/constants.ts

* Refactor and change some constants regarding start date validation
* Add notification on handler application edit when changing start / end date too far from recommended range
* Fix a nasty bug that crashed the whole app

fix: resolve issues with start date on handler's side (HL-1270)

---

backend/benefit/applications/management/commands/check_drafts_to_delete.py

Exhaustive printing in `check_drafts_to_delete.py`:

fix: ignore paper apps, correct date to email template

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json

fix:loc key added for application.handling & .cancelled (HL-1288)

---

backend/benefit/applications/services/ahjo_xml_builder.py
backend/benefit/applications/tests/test_ahjo_xml_builder.py

Fix the decimal in the total amout row of the XML attachment.

fix: total amount as int

---

frontend/kesaseteli/employer/src/__tests__/application.test.tsx
frontend/kesaseteli/youth/src/__tests__/additional_info.test.tsx
frontend/kesaseteli/youth/src/__tests__/index.test.tsx
frontend/kesaseteli/youth/src/__tests__/utils/components/get-additional-info-page-api.ts
frontend/shared/src/__tests__/utils/slow-jest-timeout.ts

TL;DR:
- **Increasing timeouts** in favor of retries (Retries were added in PR #2940 by @sirtawast and now removed in this PR)
remove jest.retryTimes(5) as they should not be needed anymore
with the increased timeouts, if they still fail then it's good to get
the information about them failing rather than thinking that they're
not failing
refs YJDH-690, YJDH-699
[YJDH-690](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-690) "Some kesäseteli tests fail randomly on employer and youth"
[YJDH-699](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-699) "Increase timeouts for the kesäseteli tests that fail randomly on employer and youth"
Locally tested using multiple (up to 9) simultaneous runs of tests in a loop,
i.e. I opened up to 9 terminals and ran
- `cd …

YJDH-699 | test(kesaseteli): add longer timeouts to tests that seem to need them

---

backend/benefit/applications/api/v1/serializers/application.py

Fix small style error from last Friday's hotfix.

fix: small code style fix

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/test_ahjo_payload.py

Modify the Ahjo record title so, that if the record is for an application and it is a update request, the word "täydennys" is added to the record title.

feat: adjust title of ahjo application record

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/alteration/AlterationPage.tsx
frontend/benefit/applicant/src/components/applications/alteration/utils/validation.ts
frontend/benefit/applicant/src/components/applications/forms/application/alteration/AlterationForm.tsx
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/alterationHandling/AlterationHandling.sc.ts
frontend/benefit/handler/src/components/alterationHandling/AlterationHandling.tsx
frontend/benefit/handler/src/components/alterationHandling/AlterationHandlingForm.tsx
frontend/benefit/handler/src/components/alterationHandling/AlterationHandlingSection.tsx
frontend/benefit/handler/src/components/alterationHandling/useAlterationHandling.ts
frontend/benefit/handler/src/components/alterationHandling/useAlterationHandlingForm.ts
frontend/benefit/handler/src/components/alterationHandling/utils/validation.ts
frontend/benefit/handler/src/components/alterationList/AlterationList.tsx
frontend/benefit/handler/src/components/applicationReview/handlingView/AlterationAccordionItem.tsx
frontend/benefit/handler/src/constants.ts
frontend/benefit/handler/src/pages/alterations/handle.tsx
frontend/benefit/shared/src/types/application.d.ts

Proper calculation and Talpa CSV generation will be implemented in their own respective branches.

feat: add alteration handling page with base components (HL-1250)

---

backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/tests/test_applications_api.py

Since the prefetch was missing in a real usage scenario, the applicant UI failed to find any alterations and also didn't return even an empty array, breaking views that expected one to be present.

fix: prefetch alterations regardless of auth mock flag

---

backend/benefit/applications/jobs/hourly/hourly_ahjo_job.py

Schedule the decision details request to run hourly if the automation is on.

feat: run ahjo decision details requests hourly

---

.env.benefit-backend.example
backend/README.md
backend/benefit/README.md
backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/helsinkibenefit/settings.py
backend/benefit/requirements.in
backend/benefit/requirements.txt
backend/shared/shared/oidc/tests/conftest.py
backend/shared/shared/oidc/tests/test_auth_backend.py

Update Django to the next LTS version 4.2.

chore: update Django to 4.2 LTS

---

frontend/benefit/applicant/src/components/applications/alteration/AlterationDeleteModal.tsx
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/alterationHandling/AlterationCalculator.tsx
frontend/benefit/handler/src/components/alterationHandling/AlterationHandling.tsx
frontend/benefit/handler/src/components/alterationHandling/AlterationHandlingConfirmationModal.tsx
frontend/benefit/handler/src/components/alterationHandling/AlterationHandlingForm.tsx
frontend/benefit/handler/src/components/alterationHandling/AlterationSummary.tsx
frontend/benefit/handler/src/components/alterationHandling/useAlterationHandlingForm.ts
frontend/benefit/handler/src/components/alterationHandling/utils/validation.ts
frontend/benefit/handler/src/components/applicationReview/handlingView/AlterationCancelModal.tsx
frontend/benefit/handler/src/components/applicationReview/handlingView/AlterationDeleteModal.tsx
frontend/benefit/handler/src/constants.ts
frontend/benefit/handler/src/types/application.d.ts
frontend/benefit/shared/src/constants.ts

Besides implementing the additional modal functionality, also fixes the minor text issue reported in HL-1328.

feat: confirmation modal and additional state checks for alteration handler (HL-1251, HL-1252, HL-1328)

---

backend/benefit/applications/tests/test_ahjo_integration.py

Fix overwritten applications_for_open_case variable which resulted in a rather pointless test assertion.

fix: overwritten test variable

---

backend/benefit/applications/jobs/quarter_hourly/quarter_hourly_ahjo_job.py
backend/benefit/applications/management/commands/send_ahjo_requests.py
backend/benefit/applications/services/ahjo_integration.py
backend/benefit/applications/tests/test_application_tasks.py

Schedules the applications which have `scheduled_for_deletion ` as their latest ahjo_status, for deletion/cancellation in Ahjo.

feat: schedule Ahjo case delete

---

frontend/benefit/applicant/src/components/header/Header.tsx
frontend/benefit/applicant/src/components/header/useHeader.ts

* Fix key issue warn
* Add messenger button for `cancelled` applications
* User for `cancelled` application will not be able to write new messages

fix: possibility to open messenger for cancelled application (hl-1292 cont.)

---

backend/benefit/applications/management/commands/send_ahjo_requests.py

Fix for [HL-1357](https://helsinkisolutionoffice.atlassian.net/browse/HL-1357?atlOrigin=eyJpIjoiNGI1NjZjOWFmOWU4NGU2ODllZmI0MzVlMzBkZGU4NWQiLCJwIjoiaiJ9)
Sentry issue:
https://sentry.test.hel.ninja/organizations/city-of-helsinki/issues/12930/events/5fcb1ae01e6a4823b501319dbfa95b78/
[HL-1357]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: missing parameter for delete request query

---

backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/api/v1/search_views.py
backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/applications/management/commands/import_archival_applications.py
backend/benefit/applications/tests/test_application_search.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationsArchive/ApplicationArchiveList.tsx
frontend/benefit/handler/src/components/applicationsArchive/ApplicationsArchive.sc.ts
frontend/benefit/handler/src/components/applicationsArchive/ApplicationsArchive.tsx
frontend/benefit/handler/src/components/applicationsArchive/useApplicationsArchive.ts
frontend/benefit/handler/src/hooks/useSearchApplicationQuery.ts
frontend/benefit/handler/src/types/search.d.ts

- Add filtering for decision date
- Add filtering for subsidy in effect
- Add tests for these
- Minor changes to spreadsheet import
- Address @EmiliaMakelaVincit findings on hl-1310 #3056

feat: add filters to search & improve spreadsheet import (hl-1322)

---

frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/components/applicationList/useApplicationListData.ts
frontend/benefit/handler/src/components/batchProcessing/useApplicationsHandled.ts
frontend/benefit/shared/src/types/application.d.ts

Filter out applications that should not be shown if old ahjo batch process is used.

fix: remove list items that are handled with new ahjo mode (hl-1373 cont.)

---

backend/shared/shared/audit_log/audit_logging.py
backend/shared/shared/common/utils.py

refs YJDH-696 (preparations)
[YJDH-696](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-696)
[YJDH-696]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: make shared backend code compatible with black 24.4.2

---

backend/benefit/applications/api/v1/search_views.py
backend/benefit/applications/management/commands/import_archival_applications.py
backend/benefit/applications/tests/test_application_search.py
backend/benefit/applications/tests/test_command_import_archival_applications.py
frontend/benefit/handler/src/components/applicationsArchive/ApplicationArchiveList.tsx
frontend/benefit/handler/src/components/applicationsArchive/ApplicationsArchive.tsx

Some improvements on application search. Lots of changes, reviewing one commit at a time makes sense here.

chore: series of improvements for application search

---

backend/benefit/docker-entrypoint.sh
backend/docker/benefit-ubi-arm.Dockerfile
backend/docker/finnish_postgres.Dockerfile
backend/docker/ubi/centos9-aarch.repo
backend/docker/ubi/centos9.repo
compose.benefit-backend.yml
compose.benefit.yml
frontend/Dockerfile-localdevelopment

Use ubi images instead of helsinkitest.

chore: use ubi image as backend platform (hl-1394)

---

frontend/benefit/handler/src/components/applicationForm/formContent/FormContent.tsx

Display misc. attachment upload on handler's edit view for all application origins.

feat: add 'other attachments' file upload dialog to all applications

---

frontend/benefit/applicant/package.json
frontend/benefit/handler/package.json
frontend/kesaseteli/employer/package.json
frontend/kesaseteli/handler/package.json
frontend/kesaseteli/youth/package.json
frontend/package.json
frontend/tet/admin/package.json
frontend/tet/youth/package.json
frontend/yarn.lock

chore: upgrade testcafe version because of chrome > 125 uploads fail

---

frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryBenefitManualCalculatorView.tsx
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryCalculatorResults/SalaryCalculatorResults.tsx
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/useSalaryBenefitCalculatorData.ts
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/utils/validation.ts

* Make fields required
* Validate fields
* Fix bug that prevented manual calculation from showing if normal calculation was done first

fix: validation and fixes to manual calculation (hl-1107)

---

backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/management/commands/seed.py
backend/benefit/applications/services/application_alteration_csv_report.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/factories.py
backend/benefit/applications/tests/test_applications_report.py
backend/benefit/companies/models.py
frontend/benefit/handler/src/components/alterationHandling/AlterationCsvButton.tsx
frontend/benefit/handler/src/components/alterationHandling/AlterationHandlingForm.tsx
frontend/benefit/handler/src/components/alterationHandling/useAlterationHandlingForm.ts
frontend/benefit/handler/src/hooks/useUpdateApplicationAlterationWithCsvQuery.ts
frontend/benefit/handler/src/types/application.d.ts
frontend/benefit/shared/src/backend-api/backend-api.ts
frontend/shared/src/utils/file.utils.ts

Hl 887 new csv 2

---

backend/benefit/applications/management/commands/send_ahjo_requests.py

Include applications that have been cancelled, to the automated AHJO delete request.

feat: add cancelled applications to delete request

---

frontend/benefit/handler/src/components/applicationReview/calculationTable/useCalculationTable.ts

Add manual calculation to both:
* when preparing ahjo proposal (hl-1408)
* when viewing accepted application (payment alternations section) (hl-1415)

chore: add manual calculation to new ahjo ui (hl-1408 & hl-1415)

---

backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/tests/test_applications_api.py
frontend/benefit/handler/src/components/header/Header.sc.ts
frontend/benefit/handler/src/components/header/Header.tsx
frontend/benefit/handler/src/components/header/HeaderNotifier.tsx
frontend/benefit/handler/src/hooks/useApplicationsWithMessagesQuery.ts
frontend/benefit/handler/src/hooks/useMarkLastMessageUnreadQuery.ts
frontend/benefit/handler/src/hooks/useMarkMessagesReadQuery.ts
frontend/benefit/shared/src/backend-api/backend-api.ts
frontend/shared/src/components/header/Header.tsx
frontend/shared/src/styles/mediaQueries.ts

Implement new notifier for unread messages.

feat: add unread messages notifier into header (hl-1410)

---

backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/services/application_alteration_csv_report.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_applications_report.py
backend/benefit/helsinkibenefit/settings.py

[HL-1419](https://helsinkisolutionoffice.atlassian.net/browse/HL-1419)
Use the email helsinkilisa@hel.fi defined in settings.py as the email, and the currently logged in user as the handler, in alteration csv report.
[HL-1419]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: logged in user to alteration csv

---

frontend/benefit/handler/src/components/applicationReview/handlingView/HandlingStep1.tsx
frontend/benefit/handler/src/components/applicationsArchive/useApplicationsArchive.ts

Remove a few sections mentioned in the ticket.
* Archive wont show calculation end date for cancelled or rejected application
* Single application view won't show area for decision proposal unless it's status is accepted

fix(handler): remove section and end date when application is not accepted

---

frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/HandlingApplicationActions.tsx
frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/HandlingApplicationActionsAhjo.tsx
frontend/benefit/handler/src/components/sidebar/Sidebar.tsx

Allow handler to write new messages at any time if sidebar is visible.

fix(handler): remove unnecessary restrictions for new messages or notes

---

backend/benefit/applications/api/v1/ahjo_integration_views.py
backend/benefit/applications/api/v1/application_batch_views.py
backend/benefit/applications/api/v1/talpa_integration_views.py
backend/benefit/applications/tests/test_ahjo_integration.py
backend/benefit/applications/tests/test_application_batch_api.py
backend/benefit/applications/tests/test_talpa_integration.py

[HL 1440](https://helsinkisolutionoffice.atlassian.net/browse/HL-1440?atlOrigin=eyJpIjoiNDc5Yjg4NzYwOWJmNDE0Mzk4OWY4MDM5MTkyNTUwZWMiLCJwIjoiaiJ9)
Update application.archived as True after it has been cancelled in ahjo or processed in Talpa.

feat: HL 1440 set archived status for applications

---

frontend/audit-ci.jsonc
frontend/benefit/applicant/next-env.d.ts
frontend/benefit/applicant/package.json
frontend/benefit/handler/next-env.d.ts
frontend/benefit/handler/package.json
frontend/benefit/shared/package.json
frontend/kesaseteli/employer/package.json
frontend/kesaseteli/handler/package.json
frontend/kesaseteli/youth/package.json
frontend/package.json
frontend/shared/package.json
frontend/tet/admin/package.json
frontend/tet/shared/package.json
frontend/tet/youth/package.json
frontend/yarn.lock

Resolves https://github.com/advisories/GHSA-gp8f-8m3g-qvj9

fix: bump nextjs version

---

backend/benefit/applications/api/v1/power_bi_integration_views.py
backend/benefit/applications/services/applications_power_bi_csv_report.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_applications_report.py
backend/benefit/applications/tests/test_power_bi_integration.py

Adds the columns needed for the PowerBI report.
[power_bi_data_20240919_082825.csv](https://github.com/user-attachments/files/17055992/power_bi_data_20240919_082825.csv)

Hl 1445 add fields

---

backend/kesaseteli/kesaseteli/settings.py

This is a dummy README.md change commit to trigger Kesäseteli's backend
release. The original code changes is actually in commit
5b7aab6b5b680eddd2bbd56111673cb97a71eb6e
refs YJDH-711

YJDH-711 | fix: update Suomi.fi IDP test/production metadata

---

backend/benefit/applications/api/v1/application_batch_views.py
backend/benefit/applications/api/v1/talpa_integration_views.py
backend/benefit/applications/tests/test_talpa_integration.py
backend/benefit/helsinkibenefit/settings.py

[HL-1476](https://helsinkisolutionoffice.atlassian.net/browse/HL-1476)
Refactor TALPA callback code so it handles failed and successful applications despite of the status message.
Add more logging for the updates after talpa csv download and callback
Add TALPA_CALLBACK_ENABLED env variable for turning the callback functionality on and off and doing the same for the old update after download.
[HL-1476]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: HL 1476 talpa improvements

---

backend/benefit/applications/templates/application.html
backend/benefit/applications/templates/footer.html
backend/benefit/applications/templates/style.html
frontend/audit-ci.jsonc

Remove some of the flex tricks and replace it with `position: absolute`.

fix: broken html to pdf layout in application print

---

backend/benefit/applications/services/change_history.py
backend/benefit/applications/tests/test_applications_api.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/sidebar/ChangeSet.tsx

* Add attachment history change sets
* Clean up code for edit history change sets
* Minor tweaks to how change sets are viewed for handler

feat: include attachment additions to change set (hl-1209)

---

frontend/benefit/handler/src/components/applicationReview/handlingView/AlterationAccordionItem.tsx

[HL-1490](https://helsinkisolutionoffice.atlassian.net/browse/HL-1490?atlOrigin=eyJpIjoiNmU4NGFiNTE1YTRhNDA4NTljZDgxZDc3ZTNhMGI0NWEiLCJwIjoiaiJ9)
[HL-1490]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remove decimals from alteration sum

---

frontend/benefit/applicant/package.json
frontend/benefit/handler/browser-tests/pages/7-handle-alteration.testcafe.ts
frontend/benefit/handler/package.json
frontend/kesaseteli/employer/package.json
frontend/kesaseteli/handler/package.json
frontend/kesaseteli/youth/package.json
frontend/tet/admin/package.json
frontend/tet/youth/package.json

Testcafe broken again ... 😮‍💨 
https://github.com/DevExpress/testcafe/issues/8286

fix: chrome v130 crashes on startup

---

frontend/audit-ci.jsonc
frontend/shared/package.json
frontend/yarn.lock

chore: bump express version

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/test_ahjo_payload.py

[HL-1508](https://helsinkisolutionoffice.atlassian.net/browse/HL-1508)
The application's modified_at date is the date that needs to be in the ahjo JSON title when the request is an update or adding of new record request.
Also the title generating function was a bit of an if/else mess, it was refactored to a class based solution with robust comments 😬 and tests.
[HL-1508]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: modified_at date for ahjo update request

---

frontend/benefit/handler/src/components/applicationList/HandlerIndex.tsx
frontend/benefit/handler/src/components/applicationReview/handlingView/DecisionCalculationAccordion.tsx

Hide 2nd instalment payments if application is pending Ahjo decision not in payment yet.

fix: show applications with 2nd instalments only they are in payment

---

frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/components/applicationReview/applicationProcessingView/ApplicationProcessingView.tsx
frontend/benefit/handler/src/components/applicationReview/handlingView/HandlingStep2.tsx

* fix issue with incorrect data format served by the backend
* fix preselection of radio button using save & close technique
* fix crashing bug when decision maker is null

fix: issues persist with chosing decision maker role (hl-1530 cont.)

---

backend/benefit/applications/tests/test_talpa_integration.py
backend/benefit/calculator/rules.py
backend/benefit/calculator/tests/test_calculator_api.py

[HL-1555](https://helsinkisolutionoffice.atlassian.net/browse/HL-1426)
The InstalmentStatus for the 1st instalment is now always accepted, so it can be paid in the next Talpa run.
[HL-1555]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: 1st instalment status accepted when created

---

.env.kesaseteli.example

refs YJDH-716 (so that following README would work)

chore: add local dev CSRF_TRUSTED_ORIGINS to .env.kesaseteli.example

---

frontend/kesaseteli/employer/package.json
frontend/kesaseteli/handler/package.json
frontend/kesaseteli/youth/package.json

feat: make "yarn dev" crossplatform in kesaseteli handler/employer/youth

---

frontend/benefit/handler/src/components/applicationReview/ApplicationReview.tsx

Show sidebar toggle button even if application is cancelled.

fix: make sidebar opening/closing possible even if application is cancelled (hl-1384)

---

backend/benefit/applications/jobs/daily/daily_application_jobs.py
backend/benefit/applications/management/commands/check_and_notify_ending_benefits.py
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/benefit-period-end-notice_en.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/benefit-period-end-notice_fi.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/benefit-period-end-notice_sv.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/txt/benefit-period-end-notice_en.txt
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/txt/benefit-period-end-notice_fi.txt
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/txt/benefit-period-end-notice_sv.txt
backend/benefit/locale/en/LC_MESSAGES/django.po
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/sv/LC_MESSAGES/django.po

[HL-886](https://helsinkisolutionoffice.atlassian.net/browse/HL-886)
and
[HL-1152](https://helsinkisolutionoffice.atlassian.net/browse/HL-1152)
Send email notifications about applications that have their benefit period ending in 30 days.
[HL-886]: https://helsinkisolutionoffice.atlassian.net/browse/HL-886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HL-1152]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: new command for ending benefit periods

---

backend/benefit/applications/services/applications_csv_report.py
backend/benefit/applications/services/applications_power_bi_csv_report.py
backend/benefit/applications/services/talpa_csv_service.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_applications_report.py
backend/benefit/applications/tests/test_talpa_integration.py

[HL-1502](https://helsinkisolutionoffice.atlassian.net/browse/HL-1502)
- Use instalment.amount_paid in talpa csv.
- Add instalment 1 and instalment 2 to powerBI csv report and handler csv report.
[HL-1502]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Hl 1502 csv changes

---

backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/applications/tests/test_applications_api.py
frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/hooks/useRequireAdditionalInformation.ts

Fix oversights made in #3523. Mainly, move `additional_information_required` logic to api endpoint.

fix: issues with addtional_information_required (hl-1566)

---

backend/benefit/applications/fixtures/test_applications.json
backend/benefit/calculator/api/v1/views.py
frontend/benefit/handler/browser-tests/pages/10-talpa-error-handling.testcafe.ts
frontend/benefit/handler/src/components/applicationList/HandlerIndex.tsx
frontend/benefit/handler/src/components/applicationList/TalpaStatusChangeDialog.tsx
frontend/benefit/shared/src/constants.ts
frontend/shared/src/components/header/Header.tsx

* Add testing for talpa status and instalment error resolution

test: add tests for talpa status and instalment error resolution (hl-1588)

---

backend/benefit/applications/api/v1/application_views.py
frontend/benefit/handler/src/components/header/Header.tsx
frontend/benefit/handler/src/components/header/TemporaryAhjoModeSwitch.tsx

Add applications with pending second instalments in simplified_list API response.

fix: issues with 2nd instalment not showing up in frontpage

---

frontend/kesaseteli/employer/browser-tests/actions/employer-header.actions.ts
frontend/shared/browser-tests/page-models/Header.ts

Fix lint issues noticed by my linter. Wonder why they popped up now.

chore: lint header

---

backend/benefit/applications/enums.py
backend/benefit/applications/tests/conftest.py

fix(benefit): remove year from the application title

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/pages/accessibility-statement.tsx

Update contact info in accessibility statement to Traficom
https://helsinkisolutionoffice.atlassian.net/browse/RATY-160

chore: update accessibility statement contact info

---

backend/tet/tet/settings.py

refs: TETP-310, TETP-314
Co-PR: https://dev.azure.com/City-of-Helsinki/yjdh-tet/_git/yjdh-tet-pipelines/pullrequest/10959

fix: migrate TET from tunnistamo to tunnistus

---

.env.tet.example

chore: update example env to use tunnistus

---

.github/dependabot.yml
CODEOWNERES

- adds CODEOWNERS file to root
- update dependabot config to update only security updates and simplify to target all frontend projects with one entry (should work, let's see)

HL-1618-yjdh-dependabot-configuration

---

release-please-config.json

Adds more valid sections to changelog-sections

chore: yjdh release-please-config tweak

---

backend/benefit/helsinkibenefit/settings.py
backend/kesaseteli/kesaseteli/settings.py

[HL-1634](https://helsinkisolutionoffice.atlassian.net/browse/HL-1634)
[YJDH-741](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-741)
[HL-1634]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[YJDH-741]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: postgres database to use database url + password combination
