backend/applications/tests/factories.py
backend/oidc/mock_views.py
backend/oidc/tests/test_mock_views.py
backend/oidc/urls.py

For testing purposes mock the oidc auth flow views so that it is not required to call Helsinki Profile.
[YJDH-80](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-80)

YJDH-80 | Backend: Add mock setup for Helsinki Profile auth flow

---

.env.kesaseteli.example
backend/kesaseteli/kesaseteli/settings.py
backend/kesaseteli/oidc/mock_views.py
backend/kesaseteli/oidc/tests/test_mock_views.py
backend/kesaseteli/oidc/tests/test_oidc_views.py
backend/kesaseteli/oidc/views.py

- Modify the OIDC logout view to support POST requests instead of GET.
- Return a HttpResponse with status 200 instead of redirect.

Change OIDC logout method from GET -> POST

---

.env.kesaseteli.example
README.md
backend/kesaseteli/README.md
backend/kesaseteli/docker-entrypoint.sh
backend/kesaseteli/kesaseteli/settings.py
backend/kesaseteli/oidc/services.py
backend/kesaseteli/oidc/tests/test_auth_backend.py
backend/kesaseteli/oidc/tests/test_eauth_views.py
backend/kesaseteli/oidc/tests/test_oidc_views.py
backend/kesaseteli/oidc/urls.py
backend/kesaseteli/oidc/utils.py
backend/kesaseteli/oidc/views/eauth_views.py
backend/kesaseteli/oidc/views/hki_views.py
backend/kesaseteli/requirements-dev.in
backend/kesaseteli/requirements-dev.txt
frontend/kesaseteli/employer/src/backend-api/backend-url.ts

Run local django server with SSL sertificate to get https callback urls that are required by suomi.fi eauthorizations. Also running the localhost as https also helps to bring the local environment closer to staging / production.
Add functionality for the suomi.fi eauthorizations flow. Upon successful helsinki profiili authentication, redirect the user straight to the suomi.fi valtuudet authorization init view that first handles the user registration for the valtuudet API and then redirects the user to the valtuudet authentication flow to choose the company on whose behalf they are doing business.
After receiving the "code" in EauthAuthenticationCallbackView, switch that to the auth tokens from the suomi.fi token endpoint. Save the tokens to EAuthorizationProfile for later use and to fetch …

YJDH-69 | Eauthorizations OIDC flow

---

frontend/shared/src/server/next-server.js
localdevelopment/kesaseteli/nginx/Dockerfile
localdevelopment/kesaseteli/nginx/entrypoint.sh

Fix the nginx setup by adding an entrypoint file where the cert is created if it is missing and starting the nginx server.

YJDH-109 | Fix kesaseteli nginx setup

---

README.md
docker-compose.benefit.yml
docker-compose.kesaseteli.yml
package.json

Hot reloading did not work for frontend services in docker-compose. This is now fixed-

Fix hot reload on docker-compose + clean up docker scripts

---

.github/workflows/ks-pytest.yml
backend/kesaseteli/applications/tests/conftest.py
backend/kesaseteli/applications/tests/test_applications_api.py
backend/kesaseteli/companies/api/v1/views.py
backend/kesaseteli/companies/tests/conftest.py
backend/kesaseteli/companies/tests/test_company_api.py
backend/kesaseteli/kesaseteli/settings.py
backend/kesaseteli/oidc/auth.py
backend/kesaseteli/oidc/tests/test_eauth_rest_auth.py
backend/kesaseteli/oidc/tests/test_eauth_views.py
backend/kesaseteli/oidc/utils.py
backend/kesaseteli/requirements-dev.in
backend/kesaseteli/requirements-dev.txt

- Add EAuthRestAuthentication as the default authentication class to authorize the user to use the REST API.
- Add IsAuthenticated as the default permission class for the REST API.
- Update the tests to match the new implementation of the company API.
- Small refactors to make the code cleaner.
[YJDH-120](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-120)

YJDH-120 | Update company API

---

.env.benefit.example
backend/benefit/companies/api/v1/views.py
backend/benefit/companies/tests/test_api.py
backend/benefit/helsinkibenefit/urls.py

Changing Company Get API to get business_id from path instead of header, which is more convenient for client side
Also add the CORS_ORIGIN_ALLOW_ALL = 1 to example .env

Update company API to use query string instead of header

---

frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/DeMinimisAidForm.tsx

- Disable future values for "de minimis" aid
- In the creating / editing process of an application, go to the first step 
- Under "Hakijan de minimis-tuet" select "Kyllä" and fill in the values
- Now the **future** date values are disabled, and the user can only select values from the past
- You should be able to continue to the next step as expected

HL-113 | Disable future values for "de minimis" aid

---

.github/dependabot.yml

Fixing dependabot pr builds: use '-' separator instead of '/' in dependabot pr branch names

---

frontend/benefit/applicant/src/components/applications/Applications.sc.ts
frontend/benefit/applicant/src/components/applications/applicationList/ApplicationList.sc.ts
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.sc.ts
frontend/benefit/applicant/src/components/applications/forms/application/Application.sc.ts
frontend/benefit/applicant/src/components/applications/forms/application/step1/companyInfo/CompanyInfo.sc.ts
frontend/benefit/applicant/src/components/mainIngress/MainIngress.sc.ts
frontend/kesaseteli/employer/src/components/companyInfo/CompanyInfo.sc.ts
frontend/shared/src/components/container/Container.sc.ts
frontend/shared/src/components/content/Content.sc.ts
frontend/shared/src/components/forms/fields/fieldLabel/FieldLabel.sc.ts
frontend/shared/src/components/forms/heading/Heading.sc.ts
frontend/shared/src/components/forms/section/FormSection.sc.ts
frontend/shared/src/components/forms/spacing/Spacing.sc.ts
frontend/shared/src/components/layout/Layout.sc.ts
frontend/shared/src/components/stepper/Stepper.sc.ts

- In VSCode, importing styled-components in a different name other than `styled` prevents the extension from working properly:
>There's no syntax highlighting?
Syntax Highlighting is specifically made to work with styled so make sure your default import is styled and nothing else.
See: https://github.com/styled-components/vscode-styled-components/issues/118#issuecomment-833007295
Therefore, I renamed the default import from $ to `styled`but kept the components name as they are. e.g:
~~`export const $SecondaryButton = $(Button)`~~
`export const $SecondaryButton = styled(Button)`
- Everything should works as expected

Import styled components as "styled" rather than "$"

---

.github/workflows/ks-frontend-tests-push.yml

On pushes to main or develop branch, send a message to slack from failed frontend tests.
[YJDH-147](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-147)

YJHD-147 | Send frontend test failures to slack

---

backend/shared/shared/oidc/services.py

Old company info is preserved if an user re-logins with a different company. Remove the company info on login if company info exists.
[YJDH-161](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-161)

 YJDH-161 | Remove stale company info from eauthorization profile

---

backend/shared/shared/oidc/services.py
backend/shared/shared/oidc/tests/test_backchannel_logout.py
backend/shared/shared/oidc/urls.py
backend/shared/shared/oidc/views/hki_views.py

Add backchannel logout to the shared oidc component. Implementation loosely based on tunnistamo and: City-of-Helsinki/tunnistamo#154
[YJDH-157](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-157)

YJDH-157 | OIDC backchannel logout

---

frontend/benefit/applicant/next.config.js
frontend/kesaseteli/employer/next.config.js

It seems that next-build is broken in dev-mode after next.js v11.1.0 update. Here is the fix for it.

Fix frontend next build

---

backend/benefit/docker-entrypoint.sh
backend/kesaseteli/docker-entrypoint.sh

Running docker-entrypoints.sh had "makemigrations" command, which would generate unneeded migration files.

remove ./manage.py makemigrations from docker-entrypoint.sh

---

backend/kesaseteli/common/tests/conftest.py
backend/kesaseteli/common/tests/factories.py
backend/shared/shared/common/tests/factories.py
backend/shared/shared/oidc/urls.py
backend/shared/shared/oidc/views/eauth_views.py
backend/shared/shared/oidc/views/hki_views.py

Fetches the language from GET parameters on the /authenticate call and sends that to helsinki profile and suomi.fi as a url query parameter. The language is saved in Django session during the auth flow.
[YJDH-136](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-136)
[YJDH-137](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-137)

YJDH-135 | Backend: Send language to helsinki profile and suomi.fi

---

backend/benefit/applications/models.py
backend/benefit/applications/tests/test_models.py

For Talpa integration. The same code could be useful for other purposes, too
HL-125
backend/benefit/applications/tests/test_models.py

HL-125: add properties for accessing company address info based on use_alternative_address

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/migrations/0016_benefit_amount.py
backend/benefit/applications/tests/test_applications_api.py

Add the name of the originally uploaded file to the API
Also fix an extra "s" letter in old migration
HL-79
backend/benefit/applications/tests/test_applications_api.py

add attachment_file_name, fix typo in old migration

---

backend/shared/shared/oidc/auth.py

Handle a rare race condition in the mocked rest authentication.
```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "oidc_oidcprofile_user_id_key"
```

Backend: Fix rare race condition in mock authentication

---

.github/workflows/bf-pytest.yml
backend/benefit/README.md
backend/benefit/applications/api/v1/application_batch_views.py
backend/benefit/applications/models.py
backend/benefit/applications/services/ahjo_integration.py
backend/benefit/applications/services/pdf_templates/associations.html
backend/benefit/applications/services/pdf_templates/base.html
backend/benefit/applications/services/pdf_templates/companies_benefit_with_de_minimis_aid.html
backend/benefit/applications/services/pdf_templates/companies_benefit_without_de_minimis_aid.html
backend/benefit/applications/services/pdf_templates/composed_accepted_private.html
backend/benefit/applications/services/pdf_templates/composed_accepted_public.html
backend/benefit/applications/services/pdf_templates/composed_declined_private.html
backend/benefit/applications/services/pdf_templates/composed_declined_public.html
backend/benefit/applications/tests/snapshots/snap_test_ahjo_integration.py
backend/benefit/applications/tests/test_ahjo_integration.py
backend/benefit/applications/tests/test_application_batch_api.py
backend/benefit/helsinkibenefit/settings.py
backend/benefit/requirements-dev.in
backend/benefit/requirements-dev.txt
backend/benefit/requirements.in
backend/benefit/requirements.txt
backend/benefit/setup.cfg
backend/docker/benefit.Dockerfile
backend/shared/precommit-setup.cfg
backend/shared/setup.cfg

- Add API endpoint to export application batch
- Each application in a batch will be generated to a single PDF files, the template will be decided based on the application type (company type, deminimis aid)
- Composed files are also generated, each will have two version: private and public, where the public pdf won't include employee data
NOTE: After the demo with PO, it turned out that the template should be updated so it can contain more information of the application, also design for the template might be considered later. So this PR is basically focus on the export function and its logic, any change to the template can be update later in a separated PR
Some example PDF:
Public composed file
[Liite 1 Helsinki-lisä 2021 koontiliite yhteisöille mallipohja …

HL-149 | Export Application Batch to PDF before sending to AHJO

---

backend/kesaseteli/applications/api/v1/serializers.py
backend/kesaseteli/applications/tests/test_applications_api.py

Frontend relies on the summer voucher IDs staying the same between updates. Add a list serializer for the summer vouchers so that we can update the existing objects instead of deleting everything and creating new objects.
-

KS-Backend: Keep IDs on SummerVoucher updates

---

backend/benefit/companies/api/v1/views.py
backend/kesaseteli/applications/api/v1/serializers.py
backend/kesaseteli/companies/api/v1/views.py
backend/kesaseteli/companies/services.py
backend/shared/shared/oidc/auth.py
backend/shared/shared/oidc/tests/test_eauth_rest_auth.py
backend/shared/shared/oidc/utils.py

Refactor get_organization_roles so that the roles are saved in session after login. After login the roles will be fetched from the session.
This is done because the access token that we get from suomi.fi is used only for getting these roles and the ttl of the token is only 10 minutes. So later when calling this function we can be assured that the roles are already fetched and there is no need to call the suomi.fi organizationRoles API.
[YJDH-175](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-175)

YJDH-175 | Backend: Save organization roles in session

---

backend/benefit/applications/api/v1/serializers.py

Missing return statement causing the serializer field will be always None after validation

Fix validation to return values

---

frontend/kesaseteli/employer/public/locales/en/common.json
frontend/kesaseteli/employer/public/locales/fi/common.json
frontend/kesaseteli/employer/public/locales/sv/common.json
frontend/kesaseteli/employer/src/components/application/login.sc.ts
frontend/kesaseteli/employer/src/pages/login.tsx
frontend/shared/src/components/Layout.tsx

Add login page styles and translations.
Modify the Layout shared component so that headingText is optional.
Invision: https://invis.io/WT10T1E97XKB#/453766715_Koti_Login
[YJDH-197](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-197)

YJDH-197 | KS-Employer: Login page

---

backend/kesaseteli/applications/api/v1/serializers.py
backend/kesaseteli/applications/tests/test_application_validation.py

When student was born 2004, `summer_voucher_serial_number` is not required.

YJDH-199 | KS-Backend: Adjust validation when student born 2004

---

backend/kesaseteli/applications/api/v1/permissions.py
backend/kesaseteli/applications/api/v1/views.py
backend/shared/shared/oidc/auth.py
backend/shared/shared/oidc/tests/test_eauth_views.py
backend/shared/shared/oidc/views/eauth_views.py

There was a problem when DRF was fetching the organization roles from the suomi.fi eauthorizations API every time instead of using the session variable. Save the organization roles to session on login instead of the DRF session authentication class `EAuthRestAuthentication`.

Backend: Save organization roles to session on login

---

backend/kesaseteli/applications/api/v1/permissions.py
backend/shared/shared/oidc/auth.py
backend/shared/shared/oidc/services.py
backend/shared/shared/oidc/tests/test_eauth_rest_auth.py
backend/shared/shared/oidc/tests/test_eauth_views.py

Fix an issue where:
1. User A logs in with company X
2. User session times out.
3. User A logs in with company Y.
4. System shows info of company X.
[YJDH-205](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-205)

YJDH-205 | Backend: Fix previous company shown on login

---

backend/kesaseteli/applications/api/v1/permissions.py
backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/tests/test_applications_api.py
backend/kesaseteli/applications/tests/test_attachments_api.py
backend/kesaseteli/common/tests/conftest.py

Allow for the users to view already submitted applications. This is needed to show the summary of the application on the thank you page.
[YJDH-206](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-206)

YJDH-206 | KS-Backend: Allow viewing submitted applications

---

backend/benefit/.prod/uwsgi.ini
backend/kesaseteli/.prod/uwsgi.ini

With some long callback URLs, uwsgi will throw 502 errors with the message:
`[WARNING] unable to add HTTP_X_FORWARDED_HOST=... to uwsgi packet, consider increasing buffer size.`
Increase the buffer size to (try to) resolve this.

KS-Backend: Fix 502 error in production

---

backend/shared/shared/oidc/views/eauth_views.py

Ensure that the CSRF cookie is set on login. Fix a case where Django complains about missing or invalid CSRF token.

Backend: Ensure CSRF cookie

---

backend/shared/shared/oidc/auth.py
backend/shared/shared/oidc/services.py
backend/shared/shared/oidc/tests/test_eauth_rest_auth.py

Fix the refreshing of helsinki profile access token. No need to create a new OIDCProfile instance but instead need to update the existing instance.

Backend: Fix refreshing tokens

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/step5/useApplicationFormStep5.ts
frontend/benefit/applicant/src/components/applications/forms/application/step6/useApplicationFormStep6.ts
frontend/benefit/applicant/src/hooks/useFormActions.tsx
frontend/benefit/applicant/src/utils/common.ts

- Show success notification upon saving the application
- Go to any step of the application, click on "Tallenna ja jatka myöhemmin" at the bottom of the page
- If the saving goes successfully, you will be redirected to the home page
- A success notification will be displayed with the applicant's name (if filled in) and the application number on it
- The application number is now not assigned due to a bug in the backend

HL-252 | Show success notification upon saving the application

---

backend/benefit/helsinkibenefit/settings.py
backend/kesaseteli/kesaseteli/settings.py
backend/shared/shared/azure_adfs/README.md

With certain users the `unique_name` parameter contains illegal characters for a django username. Use the `name` parameter instead which should be the email of the user, thus valid username and unique as well.

Backend: Fix ADFS login username

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/tests/test_applications_api.py

Add application_number to API fields
HL-264
backend/benefit/applications/tests/test_applications_api.py:test_application_single_read

HL-264: fix missing application number in API

---

localdevelopment/kesaseteli/nginx/nginx.conf

Add `client_max_body_size 20M;` to local nginx conf to allow uploading large files.

Kesäseteli: Add client max body size to local nginx

---

frontend/kesaseteli/employer/src/components/application/form/DateInput.tsx
frontend/kesaseteli/employer/src/components/application/form/TextInput.tsx

Add red error border when submitting fields with invalid data.
https://helsinkisolutionoffice.atlassian.net/browse/YJDH-216

YJDH-216 | KS-Employer: Add red border on invalid fields

---

frontend/kesaseteli/employer/public/locales/en/common.json
frontend/kesaseteli/employer/public/locales/fi/common.json
frontend/kesaseteli/employer/public/locales/sv/common.json
frontend/shared/src/components/forms/heading/Heading.tsx

Adjust the the tooltip buttons to show translated aria-labels for users with screen readers.
[YJDH-274](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-274)

YJDH-274 | KS-Employer: Adjust accessability of tooltips

---

frontend/kesaseteli/employer/src/components/application/form/DateInput.tsx

Change the onBlur event to onChange to validate the datepicker value correctly even when the date is picked with the datepicker element instead of writing it.
[YJDH-293](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-293)

YJDH-293 | KS-Employer: Add modify datepicker validation

---

backend/benefit/common/delay_call.py

update_now_or_later results in error when multiple threads are used, as threadlocal variable is not initialized

Fix issue with do_delayed_calls_at_end when using multiple threads

---

.github/workflows/bf-review.yml
.github/workflows/ks-review.yml

Let's try the kolga delay parameters to fix occasionally failing deploys.
Added the following:
`  K8S_PROBE_FAILURE_THRESHOLD: 30
K8S_PROBE_PERIOD: 20`
So it should check every 20 second if the service is deployed, and repeating the check 30 times, so it would totally try 600 seconds (10 minutes) before giving up. Originally it would have failed after 210 seconds (3,5min). See description below for more details:
> You have the following ways to configure the startup time:
> K8S_PROBE_INITIAL_DELAY: This is the time Kubernetes waits before doing any checks for the application (default: 60)
> K8S_PROBE_FAILURE_THRESHOLD: This is the times the health check can fail before the application is seen as unhealthy (default: 3)
> K8S_PROBE_PERIOD: This is the time between health checks (default: …

Try kolga deploy delay params

---

.env.kesaseteli.example

PR #410 changed .env.kesaseteli.example NEXT_PUBLIC_BACKEND_URL from
https to http (See commit fdd152dabff7350a212b765eb65517c771c9cdfa).
This caused a problem in testing when copying .env.kesaseteli.example
to .env.kesaseteli and opening https://localhost:3000/:
- "Access to XMLHttpRequest at 'http://localhost:8000/oidc/userinfo/'
from origin 'https://localhost:3000' has been blocked by CORS policy:
Response to preflight request doesn't pass access control check:
Redirect is not allowed for a preflight request."
Change NEXT_PUBLIC_BACKEND_URL back to https. This removes the above
problem.
Refs YJDH-327

YJDH-327 | Use https in NEXT_PUBLIC_BACKEND_URL

---

frontend/benefit/applicant/src/components/applications/forms/application/step5/employeeView/EmployeeView.tsx

bug fixed: if apprenticeship program is No, the %es were not shown at all in the summary page.

HL-225: Fix summary pay subsidy section logic

---

backend/benefit/calculator/tests/test_handler_excel_examples.py

The final fix to the previous PR was left out by mistake

HL-318: re-enable running of employment benefit tests

---

backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/common/utils.py

Add check that the Finnish social security number has no whitespace and
is uppercase. Affects YouthApplication's social security number.
Add more test cases in test_youth_applications_api.py for valid and
invalid social security numbers.
Refs YJDH-347
YJDH-347

YJDH-347 | Make social security number check stricter

---

backend/benefit/companies/api/v1/views.py
backend/benefit/companies/services.py
backend/benefit/companies/tests/conftest.py
backend/benefit/companies/tests/data/company_data.py
backend/benefit/companies/tests/test_api.py
backend/benefit/helsinkibenefit/settings.py
backend/benefit/helsinkibenefit/urls.py
backend/benefit/users/utils.py
backend/shared/shared/yrtti/yrtti_client.py

YRTTI API Integration to query association info via Palveluväylä
Documentation of YRTTI API can be found: https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/7562068053/Working+document+Integration+to+Palveluv+yl+from+app+developer+s+perspective
- Added a YRTTIClient to `shared` component, although AFAIK Kesaseteli does not support application for association.
- Update company query logic so it'll try to get association info if the first query to company return nothing.
- Update unittests

HL-321 | Integrate YRTTI API

---

frontend/benefit/handler/src/components/attachmentsListView/AttachmentsListView.tsx
frontend/benefit/handler/src/components/attachmentsListView/__tests__/AttachmentsListView.test.tsx
frontend/benefit/handler/src/types/application.d.ts

- Fix the types on the attachments on the Handler side
**Note:** now only shared components have the type Attachment, but service-specific components have the corresponding type (e.g. BenefitAttachment).

Fix the attachment type on the Handler side

---

frontend/benefit/applicant/src/components/applications/forms/application/step1/ApplicationFormStep1.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step1/useApplicationFormStep1.ts
frontend/benefit/applicant/src/components/applications/forms/application/step2/ApplicationFormStep2.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step2/useApplicationFormStep2.ts
frontend/benefit/applicant/src/components/applications/forms/application/step3/ApplicationFormStep3.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step3/useApplicationFormStep3.ts
frontend/benefit/applicant/src/components/applications/forms/application/step4/ApplicationFormStep4.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step4/useApplicationFormStep4.ts
frontend/benefit/applicant/src/components/applications/forms/application/step5/ApplicationFormStep5.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step5/useApplicationFormStep5.ts
frontend/benefit/applicant/src/components/applications/forms/application/step6/useApplicationFormStep6.ts
frontend/benefit/applicant/src/components/applications/forms/application/stepperActions/StepperActions.tsx
frontend/benefit/applicant/src/hooks/useDeleteApplicationQuery.ts
frontend/benefit/applicant/src/hooks/useFormActions.tsx
frontend/shared/src/components/modal/Modal.tsx
frontend/shared/src/components/modal/__tests__/Modal.test.tsx

- Implement a shared Modal component
- Implement the deleting logic in the form actions custom hook
- Add the deleting functionality to all steps
- From the application list, click on the edit button of one of the draft applications
- At the bottom of the page, click on the delete button
- A confirmation modal should open
- By confirming, the application should be deleted and you'll be redirected to the home page
- A success toast will appear to confirm that the application has been successfully deleted

HL-99 | Deleting draft applications

---

backend/kesaseteli/applications/migrations/0015_set_real_schools.py
backend/kesaseteli/applications/tests/test_schools_api.py

The school list was parsed manually on 2021-12-14 from
https://www.hel.fi/peruskoulut/fi/koulut/
School categories (e.g. "Yksityiset ammatilliset oppilaitokset") with
"ammatillinen", "ammatilliset" or "lukio" in their name were left out
and schools ending in " ala-asteen koulu" or " lågstadieskola" were left
out.
Refs YJDH-355
YJDH-355

YJDH-355 | KS-Backend: Set real school list

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/step5/companyInfoView/CompanyInfoView.tsx
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationReview/deminimisView/DeminimisView.tsx

Should show the text in application summary and handlers review when there are no deminimis aids granted

HL-338: Deminimis aids summary fix

---

frontend/benefit/applicant/src/components/applications/forms/application/step3/attachmentsList/AttachmentsList.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step3/useApplicationFormStep3.ts
frontend/benefit/applicant/src/components/applications/forms/application/step4/ApplicationFormStep4.tsx

- Add the validation logic for the Education Contract attachment
- Allow other file types for the power of attorney attachment
- Create a new application
- Proceed to step 2, under `Palkkatukipäätös` choose `Kyllä`
- Under `Onko kyseessä oppisopimus?` choose `Kyllä`
- Fill in the necessary fields and proceed to the next step
- You should NOT be able to go forward if `Palkkatukipäätös` attachment is missing (the `Jatka` button will be disabled)
- Going to step 4, file types other than PDF are now also acceptable

HL-300 & HL-346 | Attachments fixes

---

frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/__tests__/dates.test.ts
frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/dates.ts
frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/validation.ts

- Correcting the end date calculation logic
- Fix the unit tests
- Fix the validation of the start date
- Go to the second step
- Select the salary-based benefit type
- Select the first day of December for example
- The end date should default to the last day of December (previously, it was incorrectly 30th of Dec)
**Note:** Previously, selecting a start date in the next year resulted in a validation error. Now, this is fixed.

HL-357 | Employment date range fixes

---

frontend/benefit/applicant/src/hooks/useFormActions.tsx

- The De Minimis Aid values were always overridden by the corresponding context values, now this is fixed
- Create a new application
- Add some values to the De Minimis Aid
- Continue to step 2
- After filling in the required field, you should be able to proceed with the application with no errors

HL-363 | Fix the values of the De Minimis Aid Set

---

backend/benefit/companies/api/v1/views.py
backend/benefit/companies/services.py
backend/benefit/companies/tests/conftest.py
backend/benefit/companies/tests/data/company_data.py
backend/benefit/companies/tests/test_api.py
backend/benefit/helsinkibenefit/settings.py

Some test association can't be found in YTJ API. I revert the YRTTI changes so it can be used as a second source

HL-362 | Revert YRTTI API

---

.github/workflows/te-review.yml

The review environment is having issues with excessive load
described in YJDH-370. The temporary solution is to
disable frontends that are not yet under development.

Disable build and review env deploy of empty frontends

---

backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/kesaseteli/settings.py

**This makes the youth browser tests pass again:**
- The problem was that send_activation_email in the backend
failed and made the backend return an internal server error.
An activation email is sent when posting a youth application.
Add test_youth_application_post_valid_data_with_email_backends which
tests that using different email backends when posting a youth
application works.
Using MOCK_FLAG rather than DEBUG for choosing which email backend to
use seems more appropriate here.
YJDH-374

YJDH-374 | KS-Backend: Make activation email sending more lenient

---

backend/kesaseteli/applications/admin.py
backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/migrations/0016_add_youth_application_field_validation.py
backend/kesaseteli/applications/migrations/0017_refactor_school.py
backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/tests/test_application_validation.py
backend/kesaseteli/applications/tests/test_schools_api.py

Remove deleted schools (i.e. the ones with non-null deleted_at values).
Remove School.deleted_at as unnecessary, all Schools are active now.
Remove SchoolQuerySet as unnecessary.
Replace validate_school use with validate_name, also retroactively.
Add validate_name validator to School.name.
Remove validate_school validator as unnecessary.
Update related tests.
Add School editing to Django admin.
YJDH-230 (Django admin interface for updating schools)
YJDH-376 (Refactoring / simplifying school list maintenance)
You can edit the school list using Django admin:
- `yarn youth --build`
- Login into `https://localhost:8000/admin/` using admin/admin
- Edit schools using Applications > Schools > Add/Change:
- ![schools](https://user-images.githubusercontent.com/77663720/148202622-3f7cebcb-3534-40c6- …

YJDH-376 | Refactor and simplify School

---

.github/workflows/ks-pytest.yml
backend/kesaseteli/README.md
backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/locale/en/LC_MESSAGES/django.po
backend/kesaseteli/applications/locale/fi/LC_MESSAGES/django.po
backend/kesaseteli/applications/locale/sv/LC_MESSAGES/django.po
backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/tests/conftest.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/common/locale/en/LC_MESSAGES/django.po
backend/kesaseteli/common/locale/fi/LC_MESSAGES/django.po
backend/kesaseteli/common/locale/sv/LC_MESSAGES/django.po
backend/kesaseteli/companies/locale/en/LC_MESSAGES/django.po
backend/kesaseteli/companies/locale/fi/LC_MESSAGES/django.po
backend/kesaseteli/companies/locale/sv/LC_MESSAGES/django.po
backend/kesaseteli/docker-entrypoint.sh
backend/kesaseteli/kesaseteli/locale/en/LC_MESSAGES/django.po
backend/kesaseteli/kesaseteli/locale/sv/LC_MESSAGES/django.po
backend/kesaseteli/requirements-dev.in
backend/kesaseteli/requirements-dev.txt

Add langdetect to requirements-dev.(in|txt). Used for detecting the used
language in the activation email's subject and body in the tests.
Revamp the activation email related functions a little bit. Switched to
using gettext here instead of gettext_lazy because without it the email
subject didn't correctly get translated in the tests. Translate the
activation email subject and body according to the youth application's
language.
Add placeholder translations for the activation email's subject and
body for Swedish and English.
Add tests for Finnish, Swedish and English:
- test_youth_application_post_valid_language
- Tests that posting a new youth application is successful with
different languages
- test_youth_application_activation_email_language
- Tests that the activation email's subject …

YJDH-356 | KS-Backend: Translate activation email to fi/sv/en

---

.github/workflows/ks-pytest.yml
backend/docker/kesaseteli.Dockerfile
backend/kesaseteli/applications/api/v1/views.py
docker-compose.youth.yml

Based on discussion in https://github.com/docker-library/postgres/issues/725#issuecomment-624141851
backend/docker/kesaseteli.Dockerfile:
- Add finnish_postgres target based on postgres:12 which sets up the
PostgreSQL image to use Finnish language and database collation
docker-compose.youth.yml:
- Use the finnish_postgres target
Using finnish_postgres kesaseteli-db is initialized like this:
- The database cluster will be initialized with locale "fi_FI.UTF-8".
- The default database encoding has accordingly been set to "UTF8".
- The default text search configuration will be set to "finnish".
Listing the databases in the kesaseteli-db using
```docker exec -it kesaseteli-db psql -Ukesaseteli -c"\l"```
now gives (Removed irrelevant information for compact output):
```
List of databases
Name …
```

YJDH-345 | KS-Backend: Use Finnish PostgreSQL in Docker

---

frontend/benefit/applicant/src/components/applications/forms/application/step2/ApplicationFormStep2.tsx

Remove unnecessary messages when selecting salary benefit type
>When I choose that there is palkkatuki, but it is not oppisopimus and then choose the benefit type Palkan Helsinki-lisä, I ?get the infobox of oppisopimus and there is text: Oppisopimuksessa 12 kk ylittävältä jaksolta tehdään uusi hakemus. I don’t want information about oppisopimus, if I choose that it is not oppisopimus. 
Before:
After:

HL-299 | Fix salary benefit type message step 2

---

.github/workflows/ks-pytest.yml
backend/docker/finnish_postgres.Dockerfile
backend/docker/kesaseteli.Dockerfile
backend/kesaseteli/applications/api/v1/views.py
docker-compose.youth.yml

Revert the changes from PR #582 related to GitHub Actions.
Also:
- Move Finnish Postgres to own Dockerfile and use it from there
- Add back PostgreSQL specific custom sorter to SchoolListView because
otherwise the backend tests won't pass using GitHub Actions.
NOTE:
- Hotfixing YJDH-405 to get "(KS) Python tests" working again in pull
requests while looking for a way to use Finnish Postgres in GitHub
Actions.
YJDH-405

YJDH-405 | Fix ks-pytest.yml by not using Finnish Postgres

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/benefit_aggregation.py
backend/benefit/applications/tests/test_benefit_aggregation.py

Add new "warnings" element to the API that can be used for other kinds of warnings, too.
Rename past_benefit_info.
Add tests for overlapping previously granted benefit.

HL-379: time range validation errors should be warnings.

---

backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/enums.py
backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/tests/test_misc.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/common/tests/factories.py
backend/kesaseteli/kesaseteli/settings.py

Redirect on youth application activation to the following frontend URLs
(Language is fi, sv or en):
- `/<language>/activated` if activation was successful
- `/<language>/expired` if activation link has expired
- `/<language>/already_activated` if application is already activated
Add applications.enums.get_supported_languages function:
- Get the supported languages, currently returns ('fi', 'sv', 'en').
Tests:
- Make use of applications.enums.get_supported_languages function
- Update related tests in test_youth_applications_api.py
- Add test_misc.py:
- Add test test_youth_application_page_url_function
- Test that YouthApplication instance's member functions generate
frontend URLs correctly
Refs YJDH-396 (Redirecting to successful activation page)
Refs YJDH-400 (Redirecting to expired …

YJDH-396 | KS-Backend: Add redirects to youth application activation

---

frontend/kesaseteli/youth/src/pages/activated.tsx
frontend/kesaseteli/youth/src/pages/already_activated.tsx
frontend/kesaseteli/youth/src/pages/already_assigned.tsx
frontend/kesaseteli/youth/src/pages/email_in_use.tsx
frontend/kesaseteli/youth/src/pages/expired.tsx
frontend/kesaseteli/youth/src/pages/thankyou.tsx
frontend/shared/src/components/pages/NotificationPage.tsx
frontend/shared/src/components/pages/PageNotFound.tsx

Use NotificationPage as base component for all activation,thank you - and error pages

Refactor: use NotificationPage as base component for all ok/error pages

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/applicationList/ApplicationList.sc.ts
frontend/benefit/applicant/src/components/applications/applicationList/ApplicationList.tsx
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.sc.ts
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.tsx
frontend/benefit/applicant/src/components/applications/applicationList/useApplicationList.ts
frontend/benefit/applicant/src/types/application.d.ts

- The new messages indicators shows for the applicant if there are new messages in the application
IMPORTANT: BY SPEX: the count is not showing the count of the actual unread messages in all applications in the list, but the NUMBER OF APPLICATIONS which have unread messages.
Currently there is no way to check in which application the unread messages are. This feature is planned for future development as "notification center functionality"

HL-372: Message indicator

---

frontend/benefit/handler/src/components/header/Header.tsx
frontend/shared/src/components/header/Header.tsx

Adds the handler logo url
Adds optional titleUrl param to the shared header
Note: applicant logo url is not needed

HL-313: Handler logo url

---

backend/kesaseteli/applications/api/v1/serializers.py
backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/enums.py
backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/tests/test_enums.py
backend/kesaseteli/applications/tests/test_querying.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/shared/setup.cfg
backend/shared/shared/common/tests/test_utils.py
backend/shared/shared/common/utils.py

Remove unnecessary savings of YouthApplication model instances from
test_youth_applications_api.py tests. This is in preparation for the
YJDH-398 tests where existing saved YouthApplication instances would
make a difference.
Additionally:
- Make YouthApplicationSerializer return more specific error by
specifying the social_security_number field as the source of the
validation error.
- Update tests to check that returned error is field specific:
- test_youth_application_post_missing_required_field
- test_youth_application_post_empty_required_field
When creating/submitting a new youth application handle errors:
- Activated youth application with same email or social security number
already exists
- Return 400 Bad Request and JSON:
{"code": "already_assigned", "message": "<human readable …

YJDH-398 | KS-Backend: Add error handling to youth application creation

---

backend/kesaseteli/applications/api/v1/serializers.py
backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/common/permissions.py
backend/kesaseteli/common/utils.py

YouthApplication's detail view is accessible now using:
- reverse("v1:youthapplication-detail", kwargs={"pk": pk})
- e.g. locally `https://localhost:8000/v1/youthapplications/<pk>/`
The detail view returns the YouthApplication's information for the
youth application / youth summer voucher handler.
Also:
- Add encrypted_vtj_json to YouthApplicationSerializer so it is sent to
the handler through the detail view. Convert it from string to JSON
and convert None and empty string to {}.
- Create backend/kesaseteli/common/permissions.py
- Add stub for IsHandler permission
- TODO: Implement, split to ticket YJDH-435
- Move DenyAll from backend/kesaseteli/common/utils.py here
- test_youth_applications_api.py tests:
- Add email to required fields
- Add tests:
- …

YJDH-418 | KS-Backend: Add detail view for YouthApplication

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/step2/ApplicationFormStep2.tsx

Add extra explanation row for salary related expenses

HL-378: Add extra explanation row for salary related expenses

---

frontend/benefit/applicant/src/hooks/useFormActions.tsx

When creating application, we set default value for apprenticeship program as false, fixing because we don't want default value for this

HL-348: Not saving application with default apprenticeship program value

---

frontend/kesaseteli/youth/browser-tests/actions/send-youth-application.ts
frontend/kesaseteli/youth/browser-tests/index-page/indexPage.testcafe.ts
frontend/kesaseteli/youth/browser-tests/notification-page/alreadyAssignedPage.components.ts
frontend/kesaseteli/youth/browser-tests/notification-page/emailInUsePage.components.ts
frontend/kesaseteli/youth/browser-tests/utils/url.utils.ts
frontend/kesaseteli/youth/src/__tests__/index.test.tsx
frontend/kesaseteli/youth/src/__tests__/utils/backend/backend-nocks.ts
frontend/kesaseteli/youth/src/components/constants/creation-error-codes.ts
frontend/kesaseteli/youth/src/components/constants/creation-error-types.ts
frontend/kesaseteli/youth/src/components/forms/YouthForm.tsx
frontend/kesaseteli/youth/src/types/youth-application-creation-error.d.ts
frontend/kesaseteli/youth/src/utils/type-guards.ts
frontend/shared/src/components/forms/buttons/SaveFormButton.tsx
frontend/shared/src/utils/typescript.utils.ts
frontend/yarn.lock

Show specific error pages when
-  email is already in use in other application  
- there is an already registered kesaseteli with same ssn or email
Also including browser tests to these special cases

Yjdh-350: Show creation error pages

---

backend/docker/kesaseteli.Dockerfile
backend/kesaseteli/docker-entrypoint.sh
docker-compose.employer.yml
docker-compose.handler.yml
docker-compose.youth.yml

Compile messages in Docker image build in kesaseteli.Dockerfile to
remove the need for writeable localization directories in the Docker
container. This should fix the error in Platta environment about not
being able to write the generated django.mo files.
Also override the entrypoints in the docker-compose files using the
Kesäseteli backend because although "django-admin compilemessages" is
now run as a part of Docker image build, the resulting files are
overridden by the volume mounts in the docker-compose files and thus
have to regenerated.
YJDH-459

YJDH-459 | KS-Backend: Compile messages in Docker image build

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationReview/calculatorErrors/CalculatorErrors.tsx
frontend/benefit/handler/src/components/applicationReview/employmentAppliedMoreView/EmploymentAppliedMoreView.tsx
frontend/benefit/handler/src/components/applicationReview/employmentAppliedMoreView/useEmploymentAppliedMoreView.ts
frontend/benefit/handler/src/hooks/useHandlerReviewActions.tsx

- Error notifications implemented
- Fixed the bug with not showing error on first Calculate click (caused by onError)
- Fixed fields namings for the notification error list

HL-434: Calculator error notifications

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/tests/test_benefit_aggregation.py
backend/benefit/calculator/api/v1/serializers.py
backend/benefit/calculator/models.py
backend/benefit/calculator/tests/test_calculator_api.py
backend/benefit/common/tests/test_utils.py
backend/benefit/common/utils.py

Add  duration in months field for PaySubsidy and Calculation objects in the API. The duration is rounded to two decimals, suitable for display in the UI.
Also add a last valid end_date for the calculation to the API, taking into account the previously accepted benefits.

HL-380: add duration_in_months_rounded and last_possible_end_date to API

---

frontend/benefit/applicant/Dockerfile
frontend/benefit/handler/Dockerfile
frontend/kesaseteli/employer/Dockerfile
frontend/kesaseteli/handler/Dockerfile
frontend/kesaseteli/youth/Dockerfile
frontend/tet/admin/Dockerfile
frontend/tet/employer/Dockerfile
frontend/tet/youth/Dockerfile

docker command `RUN chgrp -R 0 . && chmod -R g+rwX .` takes 23 minutes. Let's change it so that it doesnt try to change recursively every file in the `node_modules` folder. Let's add the user group earlier and change mode only for excutable files in the `node_modules/.bin` folder. 
After quick check it seems that the build time for example for ks-youth has dropped from 9.5 minutes to 6 minutes.
new docker file build time: https://github.com/City-of-Helsinki/yjdh/runs/4935611018?check_suite_focus=true
old docker file build time (from another pr):
https://github.com/City-of-Helsinki/yjdh/runs/4933217802?check_suite_focus=true

YJDH-432: improve docker image build times: remove write access

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/tests/test_applications_api.py

Change validation of apprenticeship_program for submitted applications:
If pay_subsidy_granted is selected, then the applicant needs to also select if
it's an apprenticeship_program or not
backend/benefit/applications/tests/test_applications_api.py:test_apprenticeship_program_validation_on_submit

HL-430: apprenticeship_program only needs to be selected if pay_subsidy_granted is selected

---

.github/workflows/bf-review.yml
.github/workflows/ks-review.yml
.github/workflows/te-review.yml

Juho Saarinen commented in Slack: "Basically lock should be namespace + service"
NOTE: If this seems to work, I'll add the same config for other YJDH subprojects

HL-421: reduce review environment build failures by limiting concurrency of jobs

---

backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/common/permissions.py
backend/shared/shared/common/tests/conftest.py

Before everyone was a handler.
Now everyone is a handler if the mock flag is set, otherwise no one is.
Parametrize tests with/without mock flag and with different clients:
- test_youth_applications_process_valid_pk
- Should return 403 Forbidden for all without mock flag
- Should return 501 Not implemented for all with mock flag
- test_youth_applications_detail_valid_pk
- Should return 403 Forbidden for all without mock flag
- Should return 200 OK for all with mock flag
Rename invalid_pk->unused_pk & parametrize tests with/without mock flag:
- test_youth_applications_process_unused_pk
- Use random UUID rather than "invalid value" string as primary key
- test_youth_applications_detail_unused_pk
- Use random UUID rather than "invalid value" string as primary key
Test only with mock flag:
- …

YJDH-446 | KS-Backend: Set handler permission to mock flag state

---

frontend/benefit/handler/src/components/applicationReview/employmentAppliedMoreView/EmploymentAppliedMoreView.tsx
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryBenefitCalculatorView.tsx

Fix applied dates and amount format in calculator views

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/tests/test_applications_api.py

Association applicants need not specify the de_minimis_aid parameter
backend/benefit/applications/tests/test_applications_api.py:test_submit_application_without_de_minimis_aid

HL-457: fix de_minimis_aid validation when submitting application

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/calculator/tests/test_models.py
backend/benefit/common/utils.py

The field is needed for display in the UI
backend/benefit/applications/tests/test_applications_api.py:test_application_single_read_as_applicant

HL-450: add duration_in_months_rounded to the application API

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/api/v1/status_transition_validator.py
backend/benefit/applications/enums.py
backend/benefit/applications/tests/test_applications_api.py

The application handlers need to be able to revert their decision
backend/benefit/applications/tests/test_applications_api.py:test_application_status_change_as_handler

HL-442: application can be returned from ACCEPTED and REJECTED statuses back to HANDLING

---

frontend/kesaseteli/youth/src/__tests__/index.test.tsx
frontend/shared/src/components/forms/inputs/SocialSecurityNumberInput.tsx
frontend/shared/src/constants.ts

Dont accept fake social security number having number nine in postfix part: `######A9##X`. More info about it in finnish: https://www.tuomas.salste.net/doc/tunnus/henkilotunnus.html#keinotunnus
Also better user experience on ssn field when there is already validation error on the field, it is cleared when getting valid.

Yjdh-484: Don't accept fake finnish ssn + better feed input on ssn field

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/terms/tests/test_api.py

Some application processing statuses need to be hidden from the applicant
backend/benefit/applications/tests/test_applications_api.py:test_application_single_read_as_applicant

HL-443: hide some application statuses from the applicant

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/tests/factories.py
backend/benefit/applications/tests/test_applications_api.py

submitted_at was always null in API responses
backend/benefit/applications/tests/test_applications_api.py:test_application_submitted_at

HL-474: fix submitted_at field in application api

---

backend/benefit/applications/services/applications_csv_report.py
backend/benefit/applications/services/csv_export_base.py
backend/benefit/applications/tests/test_applications_csv_report.py

If application had no calculation, csv export would return a http 500 error.
Use empty/default values for the missing fields instead.
backend/benefit/applications/tests/test_applications_csv_report.py:test_applications_csv_export_without_calculation

HL-473: fix csv export of applications without calculation

---

frontend/kesaseteli/youth/browser-tests/youth-application.testcafe.ts

In production there is an end user that claims that (s)he cannot send a new application after expiration. There is a browser test that proofs that it is possible. I also refactored the test file name and test descriptions to tell better what is the use case of each test.

youth-ui: New browser test to proof that if first application has expired, user can send same application again and activate it.

---

frontend/shared/src/utils/__tests__/mask-gdpr-data.test.ts

It seems that unit tests fail occasionally: `Given age (0) is not between sensible age range of 1 and 200`
https://github.com/City-of-Helsinki/yjdh/runs/5271461325?check_suite_focus=true
Let's fix it

fix occasionally failing unit test

---

backend/shared/shared/audit_log/tasks.py

Add op_type="create" that is required by ElasticSearch instance in Platta.
The issue causes errors like "elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'only write ops with an op_type of create are allowed in data streams')" when running the cron job.

HL-366: add missing op_type parameter when sending audit logs to ES

---

.github/workflows/bf-pytest.yml
.github/workflows/ks-pytest.yml
.github/workflows/te-pytest.yml
backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/common/decorators.py
backend/kesaseteli/common/urls.py
backend/kesaseteli/kesaseteli/settings.py
backend/shared/shared/azure_adfs/tests/test_adfs_login.py
backend/shared/shared/azure_adfs/views.py
backend/shared/shared/common/decorators.py
backend/shared/shared/common/tests/__init__.py
backend/shared/shared/common/utils.py

Enforce youth application handler ADFS login by adding
@enforce_handler_view_adfs_login decorator to:
- YouthApplicationViewSet.process
- Handler's processing email contains a link to this action
- YouthApplicationViewSet.detail
- Used by frontend to get data for processing a youth application
Revamp permission handling in YouthApplicationViewSet.
Add tests:
- test_youth_applications_forbidden_modification_methods
- Test that forbidden methods in YouthApplicationViewSet return
HTTP status 403 Forbidden which can also seen in the audit log
- test_youth_application_post_valid_audit_log
- Test that the posting of a valid youth application can be seen in
the audit log
Extend test with more parametrizations and audit log entry testing:
- test_youth_applications_list
Extend tests with more …

YJDH-251 | KS-Backend: Enforce youth application handler ADFS login

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/api/v1/views.py
backend/benefit/applications/models.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/applications/tests/test_applications_csv_report.py

The field contains the timestamp when the application was cancelled/rejected/accepted
Add handled_at field in API
The field contains the timestamp when the application was cancelled/rejected/accepted

HL-482: Add handled_at field in API

---

backend/benefit/applications/tests/test_applications_csv_report.py
backend/benefit/calculator/models.py

backend/benefit/applications/tests/test_applications_csv_report.py:test_applications_csv_monthly_amount_override

HL-480: csv export fails when override_monthly_benefit_amount is set

---

frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/validation.ts
frontend/shared/src/utils/__tests__/date.utils.test.ts
frontend/shared/src/utils/date.utils.ts

Fix applicant cannot choose 1.1 as start date

Fix applicant cannot choose 1.1 as start date

---

frontend/kesaseteli/handler/public/locales/fi/common.json
frontend/kesaseteli/handler/src/__tests__/index.test.tsx
frontend/kesaseteli/handler/src/__tests__/utils/backend/backend-nocks.ts
frontend/kesaseteli/handler/src/__tests__/utils/components/get-index-page-api.ts
frontend/kesaseteli/handler/src/components/form/ActionButtons.tsx
frontend/kesaseteli/handler/src/components/form/HandlerForm.tsx
frontend/kesaseteli/handler/src/hooks/backend/useCompleteYouthApplicationQuery.ts
frontend/kesaseteli/handler/src/hooks/backend/useYouthApplicationQuery.ts
frontend/kesaseteli/shared/browser-tests/handler-form-page/handlerFormPage.components.ts
frontend/kesaseteli/shared/src/__tests__/utils/fake-objects.ts
frontend/kesaseteli/shared/src/backend-api/backend-api.ts
frontend/kesaseteli/shared/src/constants/status-constants.ts
frontend/kesaseteli/shared/src/types/created-youth-application.d.ts
frontend/kesaseteli/shared/src/types/youth-application-status.d.ts
frontend/kesaseteli/youth/browser-tests/youth-application.testcafe.ts

Accept and Reject -button to handler-ui. Backend is not yeat implemented but ui functionality is already done. Component tests shows that it works correctly. After backend is done, browser tests for accepting/rejecting should be added.

YJDH-448/YJDH-453: Accept and Reject -button to handler-ui

---

backend/benefit/calculator/rules.py
backend/benefit/calculator/tests/test_models.py

state_aid_max_percentage is not needed to calculate employment_benefit, so don't require it
backend/benefit/calculator/tests/test_models.py:test_calculation_required_fields

HL-488: state_aid_max_percentage not required for employment_benefit

---

backend/benefit/applications/api/v1/views.py
backend/benefit/applications/models.py
backend/benefit/applications/tests/test_application_batch_api.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/calculator/tests/test_calculator_api.py
backend/benefit/common/permissions.py
backend/benefit/messages/tests/test_api.py
backend/benefit/messages/views.py
backend/benefit/requirements.in
backend/benefit/requirements.txt
backend/benefit/terms/api/v1/views.py

Also
* Deny handler's access to applicant applications API
* Fix tests where handler was accessing draft applications
or using the applicant API
* Force the rest framework to use English error messages in tests

HL-449: hide draft applications from handler API

---

backend/tet/tet/urls.py

Include Django admin urls only when ENABLE_ADMIN is set

---

backend/benefit/companies/tests/conftest.py
backend/benefit/companies/tests/test_api.py
backend/kesaseteli/companies/tests/test_company_api.py
backend/shared/shared/azure_adfs/tests/test_adfs_login.py
backend/shared/shared/oidc/tests/test_auth_backend.py
backend/shared/shared/oidc/tests/test_eauth_views.py
backend/shared/shared/oidc/tests/test_oidc_views.py

GitHub Code Scanning / CodeQL found "Incomplete regular expression for
hostnames" problems in code in develop to main branch merging on
7th of March, 2022, for an example:
- "This regular expression has an unescaped '.' before 'microsoft.com',
so it might match more hosts than expected."
Fix uses of re.compile in tests with string literals by escaping the
input i.e. by changing re.compile(text) to re.compile(re.escape(text)).
`-`

Backends: Escape string literals in tests' regular expressions

---

backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/common/tests/test_utils.py
backend/kesaseteli/common/utils.py

Add tests:
- test_youth_application_activation_email_sending
- test_youth_summer_voucher_email_language
- test_youth_summer_voucher_email_sending
- test_youth_summer_voucher_email_type
- test_youth_summer_voucher_email_plaintext_html_similarity
- test_youth_applications_accept_acceptable_with_invalid_smtp_server
- test_youth_applications_handle_handled
- test_youth_applications_accept_accepted merged into this
- test_youth_applications_reject_rejected merged into this
Add testing of the email sender and recipients for activation,
processing and youth summer voucher emails.
Add normalize_whitespace utility function and test for it.
YJDH-501

YJDH-501 | KS-Backend: Add more youth summer voucher tests

---

backend/tet/tet/settings.py

TET backend tries to read user's name from ADFS claim. If givenName or familyName is empty, it will produce the following warning but no error: `Claim 'givenName' for user field 'first_name' was not found in the access token for user '6928cf58-4791-480c-b848-1272de20c124'. Field is not required and will be left empty`

TET: add ADFS claims givenName and familyName

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/tests/test_applications_api.py

Application.batch field needs to be set to null when moving back to handling
backend/benefit/applications/tests/test_applications_api.py:test_application_with_batch_back_to_handling

HL-478: remove application from batch when moving back to handling

---

backend/kesaseteli/applications/api/v1/serializers.py
backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py

The added endpoint:
- URL: `/v1/youthapplications/<pk>/status/`
- Access control: None, so this is a public endpoint
- Output: {"status": "<youth application's status>"}
Add YouthApplicationStatusSerializer for serializing only the youth
application's status.
Add tests for status endpoint:
- test_youth_applications_public_action_unused_pk
- Combine test_youth_applications_activate_unused_pk into this
- test_youth_applications_status_valid_pk
YJDH-497

YJDH-497 | KS-Backend: Add youth application status endpoint

---

backend/benefit/helsinkibenefit/settings.py

[mikkovihonen](https://app.slack.com/team/U017Z6SEH70) [Mar 17th at 3:11 PM]
@here Does anyone have any clue why csrftoken would be set two times, first for .[hel.fi](http://hel.fi/) domain and the latter for .[arodevtest.hel.fi](http://arodevtest.hel.fi/)? We noticed that two csrftokens on a call will cause an error which will disappear once the “wrong” csrftoken expires. I witnessed this yesterday in Kesäseteli and today in TET project.

HL-514: change CSRF_COOKIE_NAME to avoid conflict with Tunnistamo

---

frontend/benefit/applicant/src/components/applications/forms/application/step2/ApplicationFormStep2.tsx

Fix applicant form step 2 so that error for no available benefit types is shown only when user has chosen no for paySubsidyGranted

Fix showing error for no available benefit types

---

backend/benefit/applications/services/applications_csv_report.py
backend/benefit/applications/services/csv_export_base.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_applications_csv_report.py
backend/benefit/setup.cfg
backend/shared/precommit-setup.cfg

* Add columns for "Siirrettävä ahjo-rivi" for easier processing
* Finnish texts in colunns "Haettava lisä" and "Työnantajan tyyppi"
* move "Hyväksymisen/hylkäyksen/peruutuksen syy" to a more logical place
backend/benefit/applications/tests/test_applications_csv_report.py

HL-501: ahjo csv export formatting changes

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/api/v1/views.py
backend/benefit/applications/models.py
backend/benefit/applications/tests/test_applications_api.py

* Add to include/exclude fields in the application
* Add separate endpoint to download a simplified application listing,
with only the fields normally needed for application list UIs
* Optimize various SQL queries
* Remove the unused ApplicationBasisSerializer, as it was creating unnecessary queries
backend/benefit/applications/tests/test_applications_api.py:test_applications_simple_*

HL-467: performance improvements for application listing

---

backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/enums.py
backend/kesaseteli/applications/locale/en/LC_MESSAGES/django.po
backend/kesaseteli/applications/locale/fi/LC_MESSAGES/django.po
backend/kesaseteli/applications/locale/sv/LC_MESSAGES/django.po
backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/tests/test_misc.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/common/tests/factories.py
backend/shared/shared/common/tests/test_utils.py
backend/shared/shared/common/utils.py

Changes to YouthApplicationViewSet:
- activate action i.e. activating a submitted youth application:
- If an active youth application already exists then:
- If the youth application to be activated is already active and it
initially needs additional info then redirect to frontend's
additional info page
- If the youth application to be activated is not the already
activated one or it does not initially need additional info then
then redirect to already activated page i.e. as was done before
this commit
- If activated an inactive youth application then:
- If additional info is needed then set youth application's status
to "additional_information_requested" and redirect to frontend's
additional info page. Otherwise do as before.
- create action i.e. submitting a new youth application:
- If …

YJDH-509 | KS-Backend: Send additional info request email

---

backend/benefit/messages/serializers.py
backend/benefit/messages/tests/test_api.py

Applicant is allowed to send messages in received, handling
and additional_information_needed statuses.
Applicant needs to be able to send and read messages when application is received, in handling or reopened for more information.
Applicant can be the one to send the first message.
backend/benefit/messages/tests/test_api.py

HL-511: allow applicant to send first message

---

backend/benefit/terms/tests/test_terms_of_service_api.py
backend/benefit/users/api/v1/serializers.py

The response from server contained local fs paths

HL-523: fix missing URLs in terms_of_service_in_effect

---

docker-compose.benefit.yml

Use Finnish locale for the Postgres instance used for local development

Use Finnish locale in postgres in local development

---

backend/kesaseteli/applications/tests/test_models.py

Enable use of transactions and reset sequences in all tests in
test_models.py. Previously the "with transaction.atomic()" clauses in
these tests did nothing besides having the code wrapped in a with clause
because the related default parameters to pytest.mark.django_db are:
- transaction=False
- "With transaction=False (the default when not specified),
transaction operations are noops during the test."
- reset_sequences=False
- "The reset_sequences argument will ask to reset auto increment
sequence values (e.g. primary keys) before running the test.
Defaults to False. Must be used together with transaction=True to
have an effect."
`–`

KS-Backend: Use transactions in test_models.py tests

---

frontend/Dockerfile

When running TET project locally Docker Compose has been crashing often due to `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`.

Increase V8 max heap size in development

---

backend/benefit/calculator/models.py
backend/benefit/calculator/tests/test_models.py

The amount of benefit was not rounded
backend/benefit/calculator/tests/test_models.py

HL-544: Round the amount of employment benefit to full euros

---

backend/benefit/applications/services/applications_csv_report.py
backend/benefit/applications/tests/test_applications_csv_report.py
backend/benefit/calculator/admin.py
backend/benefit/calculator/rules.py
backend/benefit/calculator/tests/test_manual_override.py

Also fix translation for association_has_business_activities
In some cases, the start_date and end_date were missing in Ahjo rows
backend/benefit/applications/services/applications_csv_report.py
backend/benefit/applications/tests/test_applications_csv_report.py

HL-501: Fix start_date, end_date in new Ahjo "current row" columns

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/api/v1/views.py
backend/benefit/applications/models.py
backend/benefit/applications/tests/test_applications_api.py

Also:
* move perform_update to BaseApplicationViewSet in order to avoid
issues with stale submitted_at values
* remove dead code from ApplicationManager
The default ordering in the handling views:
* In the "received" table, ordering should be by the send time, most recent first
* In the "handling" table, ordering should be by the calculation modification time, most recent first
* In the archive page, ordering should be by handled_at, most recent first.
All these goals are achieved by ordering by first handled_at, then
modified_at.
* in the "received" and "handling" table, no application has handled_at set yet,
so applications will compare as equals
* For received applications, the send time is the same as application modification time

HL-484: set default sorting of applications in the handler UI

---

backend/benefit/.prod/on_deploy.sh
backend/benefit/README.md
backend/benefit/docker-entrypoint.sh
backend/benefit/helsinkibenefit/settings.py
backend/benefit/users/admin.py
backend/benefit/users/fixtures/groups.json
backend/benefit/users/management/commands/set_group_permissions.py
backend/shared/shared/azure_adfs/auth.py
backend/shared/shared/azure_adfs/tests/test_adfs_login.py

Handlers need (rarely) to be able to edit the terms of service and applicant terms in the django admin.
Use a shortcut in ModelAdmin so that permissions don't need to be assigned for every new handler.

HL-545: allow handlers to access terms in django admin

---

.env.benefit-backend.example
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/common/tests/conftest.py
backend/benefit/helsinkibenefit/settings.py
backend/benefit/locale/en/LC_MESSAGES/django.po
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/sv/LC_MESSAGES/django.po
backend/benefit/messages/automatic_messages.py
backend/benefit/messages/tests/test_api.py
backend/benefit/messages/views.py
backend/benefit/requirements-dev.in
backend/benefit/requirements-dev.txt
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/shared/shared/common/lang_test_utils.py

Email sending is implemented in the same way as in Kesäseteli
Report email sending errors to Sentry so that the errors can be reported further to the handlers. Error while sending email should not block sending messages.
backend/benefit/messages/tests/test_api.py

HL-387: send email notification to applicant about new messages

---

backend/kesaseteli/applications/enums.py
backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/tests/test_applications_api.py
backend/kesaseteli/applications/tests/test_models.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/common/tests/conftest.py
backend/kesaseteli/common/tests/factories.py
backend/kesaseteli/common/tests/test_factories.py

Tests in test_models.py:
- Use AwaitingManualProcessingYouthApplicationFactory instead of
AcceptedYouthApplicationFactory because the former factory generates
youth applications without youth summer vouchers now but the latter
generates youth applications with youth summer vouchers. These tests
need youth applications without youth summer vouchers.
YouthApplicationStatus:
- Add active_unhandled_values function
- Active youth application statuses which have not been handled.
- Add unhandled_values function
- Youth application statuses which have not been handled.
Expose email subject functions for testing by removing underscore
prefixes from the function names:
- YouthApplication._processing_email_subject
- YouthSummerVoucher._email_subject
Tests in test_youth_applications_api.py:
- Move …

YJDH-515 | KS-Backend: Add more additional info related tests

---

backend/benefit/helsinkibenefit/settings.py
backend/kesaseteli/kesaseteli/settings.py
backend/tet/tet/settings.py
frontend/kesaseteli/shared/src/query-client/create-query-client.ts
frontend/shared/src/backend-api/BackendAPIProvider.tsx
frontend/tet/admin/src/query-client/create-query-client.ts

Change CSRF_COOKIE_NAME to yjdhcsrftoken in all YJDH projects

HL-506, YJDH-514, TETP-158: change CSRF_COOKIE_NAME to yjdhcsrftoken

---

frontend/tet/shared/package.json

The production build was failing with error message`ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom' in '/app/node_modules/next/dist/client'` due to this.

Update tet-shared to React 18

---

backend/tet/events/api/v1/permissions.py
backend/tet/events/api/v1/views.py
backend/tet/events/linkedevents.py
backend/tet/events/services.py
backend/tet/events/tests/data/linked_events_responses.py
backend/tet/events/tests/test_services.py
backend/tet/events/transformations.py
backend/tet/events/utils.py
backend/tet/tet/views.py

The purpose of this PR is that login from path `/oidc/authenticate` logs in a "company user" (suomi.fi puolesta asiointi) instead of city of Helsinki user (login via /oauth2/authenticate). We can currently test when the logins are mocked (localhost or review environment). Setup for testing suomi.fi login is still underway by Helsinki profiili.

TETP-208: Add support for mocked suomi.fi authentication

---

backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py

PR #1094 was incomplete, it only disregarded rejected youth applications
in youth application creation. This commit adds disregarding of
rejected youth applications in activation. This should now allow a
person to submit a new youth application and have it accepted even if
they have a previously rejected youth application.
Add test cases for activation where a rejected youth application for the
same person using the same email already exists. All rejected youth
applications should be ignored in activation.
Refs YJDH-532 (Disregarding rejected youth applications)
Refs PR #1094 (Disregarding rejected youth applications on creation)
YJDH-532
PR #1094

YJDH-532 | KS-Backend: Ignore rejected youth applications in activation

---

backend/kesaseteli/applications/tests/test_schools_api.py
backend/kesaseteli/common/tests/conftest.py

Add school_list fixture which populates the School model and use it in
school list related tests.
This way the school list related tests aren't dependent on the data
migrations having populated the school list.
YJDH-569

YJDH-569 | KS-Backend: Add and use school_list test fixture

---

frontend/shared/src/components/stepper/WizardStepper.sc.ts
frontend/shared/src/components/stepper/WizardStepper.tsx

At some point wizard step styles have been messed up. Previous it looked like this:
Now it looks like this:
HL-benefit uses same stepper and it's still looking ok:

YJDH-564: fix wizard step styles

---

backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/tests/test_models.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/common/utils.py

Send a hidden copy (bcc) of the youth summer voucher to the handler email. This will enable the handlers to deal with possible problems the users are having e.g. handlers are able to re-send a lost voucher to a user.

YJDH-581 YJDH-582 | Send copy of the youth summer voucher to handlers

---

backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py

When `DISABLE_VTJ` is enabled, accepting or rejecting a `YouthApplication` will not expect any input for the `encrypted_handler_vtj_json` field and will store `None` to the field.

YJDH-594 | Fix YouthApplication accept/reject when DISABLE_VTJ is enabled

---

backend/kesaseteli/requirements-dev.txt

This bumps all kesaseteli related development requirements while respecting the versions set in pre-commit.

KS backend: Bump development requirements

---

backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py

When `DISABLE_VTJ` is set the logic now also checks if additional information is required for the application. `YouthApplication.need_additional_info` will require additional info when an unlisted school is selected if VTJ is disabled.

YJDH-595 | Additional DISABLE_VTJ fixes

---

backend/kesaseteli/kesaseteli/settings.py

To be able to pass test/use cases required for production the following fixes are needed to get Suomi.fi to work.
- https://palveluhallinta.suomi.fi/fi/sivut/tunnistus/kayttoonotto/kayttoonoton-vaiheet
YJDH-574 Suomi.fi integration

YJDH-574 | Suomi.fi authentication logout fixes

---

frontend/tet/admin/src/pages/login.tsx

Do not set the title explicitly for login page.

TETP-256: Fix login page title

---

backend/kesaseteli/applications/api/v1/serializers.py
backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/exporters/excel_exporter.py
backend/kesaseteli/applications/tests/test_excel_export.py
backend/kesaseteli/applications/tests/test_models.py
backend/kesaseteli/applications/views.py
backend/kesaseteli/common/tests/factories.py

Add following fields to be exported in Talpa Excel export:
- Liite: Työsopimus 1
- Liite: Työsopimus 2
- Liite: Työsopimus 3
- Liite: Työsopimus 4
- Liite: Työsopimus 5
- Liite: Palkkalaskelma 1
- Liite: Palkkalaskelma 2
- Liite: Palkkalaskelma 3
- Liite: Palkkalaskelma 4
- Liite: Palkkalaskelma 5
"Työsopimus" means an employment contract, first 5 of them are exported.
"Palkkalaskelma" means a payslip, first 5 of them are exported.
Refs YJDH-618
Remove unused import and run "black . && isort . && flake8" without
warnings.
Refs YJDH-618 (Noticed these hadn't been run)
Fix Excel export tests by not using mock flag, checking for correct
redirection URL and removing ENABLE_ADMIN checks that didn't for an
unknown reason work.
Add attachment export testing to Excel export tests.
Test that Excel …

YJDH-618 | Export attachments in Talpa Excel export

---

backend/kesaseteli/applications/exporters/excel_exporter.py
backend/kesaseteli/applications/tests/test_excel_export.py

Add the following contact info fields to reporting Excel export:
- "Yhdyshenkilön sähköposti" i.e. contact person's email
- "Yhdyshenkilön Puhelin" i.e. contact person's phone number
- "Laskuttajan sähköposti" i.e. invoicer's email
- "Laskuttajan Puhelin" i.e. invoicer's phone number
Fix test_excel_view_download_content test:
- Handle special case of invoicer related fields when separate invoicer
is not used
Add new Excel export related tests:
- test_removable_reporting_field_titles
- Test that values in REMOVABLE_REPORTING_FIELD_TITLES are unique
- Test that REMOVABLE_REPORTING_FIELD_TITLES is a subset of FIELDS
- test_removable_talpa_field_titles
- Test that values in REMOVABLE_TALPA_FIELD_TITLES are unique
- Test that REMOVABLE_TALPA_FIELD_TITLES is a subset of FIELDS
YJDH-626

YJDH-626 | KS-Backend: Add contact info to reporting Excel export

---

backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/common/tests/factories.py

Add more activate unexpired inactive youth application tests:
- Remove test:
- test_youth_applications_activate_unexpired_inactive
- Add tests:
- test_youth_applications_activate_unexpired_inactive_with_rejection
- test_youth_applications_activate_unexpired_inactive__vtj_enabled
- test_youth_applications_activate_unexpired_inactive__vtj_disabled
Now the automatic acceptance of youth applications on their activation
is tested with both VTJ integration disabled and enabled.
Also add helper function get_random_social_security_number_for_year and
a comment to function determine_target_group_social_security_number
about the generated social security numbers' year.
YJDH-542

YJDH-542 | KS-Backend: Add more activate unexpired inactive tests

---

backend/kesaseteli/applications/tests/test_excel_export.py
backend/kesaseteli/applications/views.py

Use a FileResponse in EmployerApplicationExcelDownloadView in order to
avoid getting a Gateway Timeout 504 error if the Excel export takes too
long.
EmployerApplicationExcelDownloadView:
- Select and prefetch related objects in Excel export to hopefully
speed up the query.
EmployerApplicationExcelDownloadView:
- Move shared query part from export_and_download_annual_applications
and export_and_download_unhandled_applications to base_queryset
[YJDH-642](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-642) ("BE: Kesäsetelin tämän vuoden hakemusten Talpa-Excelin lataaminen epäonnistuu yhdyskäytävän aikakatkaisuun")
Similar to the fix in https://github.com/City-of-Helsinki/yjdh/pull/1118

YJDH-642 | KS-Backend: Fix annual Talpa Excel export

---

.env.kesaseteli.example
backend/kesaseteli/applications/exporters/excel_exporter.py
backend/kesaseteli/applications/tests/test_excel_export.py
backend/kesaseteli/applications/tests/test_models.py
backend/kesaseteli/applications/views.py
backend/kesaseteli/common/tests/factories.py
backend/kesaseteli/kesaseteli/settings.py
backend/kesaseteli/requirements.in
backend/kesaseteli/requirements.txt
backend/shared/shared/common/tests/factories.py

Refs YJDH-645 (The package to be used for streaming .xlsx files)
Refs YJDH-642 (The bug this fix is related to)
Refs YJDH-645 (A fix for YJDH-642)
- Add type hints to some of the functions in excel_exporter.py.
- Configure Excel download batch size in Excel exporting with setting
EXCEL_DOWNLOAD_BATCH_SIZE and default value of 50.
- Add comment to generate_xlsx_template function in excel_exporter.py.
Refs YJDH-645
EmployerApplicationExcelDownloadView:
- Use triplet (submitted_at, created_at, pk) as the sorting key for the
Excel download's queryset. Use the same triplet in the queryset's
order_by clause and the RowNumber window function annotation's
order_by clause to make the row numbers work correctly. Using
created_at and primary key as the secondary and tertiary ordering
parameters to …

YJDH-645 | KS-Backend: Stream Excel export

---

backend/benefit/applications/tests/test_application_batch_api.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/calculator/tests/test_previous_benefits_api.py
backend/benefit/common/tests/conftest.py
backend/benefit/companies/tests/test_api.py
backend/benefit/helsinkibenefit/tests/conftest.py
backend/benefit/messages/tests/test_api.py
backend/benefit/pyproject.toml
backend/benefit/setup.cfg
backend/benefit/terms/tests/test_terms_of_service_api.py

Combine force_settings and setup_test_environment autouse fixtures into
the latter and add following settings to it:
- settings.DISABLE_TOS_APPROVAL_CHECK = False
- settings.NEXT_PUBLIC_MOCK_FLAG = False
Remove all now unnecessary uses of:
- @override_settings(NEXT_PUBLIC_MOCK_FLAG=False)
- @override_settings(DISABLE_TOS_APPROVAL_CHECK=False)
Refs HL-566
Add pyproject.toml to configure black because black AFAIK can not be
configured using setup.cfg at the moment.
Exclude the following directories in black/coverage/flake8/pep8/pytest:
- .pytest_cache
- var/media
This speeds up
- "black . && isort . && flake8" from minutes to ~10 seconds
- "pytest . --collect-only" from minutes to ~6 seconds
in Docker on Windows 10 using Docker Desktop and WSL 2. I saw around
100k files in /app/var/media …

HL-566 | Force pytest settings

---

backend/benefit/applications/api/v1/views.py
backend/benefit/applications/enums.py
backend/benefit/applications/tests/test_application_status.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/calculator/api/v1/serializers.py
backend/benefit/calculator/tests/test_calculator_api.py
backend/benefit/locale/en/LC_MESSAGES/django.po
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/sv/LC_MESSAGES/django.po
backend/benefit/users/api/v1/serializers.py
backend/shared/shared/common/tests/test_mock_enabled_proxy_view.py
backend/shared/shared/common/views.py
backend/shared/shared/oidc/tests/test_mock_views.py
backend/shared/shared/oidc/urls.py
backend/shared/shared/oidc/views/mock_views.py

Add settings to control OIDC mock user's is_staff & is_superuser values:
- settings.OIDC_MOCK_USER_IS_STAFF -> OIDC mock user's is_staff
- If the setting is not set at all then will default to False
- settings.OIDC_MOCK_USER_IS_SUPERUSER -> OIDC mock user's is_superuser
- If the setting is not set at all then will default to False
The OIDC mock user is created by MockAuthenticationRequestView which is
mapped to oidc's authenticate endpoint
(See backend/shared/shared/oidc/urls.py) if NEXT_PUBLIC_MOCK_FLAG is set
Refs HL-566
BaseApplicationViewSet.get_queryset:
- Refactor logical structure for readability, should not change effect
ApplicationStatus.is_editable_status:
- Previously NEXT_PUBLIC_MOCK_FLAG allowed to edit all statuses. Now
NEXT_PUBLIC_MOCK_FLAG allows to edit both handler's and …

HL-553, HL-566 | Update mock flag related permission handling & fix moving application to handling

---

backend/benefit/applications/tests/factories.py
backend/benefit/calculator/api/v1/serializers.py
backend/benefit/calculator/models.py
backend/benefit/calculator/tests/test_calculator_api.py

Tests:
- Add new tests
- test_pay_subsidies_validation_in_handling
- Test that pay subsidies' validation works as expected for
applications in handling
- Fix existing tests
- test_application_edit_pay_subsidy_invalid_values
- test_validate_pay_subsidy_dates_when_application_is_handled
HL-553

HL-553 | Restrict pay subsidies' date validation to salary benefits

---

.env.benefit-backend.example
backend/benefit/helsinkibenefit/settings.py

Change the URLs for YRTTI and YTJ Palveluväylä test integrations:
- https://yrtti-integration-dev.agw.arodevtest.hel.fi/api/BasicInfo → https://yrtti-integration-test.agw.arodevtest.hel.fi/api/BasicInfo
- https://ytj-integration-dev.agw.arodevtest.hel.fi/api/GetCompany → https://ytj-integration-test.agw.arodevtest.hel.fi/api/GetCompany
HL-581

HL-581 | HL-Backend: Fix URLs for YRTTI and YTJ Palveluväylä test integrations

---

backend/tet/tet/views.py

Give a reasonable fallback when GDPR data has been removed
HL-587

HL-587 | TET-Backend: Use organization name as a fallback for showing user name

---

backend/benefit/setup.cfg
backend/kesaseteli/applications/api/v1/serializers.py
backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/templates/application_excel_download.html
backend/kesaseteli/applications/tests/conftest.py
backend/kesaseteli/applications/tests/test_excel_export.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/applications/views.py
backend/kesaseteli/common/tests/factories.py
backend/kesaseteli/kesaseteli/urls.py
backend/kesaseteli/pyproject.toml
backend/kesaseteli/setup.cfg
backend/shared/precommit-setup.cfg
backend/shared/setup.cfg
backend/shared/shared/audit_log/viewsets.py
backend/tet/pyproject.toml
backend/tet/setup.cfg

Add new tests:
- test_youth_excel_download_no_youth_applications
- test_youth_excel_download_writes_audit_log
- test_youth_excel_download_content
Add parametrization to extisting test:
- test_excel_view_download_with_unauthenticated_user
Also:
- Disable VTJ in test_youth_applications_detail_valid_pk test to fix
the test case
- Add audit log support for list function in AuditLoggingModelViewSet
- AuditLoggingModelViewSet inherits ModelViewSet which inherits
ListModelMixin which has a list function so it makes sense to add
an audit log entry also for list calls
Refs YJDH-651
Similar to change in b1084fb. Should
speed up running "black . && isort . && flake8" because of excluding
e.g. var/media also in the kesaseteli backend.
Now:
- Identical pyproject.toml files for configuring black …

YJDH-651 | KS-Backend: Add Excel export for confirmed youth summer applications

---

backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/tests/test_models.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py

Places affected:
- YouthApplicationViewSet.activate and tests:
- test_youth_applications_activate_expired_active
- test_youth_applications_activate_expired_inactive
- test_youth_applications_activate_unexpired_active
- test_youth_applications_activate_unexpired_inactive__vtj_disabled
- test_youth_applications_activate_unexpired_inactive__vtj_enabled
- YouthApplicationViewSet.create and tests:
- test_youth_application_post_success
- test_youth_application_post_rejection
Add support to tests:
- test_youth_applications_accept_acceptable__vtj_disabled
- test_youth_applications_accept_acceptable
Also:
- Simplify test_youth_applications_adfs_login_enforced_action_unused_pk
parametrizations by removing needless reduce function use
- Add youth summer voucher serial number sequence related …

YJDH-516 | KS-Backend: Allow same person to get summer voucher on different years

---

backend/benefit/helsinkibenefit/settings.py
backend/kesaseteli/kesaseteli/settings.py
backend/tet/tet/settings.py

Looks like we use too strict logger level on django settings, now it's downgraded to "INFO" level to see for example
scheduled cron job loggings on kibana. See: https://medium.com/@soroush_safarii/django-log-management-with-elastic-and-kibana-440ab7e2e457

chore: use INFO level logger on yjdh backends

---

frontend/kesaseteli/employer/src/hooks/backend/useUserQuery.ts
frontend/kesaseteli/handler/src/hooks/backend/useCompleteYouthApplicationQuery.ts
frontend/kesaseteli/handler/src/hooks/backend/useYouthApplicationQuery.ts
frontend/kesaseteli/youth/src/hooks/backend/useCreateAdditionalInfoQuery.ts
frontend/kesaseteli/youth/src/hooks/backend/useSchoolListQuery.ts
frontend/kesaseteli/youth/src/hooks/backend/useYouthApplicationStatusQuery.ts
frontend/kesaseteli/youth/src/hooks/useHandleYouthApplicationSubmit.ts
frontend/shared/src/components/forms/buttons/SaveFormButton.tsx
frontend/shared/src/error-handler/error-handler.ts
frontend/shared/src/hooks/useErrorHandler.ts
frontend/tet/admin/src/hooks/backend/useUserQuery.ts
frontend/tet/admin/src/pages/login.tsx

Let's detect with next/router when user is on login page. In this case always redirect to login error page instead of 500 page.
This is a change to shared code so it will change the functionality in all frontend services.

feat(hl-573): fix redirecting loop when server error

---

frontend/kesaseteli/employer/src/hooks/backend/useUserQuery.ts
frontend/shared/src/error-handler/error-handler.ts
frontend/shared/src/hooks/useErrorHandler.ts
frontend/tet/admin/src/hooks/backend/useUserQuery.ts

Second try to fix the endless error page loop when unauthenticated. 
Now resolution is not to move 500 page when user query throws server error but go to login error page instead

feat(hl-573): route to login error page on userquery error

---

backend/shared/shared/azure_adfs/README.md
backend/shared/shared/azure_adfs/auth.py
backend/shared/shared/azure_adfs/tests/test_adfs_login.py
backend/tet/tet/views.py

Create "ADFS login" group and add the user to it when logging in using
HelsinkiAdfsAuthCodeBackend. This determines whether user was logged in
using ADFS at some point or not. Use this in TET's UserInfoView to set
return value is_adfs_login.
Return Forbidden 403 HTTP error in TET's UserInfoView if user was logged
in using ADFS at some point but did not qualify as a handler at last
ADFS login.
Add documentation about azure_adfs's optional Django settings:
- HANDLERS_GROUP_NAME:
- This group's membership signifies that user qualified as a
handler at last ADFS login.
- If set and a user group by this name exists then will be added to
the logged in user's groups if the user qualifies as a handler or
removed if the user does not.
- ADFS_LOGIN_GROUP_NAME:
- This group's membership signifies …

HL-573 | Shared/TET backend: Determine ADFS login with "ADFS login" group

---

frontend/package.json
frontend/tet/admin/src/components/editor/Editor.tsx
frontend/yarn.lock

For some reason nextjs complains about the devtools when it should not even be rendered in production mode. Thus removed. Not sure why it started to complain about it now as it's been in the code for a long time

feat(hl-599): remove devtools from production

---

frontend/next.config.js
frontend/shared/src/components/app/BaseApp.tsx

I noticed some mistakes in sentry configuration:
- stacktrace was still disabled
- sample rate was not necessary 100% meaning that not all the messages get through

HL-576: Enable sentry stacktrace + fix sample rate to be always 100%

---

backend/benefit/requirements-dev.in
backend/benefit/requirements.in
backend/kesaseteli/requirements-dev.in
backend/kesaseteli/requirements.in
backend/tet/events/tests/test_gdpr_api.py
backend/tet/requirements-dev.in
backend/tet/requirements-dev.txt
backend/tet/requirements.in
backend/tet/requirements.txt
backend/tet/tet/settings.py
backend/tet/tet/urls.py
backend/tet/tet/views.py

Normalize package names to all lowercase letters in requirements*.in
which should be safe because PEP 428 at
https://peps.python.org/pep-0426/#name says:
- "All comparisons of distribution names MUST be case insensitive"
Sort the package names in requirements*.in to ascending order.
Afterwards ran:
- pip-compile requirements.in
- pip-compile requirements-dev.in
- pip-compile requirements-prod.in
but the requirements*.txt files remained unchanged for all backends.
Refs HL-600 (Looked at requirements*.in when implementing this ticket)
Afterwards ran:
- pip-compile requirements.in
- pip-compile requirements-dev.in
- pip-compile requirements-prod.in
Refs HL-600
Examples of endpoints:
- GET & DELETE: /gdpr-api/v1/user/60404d9b-9e75-43be-bdb4-aae6a1a2f9f6
- 60404d9b-9e75-43be-bdb4-aae6a1a2f9f6 …

HL-600 | Add TET GDPR API

---

backend/tet/requirements.in
backend/tet/requirements.txt

drf-oidc-auth was too new, with the newer version got:
django-helusers/ApiTokenAuthentication.authenticate: self.validate_claims(payload)
->
drf-oidc-auth/JSONWebTokenAuthentication.validate_claims: id_token.validate(
->
authlib/IDToken.validate:
self.validate_amr()
->
authlib/IDToken.validate_amr
->
authlib/InvalidClaimError:
description = 'Invalid claim "{}"'.format(claim)
->
"Invalid claim "amr"
When "amr" was in the decoded JWT token:
- 'amr': 'heltunnistussuomifi'
The "amr" claim was truthy but wasn't a list which caused the 'Invalid claim "amr"' error message from authlib.
Refs HL-600
HL-600

HL-600 | TET-Backend: Use drf-oidc-auth 0.10.0 to make GDPR API work

---

backend/tet/tet/views.py

TET-Backend: Return empty dictionary as JSON in TetGDPRAPIView.get
HL-600

HL-600 | TET-Backend: Return empty dictionary as JSON in TetGDPRAPIView.get

---

backend/shared/shared/oidc/mixins.py
backend/tet/requirements.in
backend/tet/requirements.txt
backend/tet/tet/views.py

This PR is about production release GDPR API related fixes, see
- https://github.com/City-of-Helsinki/yjdh/pull/1635#discussion_r1055169944
- https://github.com/City-of-Helsinki/yjdh/pull/1645#issuecomment-1362609931
- https://github.com/City-of-Helsinki/yjdh/pull/1647#discussion_r1055451993
- https://github.com/City-of-Helsinki/yjdh/pull/1647#discussion_r1055457539
The changes are:
Remove debug logging from TetGDPRAPIView.
Remove drf-oidc-auth version binding to 0.10.0 and update requirements:
- Removed rows from requirements.in:
- django-helusers
- drf-oidc-auth==0.10.0
- Ran pip-compile on requirements*.in
- Added rows to requirements.in:
- django-helusers
- drf-oidc-auth
- Ran pip-compile on requirements*.in
Refs HL-600
Copied FixTunnistamoMixin from palvelutarjotin …

HL-600 | TET-Backend: Production release GDPR API related fixes

---

localdevelopment/benefit/nginx/Dockerfile

Achieve a smaller docker fingerprint by switching to alpine-slim instead of the default distro.

HL-607 | Use alpine-slim image instead of a default one

---

localdevelopment/benefit/nginx/nginx.conf
localdevelopment/employer/nginx/nginx.conf
localdevelopment/handler/nginx/nginx.conf
localdevelopment/tet-admin/nginx/nginx.conf
localdevelopment/tet-youth/nginx/nginx.conf
localdevelopment/tet/nginx/nginx.conf
localdevelopment/youth/nginx/nginx.conf

Currently, HTTP requests to frontend only show NGINX default error (code 400, Bad Request).
For developer convenience, redirect all requests from HTTP to HTTPS:
* http://localhost:3000
* http://localhost:3001
* http://localhost:3002
* http://localhost:3100
* http://localhost:3200

HL-611 | Redirect requests for http://localhost to HTTPS on ports 3000+

---

frontend/benefit/handler/src/components/applicationList/useApplicationList.ts
frontend/benefit/handler/src/components/applicationsArchive/useApplicationsArchive.ts

Hard refresh on:
* https://localhost:3100/
* https://localhost:3100/archive
caused an hydration error.
SSR does not have the LoadingSkeletor component rendered. This invoked the hydration error. Just show this component  and all is well 🎉 
https://helsinkisolutionoffice.atlassian.net/browse/HL-592
[HL-592]: https://helsinkisolutionoffice.atlassian.net/browse/HL-592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HL-592 | Fix hydration issue on handler's application index and archive page

---

frontend/benefit/applicant/src/components/pdfViewer/PdfViewer.tsx

Whole test case would hang in it's first action.
https://helsinkisolutionoffice.atlassian.net/browse/HL-608
CDN causing trouble, TestCafé won't be able to download the file. Just load the file while in production.
```
1) A JavaScript error occurred on "https://localhost:3000/".
Repeat test actions in the browser and check the console for errors.
To ignore client-side JavaScript errors, enable the "--skip-js-errors" CLI option, or set the "skipJsErrors" configuration file property to "true".
If the website only throws this error when you test it with TestCafe, please create a new issue at:
"https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
JavaScript error details:
Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at …
```

HL-608 | Fix broken TestCafé run, issue with loading CDN content from test proxy

---

backend/benefit/applications/tests/test_ahjo_integration.py
backend/kesaseteli/applications/tests/test_models.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/kesaseteli/common/tests/factories.py
backend/kesaseteli/common/tests/faker.py
backend/kesaseteli/common/tests/test_factories.py
backend/kesaseteli/common/tests/test_utils.py
backend/kesaseteli/common/tests/utils.py
backend/kesaseteli/common/utils.py
backend/shared/shared/common/tests/test_utils.py
backend/shared/shared/common/tests/utils.py
backend/shared/shared/common/utils.py
backend/shared/shared/oidc/tests/test_auth_backend.py

Previously determine_target_group_social_security_number function
sometimes returned social security numbers for two different years.
When NEXT_PUBLIC_DISABLE_VTJ was set to True and
determine_target_group_social_security_number returned a social security
number with year difference of 17 from the current year rather than 16
it made YouthApplication.need_additional_info return True.
Now the determine_target_group_social_security_number only returns
social security numbers with a year difference of 16 from the current
year and AbstractYouthApplicationFactory based factories that expect a
certain need_additional_info value in their created object work with
both NEXT_PUBLIC_DISABLE_VTJ=False and NEXT_PUBLIC_DISABLE_VTJ=True.
Add test_need_additional_info test to test_factories.py to check …

YJDH-655 | Fix YouthApplication factories' need_additional_info

---

frontend/kesaseteli/employer/src/components/application/form/SelectionGroup.tsx
frontend/kesaseteli/employer/src/components/application/steps/step2/accordions/EmploymentAccordion.tsx

Affected selection groups in employer UI:
- target_group
- "Vuosiluokka tai syntymävuosi" in Finnish
- hired_without_voucher_assessment
- "Olisitko palkannut nuoren ilman kesäseteliä?" in Finnish
Previously the showTitle parameter to these selection groups was either false or not given at all and thus falsy. Thus their titles were not shown. Now the showTitle parameter is removed completely and the selection groups' titles are always shown.
YJDH-656

YJDH-656 | KS-Frontend: Always show titles in employer UI's selection groups

---

frontend/benefit/handler/src/components/footer/Footer.tsx

Fix HL handler's footer translation keys.

HL-616 | Fix keys for footer's copyright text translations

---

frontend/benefit/applicant/package.json
frontend/benefit/handler/package.json
frontend/benefit/shared/package.json
frontend/kesaseteli/employer/package.json
frontend/kesaseteli/handler/package.json
frontend/kesaseteli/youth/package.json
frontend/shared/package.json
frontend/tet/admin/package.json
frontend/tet/shared/package.json
frontend/tet/youth/package.json
frontend/yarn.lock

Upgrade all frontends to hds-react ^2.9.0. Should be working out of the box. @nenonja might want to check and refactor Kesäseteli's accordion.
For more details, see the [official migration guide](https://hds.hel.fi/getting-started/hds-2.0/migrating-to-2.0). 
Ticket:
https://helsinkisolutionoffice.atlassian.net/browse/HL-614

HL-614 | Bump all project's versions to use hds-react 2.10.0

---

frontend/benefit/handler/next-i18next.config.js
frontend/benefit/handler/src/components/header/Header.tsx

* Remove language selector from handler frontend (only FI will be used for now)
* Future proof language switch behaviour: register SV and EN to handler / nextjs so that switching won't crash the whole app

HL-613 | For handler, register EN and SV languages to nextjs but remove the language selector

---

.github/workflows/yarn-audit-scheduled.yml
frontend/audit-ci.json
frontend/audit-ci.jsonc
frontend/package.json
frontend/yarn.lock

`audit-ci` command didn't use a config file even though it was in place. This resulted in output without an error code and GH Action passed as completed. Now when the config is explicitly put in the workflow, action should report to Slack on any failure (that is, a critical level vulnerability on some package).
I've allowed for some packages that won't invoke a critical level failure. This is because these packages stem from `lerna` and `nextjs` that are on the @nenonja's workboard already and should be merged sooner or later (nextjs v12 and yarn v4 upgrade). Any additional critical vulnerabilities -- we should get the Slack alerts.
~You may have noticed that I've changed the alert level from **high** to **critical**. That's because there's so many of those errors, once again mostly from …

HL-604 | Audit-ci should fail if packages are on critical level of vulnerability

---

frontend/kesaseteli/employer/src/__tests__/application.test.tsx
frontend/kesaseteli/employer/src/__tests__/index.test.tsx
frontend/kesaseteli/employer/src/pages/application.tsx
frontend/kesaseteli/employer/src/pages/thankyou.tsx
frontend/kesaseteli/handler/src/__tests__/index.test.tsx
frontend/kesaseteli/youth/src/__tests__/additional_info.test.tsx
frontend/kesaseteli/youth/src/__tests__/email_in_use.test.tsx
frontend/kesaseteli/youth/src/__tests__/expired.test.tsx
frontend/kesaseteli/youth/src/__tests__/inadmissible_data.test.tsx
frontend/kesaseteli/youth/src/__tests__/index.test.tsx
frontend/kesaseteli/youth/src/__tests__/thankyou.test.tsx
frontend/shared/src/error-handler/error-handler.ts
frontend/shared/src/hooks/useErrorHandler.ts
frontend/shared/src/hooks/useGoToPage.ts
frontend/shared/src/types/go-to-page-function.d.ts
frontend/tet/admin/src/__tests__/copy.test.tsx
frontend/tet/admin/src/__tests__/edit.test.tsx
frontend/tet/admin/src/__tests__/index.test.tsx

To make sure error handler doesn't cause infinite loop, let's do the following:
- if we are already on login page and get auth error, do nothing (because on login page we are not authorized yet)
- if we are routing to the same path where we already are, use shallow route (to avoid unnecessary refresh)
- if we are routing to exact same path where we already are, do nothing (to avoid loop)

yjdh-657: fix endless loop on kesaseteli login page

---

backend/benefit/README.md
backend/benefit/applications/jobs/daily/daily_ application_jobs.py
backend/benefit/applications/management/commands/delete_cancelled.py
backend/benefit/applications/models.py
backend/benefit/applications/tests/test_application_tasks.py

This PR registers a Django command `python manage.py delete_cancelled` that deletes all applications (and their attachments) that have been in "cancelled"-state for 30 or more days. Also a daily Django job (via the Django extensions package) is registered to run the command and can be used to run other daily dasks (such as archiving) in the future. The models registered in `applications/models.py` are also modified so that the history of a model is deleted along with the other database data.
Manually: run `python manage.py seed` to generate mock applications, of which 10 are  cancelled with a `modified_at` date 30 or more days in the past. Running the command should delete those 10 applications. 
Via Pytest: run `pytest applications/tests/test_application_task.py`.

Hl 548 delete cancelled applications

---

backend/benefit/applications/management/commands/seed.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_application_tasks.py

Improve the previously added seeder command so that it works better in the development environment where 
attachments are uploaded into Azure blob storage. 
- Delete attachments through the FileModelField class
- Check the DEBUG env-variable with django.conf
- Add a test for the DEBUG variable
- Modify seeder so that cancelled applications have  `modified_at` date older than 30 days.
Run `pytest applications/tests/test_application_tasks.py`.

Seeder improvements

---

.env.benefit-backend.example
backend/benefit/README.md
backend/benefit/helsinkibenefit/settings.py

The `local`, `development` and `testing` environments are connected to the Sentry instance at [`https://sentry.test.hel.ninja/`](https://sentry.test.hel.ninja/) under the `yjdh-benefit`-team. There are separate Sentry projects for the Django api (`yjdh-benefit-api`), handler UI (`yjdh-benefit-handler`) and applicant UI (`yjdh-benefit-applicant`). To limit the amount of possibly sensitive data sent to Sentry, the same configuration as in kesaseteli is used by default, see [`https://github.com/City-of-Helsinki/yjdh/pull/779`](https://github.com/City-of-Helsinki/yjdh/pull/779).

Configure Sentry for Django, use GPDR-friendly defaults for Sentry

---

frontend/benefit/handler/src/components/applicationReview/paySubsidyView/PaySubsidyView.tsx

Add apprenticeship attachment doc to handler's application view.
* As per [spec HL-629](https://helsinkisolutionoffice.atlassian.net/jira/software/c/projects/HL/boards/204?modal=detail&selectedIssue=HL-629)
* Implementation done according to: "_Voidaan toteuttaa joko otsikon Palkkatukipäätös alle ..._",  because in this section there was already a field `Onko kyseessä oppisopimus? Kyllä / Ei`.
See image, first application does not have "oppisopimus" selected.

HL-629 | Add apprenticeship contract for handler

---

frontend/shared/src/components/attachments/UploadAttachment.tsx

Adding `accept` attribute to upload `<input>` to limit upload file types to allowed file types. Allowed file types were already defined elsewhere as an array.

HL-623 Limit upload filetypes

---

backend/kesaseteli/applications/locale/en/LC_MESSAGES/django.po
backend/kesaseteli/applications/locale/fi/LC_MESSAGES/django.po
backend/kesaseteli/applications/locale/sv/LC_MESSAGES/django.po
backend/kesaseteli/applications/templates/youth_summer_voucher_email.html
backend/kesaseteli/applications/templates/youth_summer_voucher_email.txt

fix: change youth summer voucher email's year from 2022 to 2023

---

frontend/benefit/handler/src/hooks/useApplicationsQuery.ts

I've accidentally used wrong endpoint in frontend when list orderby was implemented. Handler's archive should now be working as intended.
Resolves:
* [HL-651](https://helsinkisolutionoffice.atlassian.net/browse/HL-651)
* [HL-649](https://helsinkisolutionoffice.atlassian.net/browse/HL-649)
* [HL-650](https://helsinkisolutionoffice.atlassian.net/browse/HL-650)
[HL-651]: https://helsinkisolutionoffice.atlassian.net/browse/HL-651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HL-649]: https://helsinkisolutionoffice.atlassian.net/browse/HL-649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HL-650]: https://helsinkisolutionoffice.atlassian.net/browse/HL-650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …

HL-661 | Use the correct endpoint for handler

---

backend/benefit/applications/api/v1/serializers.py
backend/benefit/applications/tests/test_applications_api.py
frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.tsx
frontend/benefit/applicant/src/components/applications/applicationList/useApplicationList.ts
frontend/benefit/applicant/src/components/applications/pageContent/PageContent.tsx
frontend/benefit/shared/src/types/application.d.ts

Fix sorting issues with draft listing by using `modified_at` rather than `created_at`.
The actual issue?
1. Applicant makes a new application
2. Applicant presses "Save and close" button
3. Application is now created but listed in by `created_at`
4. Applicant edits to an older draft and presses "Save and close" button
5. Application list for drafts remains unchanged even though the older draft should now be listed before the newly created one
Behaviour is now changed to order the list by `modified_at`.

HL-230 | Fix sorting issues with draft listing by using modified_at

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/header/Header.tsx
frontend/benefit/handler/src/constants.ts
frontend/benefit/handler/src/hooks/useLogout.ts
frontend/benefit/shared/src/backend-api/backend-api.ts

Header now displays user's full name and has a dropdown link to sign out. ~As far as I'm considered, there's no configured path to local development for OAUTH2:~
* ~https://localhost:8000/oauth2/login~
* ~https://localhost:8000/oauth2/logout~
~Thus, testing this is hard.~
~However, these seem to work on test env backend:~
* ~[See log in / out links here](https://helsinkisolutionoffice.atlassian.net/browse/HL-437)~
~This is enough and fine, I think~ 🤔 🤷‍♂️  
All good now, HL-567 resolves all OAUTH2 / AD login problems.

HL-437 | Handler is able to log out

---

backend/shared/shared/azure_adfs/README.md
frontend/benefit/handler/src/components/header/Header.tsx
frontend/shared/src/types/user.d.ts

Changes that we forgot in pair review: Active Directory log-in didn't render anything for given_name or family_name.

Fix firstName and lastName render & typing for AD-logged user

---

backend/benefit/applications/services/pdf_templates/benefit_template.html

Generating PDF's caused a fatal error if some calculations were of `NoneType`. I've modified the PDF frontend so that it takes None into account and PDF's are fine. However, I don't know if these 0 € rows should be included in the first place, this might be a byproduct from a bug elsewhere in the calculation system.

HL-665 | Fix missing variable value that crashed the pdf generator

---

frontend/benefit/applicant/browser-tests/newApplication/association.testcafe.ts
frontend/benefit/applicant/browser-tests/newApplication/company.testcafe.ts
frontend/benefit/applicant/browser-tests/page-model/step1.ts
frontend/benefit/applicant/package.json

Basically just duplicate `company.testcafe.ts` and add some functions to click association-specific elements. 
* There will be alot of warnings like:
```
TestCafe cannot interact with the <input id="benefitTypeSalary"
class="RadioButton-module_input__1cTWc radio-button_hds-radio-button__input__27sH6" type="radio"
name="benefitType" value="salary_benefit"> element because another element obstructs it.
...
```
I'm guessing they come from HDS components not using browser native checkbox and radio elements and there's little we can do about it.
In `.env.benefit-backend` set `DUMMY_COMPANY_FORM_CODE=29`.
Before proceeding export your previous database so you can continue work later.
Log in to DB container's shell:
```
docker exec -it backend-db /bin/bash
psql -U benefit
```
In psql:
```
DROP …
```

HL-361 | Add browser test for association applicant 

---

backend/benefit/applications/api/v1/views.py
backend/benefit/applications/tests/test_applications_api.py

Adds application_number as a search filter to the handler's list.
Visit the Swagger API documentation at [https://localhost:8000/api_docs/swagger/#/v1/v1_handlerapplications_list](https://localhost:8000/api_docs/swagger/#/v1/v1_handlerapplications_list) and input an application_number into the query parameters and click "execute".
With pytest run `USE_S3=False pytest applications/tests/test_applications_api.py -k 'test_applications_filter_by_application_number'`.

Add application_number to search filters

---

frontend/benefit/applicant/src/components/applications/forms/application/step1/companyInfo/CompanyInfo.tsx

On-screen reader tells user to toggle on alternative address checkbox but actually it's not required by the form validation. Remove `required="true"` HTML-attribute to fix the issue.

HL-531 | Alternative address is no longer required

---

frontend/benefit/applicant/src/components/layout/Layout.tsx

Fixes critical error caused by HDS Koros effect: 
```Warning: Prop `id` did not match. Server: "koros_basic-xxx" Client: "koros_basic-xxx"```
Branch out, load https://localhost:3000. No more red error in console.

HL-687 | Fix SSR error by only rendering footer on client side

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/step1/companyInfo/CompanyInfo.tsx
frontend/benefit/applicant/src/components/applications/pageContent/PageContent.tsx
frontend/benefit/applicant/src/components/errorPage/ErrorPage.tsx
frontend/benefit/applicant/src/hooks/useFormActions.tsx
frontend/benefit/applicant/src/pages/404.tsx
frontend/benefit/applicant/src/utils/common.ts
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/pages/404.tsx

* Add 404 page to handler & applicant
* Fix mapping and displaying backend error in toast when contentType was a string (text/html)
* Change YTJ/Yrtti backend failure to human-readable format

HL-308 | Add generic errors and fix some toast-related issues

---

frontend/audit-ci.jsonc

Audit-ci is failing constantly. Add `http-cache-semantics` package to whitelist.

Add http-cache-semantics to audit-ci whitelist

---

.env.benefit-backend.example
backend/benefit/helsinkibenefit/settings.py

Cont. from https://github.com/City-of-Helsinki/yjdh/pull/1920
We are currently logged in as a private person but the app crashes on eauthorization the graphql query fails because of some missing envs (these are already in place in TET).
For more information, search for "Tunnistamo" at https://github.com/City-of-Helsinki/yjdh/blob/develop/backend/README.md
Deployed to dev / test works now. Yeehaw !! 🤠

HL-715 | Add missing ENV declarations to enable GraphQL and fetch SSN

---

frontend/benefit/shared/src/backend-api/backend-api.ts

A route without slash results to Django redirecting every request to `/me/`. This happens on every SPA page view change and when user clicks outside the browser tab and returns to the app.
These are used as kind of an authorization health check for both handler and the applicant app. This PR fixes the redirect issue as we only want to call the version with the slash.

Fix nasty redirect issue which happens in every view for both apps

---

.github/workflows/audit.yml
.github/workflows/bf-applicant-frontend-tests.yml
.github/workflows/bf-handler-frontend-tests.yml
.github/workflows/bf-review.yml
.github/workflows/bf-shared-frontend-tests.yml
.github/workflows/ks-empl-frontend-tests.yml
.github/workflows/ks-handler-frontend-tests.yml
.github/workflows/ks-review.yml
.github/workflows/ks-shared-frontend-tests.yml
.github/workflows/ks-youth-frontend-tests.yml
.github/workflows/shared-frontend-tests.yml
.github/workflows/te-admn-frontend-tests.yml
.github/workflows/te-review.yml
.github/workflows/te-shared-frontend-tests.yml
.github/workflows/te-yout-frontend-tests.yml
.github/workflows/yarn-audit-scheduled.yml
README.md
frontend/Dockerfile
frontend/README.md
frontend/benefit/README.md
frontend/kesaseteli/README.md
frontend/package.json
package.json

Upgrade NodeJS 14 to 16. 
Some good reasons to this upgrade:
* NodeJS 14 is end-of-life in one month
* Upgrade old node container in local development & online envs
* Upgrade .github actions
* Pave the way to yarn and lerna upgrade
* Pave the way to nextjs 12-13 upgrade
* And last but not least: upgrading has infinite intrinsic value
What could go wrong :godmode: 
---
Tested thoroughly at https://github.com/City-of-Helsinki/yjdh/pull/1945 and works great.

HL-706 | NodeJS 14 to 16 upgrade

---

frontend/tet/shared/src/components/map/Map.tsx

Map was not working for listed postings, instead showed only as gray and logged error when you tried to move the map.
Issue was due to missing center and zoom values for the Leaflet map.
Check that the map renders at '/postings' endpoint.

TETP-274(bug): Added default values for center and zoom

---

README.md
backend/benefit/azure-pipelines-release.yml
backend/kesaseteli/azure-pipelines-kesaseteli-api-release.yml
backend/tet/azure-pipelines-stageprod.yml
frontend/benefit/azure-pipelines-release.yml
frontend/benefit/handler/azure-pipelines-release.yml
frontend/kesaseteli/azure-pipelines-kesaseteli-ui-release.yml
frontend/kesaseteli/handler/azure-pipelines-stageprod.yml
frontend/kesaseteli/youth/azure-pipelines-stageprod.yml
frontend/tet/admin/azure-pipelines-stageprod.yml
frontend/tet/youth/azure-pipelines-stageprod.yml

Release pipelines are triggered by tag instead of commit to master branch
[DEVOPS-528](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-528)
[DEVOPS-528]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Tags to trigger release pipelines

---

backend/benefit/locale/fi/LC_MESSAGES/django.po

Change the Django localisation translation of the word "association" from "yhdistys" to "yhteisö"

Change association finnish translation to "yhteisö"

---

frontend/.dockerignore

Sentry config files were not excluded in the frontend/.dockerignore, thus they were not copied during the build.
This PR adds the exclusion for all the projects in the repo.

Ensure that sentry files are not ignored

---

frontend/.dockerignore

Adds the missing shared sentry-config.js into the .dockerignore exceptions.

Add the missing shared sentry-config.js

---

backend/benefit/applications/api/v1/views.py
backend/benefit/applications/services/csv_export_base.py
backend/benefit/applications/tests/test_applications_report.py

The Talpa integration requires that the CSV-file has no scandics in the filename and no quotes surrounding the strings.
This PR renames the export without the letter "ä" and removes the double quotes from the CSV file generated for Talpa while preserving the quotes for the export that has all applications from a  selected period.

Hl 791 talpa csv

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/hooks/useUserQuery.ts
frontend/benefit/handler/src/pages/login.tsx

**Before:**
When backend was unavailable, frontend kept on insisting that the user was in logged in state and trying to fetch more resources. 
**After:**
In case of an error we now redirect to `/login` and an error shows up.
Not sure if this addresses every known issue with the handler UI showing up without login, but we are getting there.

HL-590 | Fix issues with fetching user when backend is down

---

frontend/benefit/handler/src/hooks/useUserQuery.ts

Related to #2042.
When modifiying backend the frontend would panic and assume that backend is seriously ill. Do not redirect if mock-flag is in use.

For developer convenience do not redirect to login if backend is down

---

backend/kesaseteli/applications/api/v1/views.py
backend/kesaseteli/applications/models.py
backend/kesaseteli/applications/tests/test_security_with_anonymous_user.py
backend/kesaseteli/applications/tests/test_security_with_non_staff_user.py

fetch_employee_data POST endpoint can be used to fetch employee's data
using the employee's name and summer voucher serial number.
refs YJDH-587 (The backend endpoint)
refs YJDH-667 (Audit log writing)
- [YJDH-587](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-587)
- [YJDH-667](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-667)
Added automated backend tests:
- test_security_with_anonymous_user.py:
- test_youth_application_fetch_employee_data_forbidden_to_anonymous_user
- test_security_with_non_staff_user.py:
- test_youth_application_fetch_employee_data
- test_youth_application_fetch_employee_data_success_writes_audit_log
- test_youth_application_fetch_employee_data_not_found_writes_audit_log
- test_youth_application_fetch_employee_data_unallowed_methods
[YJDH-587]: …

YJDH-587, YJDH-667 | feat(ks-backend): add fetch_employee_data endpoint to fill employee form

---

frontend/benefit/applicant/public/robots.txt
frontend/benefit/handler/public/robots.txt
frontend/benefit/handler/src/hooks/useUserQuery.ts
frontend/benefit/shared/src/pages/BenefitDocument.tsx

Allow and optimize applicant later, when closed beta ends.
* Using robots.txt
* https://localhost:3000/robots.txt
* https://localhost:3100/robots.txt
* Check for tag `<meta name="robots"... />` inside `<head>`:
* https://localhost:3000
* https://localhost:3100

Hide handler and applicant from search engines

---

backend/benefit/applications/tests/factories.py
backend/benefit/companies/tests/factories.py
backend/shared/shared/common/tests/factories.py

* Benefit: I grew tired of using English seeds, use fi locale now as it reflects the real app behaviour better
* Shared: More unique faked usernames so that `benefit` seeded applications and tests won't have username namespace errors anymore
* More details: [c5d4bf3f3a2a2](https://github.com/City-of-Helsinki/yjdh/commit/c5d4bf3f3a2a22e7415c8ec3ef559b8314a1d8b2#diff-cb4c93c6e1947a9c35a5449e03d3a00cb22c0b16ca4a5e3cf3b100f883ad88f9L16) (`As we generate applications for batches too, faker usernames start to conflict which means a failing test...`)

Use Finnish locale in benefit factories, add more chars to faked username

---

backend/kesaseteli/CHANGELOG.md

No tag was created by release-please, CHANGELOG.md contained wrong information.
Update CHANGELOG.md manually.
refs YJDH-677

chore(ks-backend): update CHANGELOG.md manually

---

frontend/benefit/applicant/package.json
frontend/benefit/applicant/src/components/pdfViewer/PdfViewer.tsx
frontend/benefit/applicant/tsconfig.json
frontend/next.config.js
frontend/yarn.lock

* Resolve rendering issues
* Update react-pdf again
~Loading the worker from `public/` is not elegant and webpack should probably load it but webpack is keen on generating the file with hash included in the name for cache busting purposes. That won't allow the resource to be loaded from a single static path so we need to revisit that after NextJs12 upgrade, which has changes in the asset pipeline.~
UPDATE: Loads from webpack now, with considerably smaller JS footprint ~500KB.

HL-836 | Fix pdf viewer issues 

---

frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.sc.ts
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.tsx
frontend/benefit/applicant/src/components/mainIngress/MainIngress.sc.ts

Previously some elements were squashed and hidden when screen was small. Add in some responsiveness via breakpoints. I didn't have the guts to go with custom pixel widths to get this perfect in terms of design, but hey, at least it works.
* Fix page title and action button for "create new application"
* Switch to row view at >= 768px
* Fix list view
* Everything is stacked at 0 - 576px
* Switch to two columns at 576 - 768px (not presented in gif)
* Switch to row view at 768px
* Button "edit" to same row at >= 1024px

HL-818 | Improve application front page responsiveness

---

frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/components/applicationsArchive/ApplicationsArchive.tsx
frontend/benefit/handler/src/components/batchProcessing/ApplicationsHandled.tsx
frontend/benefit/handler/src/components/batchProcessing/BatchApplicationList.tsx
frontend/benefit/handler/src/types/applicationList.d.ts
frontend/shared/src/utils/date.utils.ts

By default, `<Table>` sorts data as A,B,C... 
Use custom function to change the sort algorithm for dates.

HL-839 | Tables now sort based on date value

---

frontend/shared/browser-tests/reporter/slackMessageSender.ts

Figured new PR would not mess / have effect with other project specific PR as this file is under `shared/`.
Local prettier/Eslint wanted also to make one line look beautiful. 
Fixes these issues:

Small fix | Disable eslint warn about Slack reporter's console.log

---

backend/benefit/calculator/api/v1/serializers.py
backend/benefit/calculator/tests/test_calculator_api.py
backend/benefit/locale/en/LC_MESSAGES/django.po
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/sv/LC_MESSAGES/django.po

The handler form fails silently if there is no option selected from the State Aid Maximum Percentage select element.
This PR extends the backend validations for the pay subsidy calculation to validate that the State Aid Maximum Percentage is selected and displays an error if is it not.
Navigate to the handler form, open an application for handling, try to create a calculation without selectin the State Aid Maximum Percentage.
Investigating the issue, I noticed that there is some code on the frontend for validating the input fields, but enabling the frontend validation breaks the layout and the validations  as the date inputs use the same keys.
Fixing this is assigned to a separate ticket [HL-826](https://helsinkisolutionoffice.atlassian.net/browse/HL-826?atlOrigin=eyJpIjoiOTczYWI5ZTZlNWRhN …

HL-756 | Validate state_aid_max_percentage

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/step6/ApplicationFormStep6.tsx
frontend/benefit/applicant/src/components/pdfViewer/PdfViewer.sc.ts
frontend/benefit/applicant/src/components/pdfViewer/PdfViewer.tsx
frontend/benefit/applicant/src/components/termsOfService/TermsOfService.tsx

* Remove fixed 700px viewport for PDF
* PDF area is now bordered with a box-shadow
* Change button component layout
* Hide next / prev buttons if PDF is only a 1 pager
* Fix translations
Mobile layout is absolutely busted. We will address this later with going with Django admin/pages and render content in frontend from markdown to HTML. This will also mitigate all the a11y problems related with PDFs.

HL-857 | PDF no longer fixed to 700px height

---

frontend/tet/youth/src/components/jobPostingSearch/JobPostingSearch.tsx

JobPostingSearch keywords can put cause application to crash if no matching keywords found in workFeaturesList
In useEffect should check to both keywords and workFeaturesList are not undefined
Testing on local machine

TETP-276(bug): JobPostingSearch keywords workFeaturesList

---

frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/DeMinimisAidForm.tsx
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/utils/validation.ts
frontend/benefit/applicant/src/constants.ts

DeMinimis aid date allows the manual input of dates  such as 1.1.1900 or 31.12.2000 which crash the app when navigating to next step. This PR adds a validation that checks that the given date cannot be older than January first, four years ago.
The minimum date is also enforced in the datepicker component via props.
Navigate to the first step of the form and try to input past  dates into the deMinimis granted at  element.

Validate  granted_at so that it cannot be more than 4 years in the past

---

frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/useHandlingApplicationActions.ts

If a specific query parameter was missing, then the app crashed in handling view.

HL-876: Handling view doesn't work

---

frontend/benefit/handler/src/hooks/useDeleteApplicationQuery.ts

Once again, the applicant endpoint was used instead of the handler endpoint. Over-aggressive mocking prevented catching this in the development environment.

HL-865: Can't remove drafts as handler

---

backend/benefit/applications/admin.py
backend/benefit/applications/management/commands/seed.py
backend/benefit/applications/tests/test_application_tasks.py
backend/benefit/terms/fixtures/default_terms.json
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/newApplication/useApplicationForm.ts
frontend/benefit/handler/src/hooks/useFormActions.tsx

Crashed as the frontend couldn't parse the backend error message related to the missing terms. This fixes error message parsing.
Also, added fixture for handler terms to avoid this happening in the future.
Modified `seed` command to seed handler applications also (HL-875).

HL-864, HL-875: Fix failing submit for handler

---

frontend/benefit/applicant/src/hooks/useLogin.ts

The backend accepts `lang` query parameter. Pass that to the backend.

HL-838: Use language for strong identification

---

frontend/benefit/applicant/src/components/header/Header.tsx

Browser native notification should be enough to prevent the user from navigating elsewhere when the form is unsaved.

HL-298, HL-869: Add link to header logo

---

frontend/benefit/handler/src/components/applicationReview/consentView/consentActions/ConsentActions.tsx
frontend/benefit/handler/src/components/applicationReview/employeeView/EmployeeActions/EmployeeActions.tsx
frontend/benefit/handler/src/components/applicationReview/employmentView/employmentActions/EmploymentActions.tsx
frontend/benefit/handler/src/components/applicationReview/paySubsidyView/PaySubsidyActions/PaysubsidyActions.tsx

Attachments can be JPG and PNG files also.

HL-829 | Add more mime types as allowed uploads

---

backend/benefit/helsinkibenefit/settings.py

Eauthorization language was still FI even though @mjturt had set `?lang` parameter. Backend would not save the data however, and after person's authentication, django would drop the ball and fallback to default language when continuing to eauthorization.
If this 'accept-language' causes any trouble or side-effects in nextjs then let's see if we can just store 'accept-language' header value to `django_language` cookie.

HL-838 cont. | Allow use of django_language cookie like in TET

---

frontend/benefit/applicant/src/components/applications/forms/application/step1/ApplicationFormStep1.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step1/useApplicationFormStep1.ts
frontend/benefit/applicant/src/components/applications/forms/application/step1/utils/validation.ts

Making it mandatory to choose a value from deminimis aid radio button in #2132 made it possible for an association user to get stuck on the first step of the form. This PR fixes the validation for the deminimis input so that when user is from an association, and has no business activity, the deminimis yes/no radio input is not visible and is not require. When the user represents a company, the deminimis yes/no radio input is visible and  required .

HL-856 | Show deminimis section for company and association

---

azure-pipelines/helsinkilisa-review.yml
backend/benefit/docker-entrypoint.sh

[DEVOPS-549](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-549)
pipeline templates
[yjdh-helsinkilisa-pipelines/pullrequest/5480](https://dev.azure.com/City-of-Helsinki/yjdh-helsinkilisa/_git/yjdh-helsinkilisa-pipelines/pullrequest/5480)
[DEVOPS-549]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: helsinkilisa review environment on Platta DEVOPS-549

---

.env.benefit-backend.example
backend/benefit/README.md
backend/benefit/helsinkibenefit/settings.py
backend/benefit/requirements.in
backend/benefit/requirements.txt
compose.benefit.yml

Remove all minio dependencies and references from benefit. They are no longer needed.

HL-871 | Remove minio references

---

frontend/benefit/applicant/src/components/messenger/Messages.tsx
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/messenger/Messages.tsx
frontend/shared/src/components/messaging/Message.tsx
frontend/shared/src/components/messaging/Messaging.sc.tsx

* New style of messenger with own chat bubbles on the right hand side and other person's bubbles on the left
* Defaults to old style so TET and KS is not affected by the change
* Add missing translations

HL-882 | Add new messenger style and fix translations on handler side

---

backend/benefit/applications/migrations/0036_alter_employee_working_hours.py
backend/benefit/applications/models.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/newApplication/utils/validation.ts
frontend/benefit/shared/src/constants.ts

There might be a scenario where a person works for say, 20 hours and 15 minutes. Previously it was impossible to input such value.

HL-862 | Allow two decimals for working hours

---

backend/benefit/users/api/v1/serializers.py
frontend/benefit/handler/src/auth/AuthProvider.tsx
frontend/benefit/handler/src/hooks/useUserQuery.ts
frontend/shared/src/types/user.d.ts

Fix issue with wrong user role. If user is logged and has wrong permissions, log the user out.
* On local dev: You must set `NEXT_PUBLIC_MOCK_FLAG=0` (or modify DB for `is_staff=false` on currently logged user) and log in as applicant ([https://localhost:3000](https://localhost:3000)). Then go to [https://localhost:3100](https://localhost:3100).
* On dev/test server: log in as applicant, then go to handler. Loaders spin and nothing gets loaded as all the requests will fail continously.

HL-849 | Fix insufficient user permissions causing handler application to freeze

---

frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/HandlingApplicationActions.tsx

Remove buttons that affect application status if app is already in a batch or it is archived ("done"). 
Hidden buttons are:
* Take application to re-evaluation
* Cancel application

HL-868 | Hide archived / batched app's actions

---

backend/benefit/applications/models.py
backend/benefit/applications/tests/test_application_batch_api.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/batchProcessing/BatchActionsInspectionForm.tsx
frontend/benefit/handler/src/components/batchProcessing/BatchApplicationList.tsx
frontend/benefit/handler/src/components/batchProcessing/useBatchActionsInspected.ts
frontend/benefit/handler/src/components/table/BatchCompletion.sc.ts
frontend/benefit/handler/src/components/table/TableExtras.sc.ts
frontend/shared/src/styles/theme.ts
frontend/shared/src/types/styled-components.d.ts

Only Ahjo **OR** P2P fields are needed, depending on case. Only display form fields based on which one is better for koonti at hand.
* Renewed colors and design
* Only either / or is required from formik and yup
* Change backend validation rules

HL-820 | P2P / Ahjo inspection inputs are shown/hidden based on radio button's value

---

backend/benefit/applications/migrations/0037_reviewstate.py

Fix conflicting migration file name issue.

HL-642 cont. | Rename conflicting migration file

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json

HL-530 | Use correct aria-label for mobile menu

---

frontend/benefit/handler/src/components/applicationReview/employmentAppliedMoreView/utils/validation.ts
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryBenefitCalculatorView.tsx
frontend/benefit/handler/src/constants.ts
frontend/benefit/shared/src/constants.ts

The handler form does not give any error when the user presses the calculate without a start date or an end date in the date input fields for the Helsinki benefit granted date range. This PR activates the frontend validation for the fields, fixes a naming collision with the startDate and endDate fields of the training compensation input fields, and fixes the frontend validation error message layout breaking because of the DateInputWithSeparator component not having enough space for the message.
Login as a handler, open an application and press the calculate button without start or end date in the benefit granted period fields.
Discovered the bug https://helsinkisolutionoffice.atlassian.net/browse/HL-910 where typing text into the training compensation end date input field crashes the …

Hl 898 handler validation

---

frontend/benefit/applicant/public/favicons/manifest.webmanifest
frontend/benefit/handler/public/favicons/manifest.webmanifest

Some favicon assets are 404'ing. Manifest file's path should have `/favicons/` in front.
Compare:
* [with /favicon/](https://yjdh-helsinkilisa-ui-hki-kanslia-yjdh-helsinkilisa-test.agw.arodevtest.hel.fi/favicons/favicon-512x512.png)
* [no /favicon/](https://yjdh-helsinkilisa-ui-hki-kanslia-yjdh-helsinkilisa-test.agw.arodevtest.hel.fi/favicon-512x512.png)

fix: some favicons had wrong asset path

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/DeMinimisAidForm.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step1/ApplicationFormStep1.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step1/useApplicationFormStep1.ts

De minimis aid could not be removed (one aid had to remain, otherwise the rows would not get updated) after application was created. Now additional checks are being done:
* Ensure there is no unfinished aid fields
* Toast an error if there is
* If there is no aid rows but de minimis toggle radio is on then consider radio is off

HL-885 | Fix de minimis aid's row deletion

---

frontend/benefit/applicant/src/components/layout/Layout.tsx

Do not mount terms component if current route is accessibility statement.

HL-890 | Do not obscure view with terms on a11y statement page

---

backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/applications/tests/factories.py
frontend/benefit/handler/src/hooks/useUpdateApplicationQuery.ts

* Fix seeded applications not being able to be opened / locked by adding more required attachments
* Fix all  handler-generated applications throwing a validation violation by skipping user terms validation altogether
* Add toast error reporting if something goes wrong
On handler's side, there's still problems locking or opening an application when terms have been changed and old (although accepted) ones  are not in effect anymore. The locking and opening action uses general `PUT` on `/applications/{app_id}/` so it's an error prone process because of rigorous model validation. [There's a new ticket for this](https://helsinkisolutionoffice.atlassian.net/browse/HL-916).
There are two ways to implement a fix:
* Make custom endpoint
* a new field to set application lock property on/off
* or …

HL-883 | Fix some issues with opening and locking application on handler's side

---

backend/benefit/applications/tests/test_applications_report.py

Skip csv_export_new_applications test as it fails constantly in deploy

---

backend/benefit/applications/tests/test_applications_report.py
frontend/benefit/applicant/src/components/applications/forms/application/step1/useApplicationFormStep1.ts
frontend/benefit/applicant/src/hooks/useFormActions.tsx

De minimis aid rows were not saving properly when using "save and close" button. De minimis rows are now being checked if unfilled. "Save and close" and "Next" -button differ in functionality too as "Next" uses Formik more intensively (can't continue without all required information). "Save and close" is more lax as it is intended to allow saving a draft application.

HL-885 cont. | Fix "save and close" button's behaviour on changing de minimis rows

---

backend/benefit/applications/tests/test_applications_report.py

remove unneeded line again

---

.github/workflows/conventional-commits.yml
.husky/commit-msg
.husky/pre-commit
.pre-commit-config.yaml
README.md
commitlint.config.js
package.json
yarn.lock

- Add Release Please documentation in readme
- Modify Git hooks documentation in readme
- Run also lerna & husky & lint-staged git hooks with pre-commit. Pre-commit is now the preferred git hook system.
- Add git hook to validate commit messages
- Add GitHub action to validate commit messages

HL-930: Release Please docs and git hook & CI modifications

---

frontend/benefit/applicant/src/hooks/useUserQuery.ts
frontend/benefit/handler/src/hooks/useUserQuery.ts

Set axios instance CSRF header instantly when getting token from /me endpoint, as the axios instance might be initialized before there was CSRF token available.

HL-925: set CSRF header instantly when getting token

---

frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryBenefitCalculatorView.tsx

User is able to input anything into the handler application training compensation end date field and it crashes the app.
This happens because the getCorrectEndDate() function returns undefined when it cannot convert either of the supplied date strings into dates. This PR fixes the issue by making the return value optional.
Navigate to the handler application and into an application that has one or more training compensation rows, try to type something into the training compensation end date.

fix: non-date string crash in trainingCompensationEndDate

---

frontend/benefit/handler/src/components/batchProcessing/BatchActionsInspectionForm.tsx

Forgot to add animation callback to hook which resulted to UI not doing animation when returning batch as draft. This also broke the error toast from showing up.

HL-974 | Batch animation bug

---

backend/benefit/applications/services/applications_csv_report.py

Talpa CSV export has multiple rows per application because it uses the same row generation logic as Ahjo export, which generates a row per application calculation row. This PR fixes the Talpa export so, that only one row per application is generated when exporting for Talpa with the prune_data_for_talpa parameter set to True.
Create a batch with applications and mark them ready for talpa.
Visit the talpa api endpoint at `/v1/applicationbatches/talpa_export`, to download the CSV.

fix: only one row per application in Talpa CSV export

---

frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/validation.ts
frontend/benefit/applicant/src/constants.ts

Fix validation schema for salaries.

HL-988 | Require salary and expenses to be 0 - 99999

---

frontend/package.json
frontend/yarn.lock

Issues with assert timeout on Mac Ventura, TestCafe needs to be upgraded to continue work on localhost.
Resolve https://github.com/advisories/GHSA-4q6p-r6v2-jvc5

chore: bump testcafe to 3.3.0

---

frontend/benefit/applicant/src/hooks/useFormActions.tsx
frontend/benefit/handler/src/hooks/useFormActions.tsx

Send the default `paySubsidyPercent` with value `50` so that the calculation row creation gets triggered.

fix: send default paySubsidyPercent value (HL-995)

---

.env.tet.example
backend/tet/events/tests/data/linked_events_responses.py
frontend/tet/admin/next.config.js
frontend/tet/admin/src/__tests__/utils/backend/backend-nocks.ts
frontend/tet/shared/src/backend-api/linked-events-api.ts
frontend/tet/youth/browser-tests/search.testcafe.ts
frontend/tet/youth/src/backend-api/backend-api.ts

Old dev/test Linked Events instances are deprecated and replaced by Platta LE instances. It is recommended that outside services use TEST Platta Linked Events, so that is used here.
[TETP-279](https://helsinkisolutionoffice.atlassian.net/browse/TETP-279)
Tested manually locally.
[TETP-279]: https://helsinkisolutionoffice.atlassian.net/browse/TETP-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Switch to new Platta test Linked Events

---

frontend/kesaseteli/employer/src/components/application/form/DateInput.tsx
frontend/shared/src/components/forms/inputs/DateInput.tsx

YJDH-684.
Since the HDS DateInput has a compatibility issue with React-hook-forms,
The onChange should include processes to
1) clear the input validation errors and
2) set the input value.
Otherwise the errors are not cleared when a datepicker is used.
The onChange is currently not in the same format
as the HDS dateinput is expecting it to be.
HDS DateInputProps are waiting for (value: string, valueAsDate: Date),
but onChange from the InputProps is (value: string).
OnChange of the React-hook-Forms waits a SyntheticEvent as a parameter.
NOTE: The HDS v. 3.0.0 will change the DateInput onChange to have an Event as a parameter.

fix(dateinput): clear validation errors when a datepicker selects a date

---

compose.benefit.yml
compose.employer.yml
compose.handler.yml
compose.tet-admin.yml
compose.tet-youth.yml
compose.tet.yml

To ensure that mac m1&m2 chips use amd images instead of the arm ones. This way we all should be using the same base images.

feat: add platform definitions to docker compose files

---

backend/benefit/common/tests/test_utils.py
backend/benefit/common/utils.py

A SHA-256 hash of each attachment needs to be sent to Ahjo when opening a case, this PR adds a small utility for the hash.

feat: add utility for hashing Ahjo attachments

---

backend/benefit/requirements.txt

This adds support for new SSNs (https://github.com/arthurdejong/python-stdnum/pull/396).

feat: update python-stdnum to 1.19 (HL-662)

---

frontend/benefit/applicant/src/hooks/useTermsOfServiceData.ts

Access the right object for English markdown terms.

fix: wrong object accessed for English terms

---

backend/benefit/applications/services/applications_csv_report.py
backend/benefit/applications/tests/test_applications_report.py

Change talpa export column titles like so
Asiantarkastajan email P2P → Tarkastajan sähköposti, P2P
Asiantarkastajan nimi P2P → Tarkastajan nimi, P2P

feat: Change  some Talpa csv export column titles

---

backend/benefit/applications/api/v1/application_batch_views.py
backend/benefit/applications/services/csv_export_base.py
backend/benefit/applications/tests/test_talpa_integration.py

Talpa csv export works better in Windows excel, when a byte order mark (BOM) is appended to the beginning of the file.

feat: add byte order mark to talpa export for better excel support

---

frontend/kesaseteli/handler/package.json
frontend/kesaseteli/shared/package.json
frontend/kesaseteli/youth/package.json

Downgrade `finnish-ssn` library so it won't generate new style of ssn in tests.

fix: downgrade kesaseteli ssn library as it's not compliant yet

---

backend/benefit/messages/serializers.py
backend/benefit/messages/tests/test_api.py

* Add more statuses to be ok'd for messaging
* If archived then no message can be sent by applicant
* Fix/add tests for these cases

fix: allow applicant messages for all but cancelled and archived app (HL-860)

---

backend/benefit/applications/services/csv_export_base.py
backend/benefit/applications/tests/test_applications_report.py
backend/benefit/applications/tests/test_talpa_integration.py
frontend/shared/src/utils/file.utils.ts

Adds a BOM in the beginning of the csv in the zipped batch and in the report that handler can dowload from the reports page.

Hl 1048 bom

---

frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.sc.ts
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.tsx
frontend/benefit/applicant/src/components/applications/applicationList/useApplicationList.ts
frontend/benefit/applicant/src/components/header/Header.tsx
frontend/benefit/applicant/src/components/header/useHeader.ts
frontend/benefit/shared/src/types/application.d.ts

Allow opening application's message drawer using query param `openDrawer=1`.
---
Click image to preview:

feat: open drawer on click of new messages bar

---

frontend/benefit/applicant/src/components/applications/forms/application/step1/ApplicationFormStep1.tsx

Add a missing function call, only the key was shown before.

fix: wrap i18n key with translation fuction (HL-1037)

---

frontend/Dockerfile

I grew tired of `package.json`changes and continuous rebuilding. `appbase` layer is now down from 140s+ to 60s+ on my local setup.
* Local docker configuration now uses `yarn cache` to resolve dependencies
* running `yarn` on rebuild utilizes cached dependencies if they are available
* Introduced a new OS-level docker layer, `apt-get` is now done in `distbase`
* `apt-get` is single line now and has improvements suggested by SonarLint

feat: leverage docker buildkit cache mount to install node deps

---

frontend/benefit/applicant/package.json
frontend/benefit/handler/package.json
frontend/benefit/shared/package.json
frontend/kesaseteli/employer/package.json
frontend/kesaseteli/handler/package.json
frontend/kesaseteli/youth/package.json
frontend/package.json
frontend/shared/package.json
frontend/tet/admin/package.json
frontend/tet/shared/package.json
frontend/tet/youth/package.json
frontend/yarn.lock

Just testing tooling, CI change and lerna v5. If tests go green then I'd say merge it.
This version of NextJS only has some performance improvements on build phase.
next
* @frontend/applicant: ^13.5.6 → 14.0.3
* @frontend/benefit-shared: ^13.5.6 → 14.0.3
* @frontend/bf-handler: ^13.5.6 → 14.0.3
* @frontend/employer: ^13.5.6 → 14.0.3
* @frontend/ks-handler: ^13.5.6 → 14.0.3
* @frontend/shared: ^13.5.6 → 14.0.3
* @frontend/te-admin: ^13.5.6 → 14.0.3
* @frontend/te-youth: ^13.5.6 → 14.0.3
* @frontend/tet-shared: ^13.5.6 → 14.0.3
* @frontend/youth: ^13.5.6 → 14.0.3

chore: upgrade to nextjs 14

---

frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryBenefitCalculatorView.tsx
frontend/benefit/handler/src/hooks/useCalculatorData.ts

Fix logic when showing "calculation changed" notification. Don't show it without reason anymore.

fix: calculation changed notification (HL-1057)

---

backend/benefit/applications/api/v1/application_batch_views.py
backend/benefit/applications/tests/test_application_batch_api.py

Return a more descripting error status when no applications are found for export.

feat: return 404 instead of 400 when no applications for talpa robot

---

backend/benefit/applications/api/v1/application_batch_views.py

Rejected are not sent to Talpa, so the status for them isn't `SENT_TO_TALPA` and so the `archived` is staying `false`. Now also set `archived=true` for rejected. Haven't worked with Talpa stuff before, can this interfere with something?

fix: show rejected in archive (HL-1039)

---

backend/benefit/applications/api/v1/application_batch_views.py
backend/benefit/applications/tests/test_application_batch_api.py

The generator code and StreamingHttpResponse made it difficult to update the application batch as sent_to_talpa after response was complete, which resulted in an empty csv file.
Add a few applications to a batch and visit (credentials for talpa robot in .env or default ones in settings.py)
https://localhost:8000/v1/applicationbatches/talpa_export/
https://localhost:8000/v1/applicationbatches/talpa_export/?skip_update=0
now respond with a csv tha includes the applications from the batch afterwhich the batch is updated to sent_to_talpa-status
and visiting
https://localhost:8000/v1/applicationbatches/talpa_export/?skip_update=1
returns the csv but does not update the batch.

fix: generate talpa export csv synchronously

---

frontend/benefit/common/src/emails/i18n/en.json
frontend/benefit/common/src/emails/i18n/fi.json
frontend/benefit/common/src/emails/i18n/sv.json

fix: some urls were missing from email templates

---

backend/benefit/applications/api/v1/ahjo_integration_views.py
backend/benefit/applications/enums.py
backend/benefit/applications/services/ahjo_integration.py
backend/benefit/applications/tests/test_ahjo_integration.py
backend/benefit/applications/tests/test_ahjo_requests.py
backend/benefit/helsinkibenefit/urls.py

Adjusts the callback view so that different kinds of callbacks can be received based on the AhjoRequestType enum.
Add a callback address for a DELETE request to Ahjo REST api.
Refactor the function `do_ahjo_request_with_json_payload` into `send_request_to_ahjo` that can do different types of requests.
```
pytest applications/tests/test_ahjo_integration.py
pytest applications/tests/test_ahjo_requests.py
```
`ahjo_integration_views.py` has a function, `_handle_delete_callback()` which currently does nothing, as placeholder because it's not certain yet, what we should do to the application after it is deleted in Ahjo.

Hl 1069 ahjo cancel

---

backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/additional-information-required_en.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/additional-information-required_fi.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/additional-information-required_sv.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/draft-notice_en.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/draft-notice_fi.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/draft-notice_sv.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/received-message_en.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/received-message_fi.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/html/received-message_sv.html
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/txt/additional-information-required_fi.txt
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/txt/draft-notice_fi.txt
backend/benefit/helsinkibenefit/templates/emails/mjml-generated/txt/received-message_fi.txt
backend/benefit/messages/tests/test_api.py
frontend/benefit/common/src/emails/i18n/fi.json
frontend/benefit/common/src/emails/templates/additional-information-required.template.mjml
frontend/benefit/common/src/emails/templates/draft-notice.template.mjml
frontend/benefit/common/src/emails/templates/received-message.template.mjml

Fix broken builds caused by failing pytest.
This reverts and adds to commit c870fcb932b2eff85e3c03339a9fd859877ba274 which is a revert of a previous PR ♻️ .
Fix issue in test. Test would assert **littyen** but it should've been **liittyen** ofc 🤷 .

fix: redo various issues with typos and text flow (#2622)

---

frontend/shared/src/utils/mask-gdpr-data.ts

Shared libraries' gdpr test has been failing since @mjturt  ssn upgrades. Loosen regex to support 2024 style on masking ssn.

fix: more liberal regex on gdpr ssn mask; to support 2024 ssn

---

backend/docker/benefit.Dockerfile
frontend/Dockerfile

This should stop OpenShift build from testing different image registries and just pull it from dockerhub straight away.

fix: stop OpenShift build from testing different image registries

---

frontend/benefit/applicant/src/components/applications/Applications.sc.ts
frontend/benefit/applicant/src/components/applications/pageContent/PageContent.tsx
frontend/benefit/applicant/src/hooks/useAnalytics.ts
frontend/benefit/applicant/src/types/common.d.ts

* fix canonicalUrl
* remove isLoading (the parent component is not mounted if isLoading)
* use disableFonts flag to prevent unnecessary Open Sans loading from askem
* mock hds styles on submit button and set headers to weight 500

fix: askem issues solved (HL-1094)

---

backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/locale/en/LC_MESSAGES/django.po
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/sv/LC_MESSAGES/django.po
frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/validation.ts
frontend/benefit/applicant/src/constants.ts

Fix application start date validations that did not allow the start date to be in the past year.
Fix validations to allow a start date 4 months in the past.

Hl 1093 y2k24 bug

---

frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/__tests__/dates.test.ts
frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/validation.ts
frontend/benefit/shared/src/utils/dates.ts

Frontend validation did not allow for a start date in the future.
As an applicant, create an application and in step 2, set start date to 4 months in the past, current date or any date in the future,
also 
`yarn test`

fix: start_date can now be in the future

---

frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/validation.ts
frontend/benefit/applicant/src/constants.ts
frontend/benefit/handler/src/components/applicationReview/handledView/HandledView.tsx
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryBenefitCalculatorView.tsx
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryCalculatorResults/SalaryCalculatorResults.tsx
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/useSalaryBenefitCalculatorData.ts
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/utils/validation.ts
frontend/benefit/handler/src/components/newApplication/utils/validation.ts
frontend/benefit/handler/src/hooks/useCalculatorData.ts
frontend/benefit/handler/src/types/application.d.ts
frontend/benefit/shared/package.json
frontend/benefit/shared/src/constants.ts
frontend/benefit/shared/src/utils/validation.ts

Fix no.1
* Fix app crash when application is approved / rejected but no calculation has been done
* Add new validation requirements for required salary fields
* Refactor salary-related fields to use generic number validation function
Fix no.2
* Add calculation results for manual calculation
* Hide calculation results if recalculation is needed

fix: app crash on empty calculations (HL-1041)

---

frontend/shared/src/components/app/BaseApp.tsx

Something has changed when next updated. Every page load causes a warning now, which is related to page's `<title>`. Fix behaviour so dev server no longer warns out.
```
Warning: A title element received a value that was not a string or number for children. In the browser title Elements can only have Text Nodes as children. If the children being rendered output more than a single text node in aggregate the browser will display markup and comments as text in the title and hydration will likely fail and fall back to client rendering
at title
at head
at Head (webpack-internal:///../../node_modules/next/dist/pages/_document.js:258:1)
at html
at Html (webpack-internal:///../../node_modules/next/dist/pages/_document.js:676:132)
at BenefitDocument …
```

fix: nullish coalescing operator caused warning on page load

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/mainIngress/MainIngress.sc.ts
frontend/benefit/applicant/src/components/mainIngress/MainIngress.tsx
frontend/benefit/applicant/src/components/prerequisiteReminder/PrerequisiteReminder.sc.ts
frontend/benefit/applicant/src/components/prerequisiteReminder/PrerequisiteReminder.tsx
frontend/benefit/applicant/src/pages/index.tsx

Adjusts the landing page of the benefit applicant site to include a reminder about prerequisites for applying, as well as the style and text content of its introductory heading section.

feat: Applicant landing page adjustments (HL-1033)

---

backend/kesaseteli/applications/exporters/excel_exporter.py
backend/kesaseteli/applications/locale/en/LC_MESSAGES/django.po
backend/kesaseteli/applications/locale/fi/LC_MESSAGES/django.po
backend/kesaseteli/applications/locale/sv/LC_MESSAGES/django.po
backend/kesaseteli/applications/tests/test_excel_export.py

related:
https://github.com/City-of-Helsinki/yjdh/pull/2745#discussion_r1461439607
refs YJDH-683
[YJDH-683](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-683)
[YJDH-683]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YJDH-683 | feat: specify Excel exporter's salary & sum fields as €, cast sum as int

---

frontend/benefit/applicant/browser-tests/page-model/MainIngress.ts
frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/header/Header.tsx
frontend/benefit/applicant/src/components/header/useHeader.ts
frontend/benefit/applicant/src/components/mainIngress/MainIngress.sc.ts
frontend/benefit/applicant/src/components/mainIngress/MainIngress.tsx
frontend/benefit/applicant/src/components/mainIngress/decisions/DecisionsMainIngress.tsx
frontend/benefit/applicant/src/components/mainIngress/frontPage/FrontPageMainIngress.sc.ts
frontend/benefit/applicant/src/components/mainIngress/frontPage/FrontPageMainIngress.tsx
frontend/benefit/applicant/src/components/mainIngress/frontPage/useFrontPageMainIngress.ts
frontend/benefit/applicant/src/components/mainIngress/useMainIngress.ts
frontend/benefit/applicant/src/constants.ts
frontend/benefit/applicant/src/context/AppContext.tsx
frontend/benefit/applicant/src/context/AppContextProvider.tsx
frontend/benefit/applicant/src/pages/_app.tsx
frontend/benefit/applicant/src/pages/decisions.tsx
frontend/benefit/applicant/src/pages/index.tsx

Adds navigation and an archive page to the applicant view that will contain the applicant's old applications that have received a decision.
Displaying the content of the additional page is not included as it's a part of a later PR.

Add navigation and a new page for processed applications (HL-1099)

---

frontend/audit-ci.jsonc
frontend/package.json
frontend/yarn.lock

Whitelist HDS dependency and upgrade nock (used in axios helper function's tests).
HDS team will address the issue. 
https://helsinkicity.slack.com/archives/CHCV3KTHA/p1706169717016779

chore: upgrade nock for lodash.set, whitelist lodash.pick for HDS

---

backend/benefit/applications/api/v1/serializers/batch.py
backend/benefit/applications/api/v1/status_transition_validator.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/batchProcessing/BatchApplicationList.tsx
frontend/benefit/handler/src/components/batchProcessing/batchFooter/BatchFooterCompletion.tsx
frontend/benefit/handler/src/components/batchProcessing/useBatches.ts
frontend/benefit/handler/src/pages/batches/index.tsx
frontend/benefit/handler/src/types/batchList.d.ts
frontend/benefit/shared/src/constants.ts
frontend/benefit/shared/src/types/application.d.ts

Use new status field to display changes for rejected Talpa batch / applications.
* Adjust colors for batch that is waiting for payment (metro -> info)
* Display new status icon for  batch that is `rejected_by_talpa` in the information header
* Use `talpa_status` to display success or alert icon on each application if the batch is `rejected_by_talpa`
UI changes already seen and accepted by Susanna.
See new functionality on the last batch of the screenshot:

feat: query for rejected_by_talpa batches and show talpa_status icon for each app

---

frontend/kesaseteli/employer/public/locales/en/common.json
frontend/kesaseteli/employer/public/locales/fi/common.json
frontend/kesaseteli/employer/public/locales/sv/common.json
frontend/kesaseteli/employer/src/components/application/form/TextInput.tsx
frontend/kesaseteli/employer/src/components/application/steps/step2/accordions/EmploymentAccordion.tsx
frontend/kesaseteli/employer/src/hooks/application/useApplicationApi.ts
frontend/kesaseteli/youth/src/components/additional-info-form/AdditionalInfoForm.tsx
frontend/kesaseteli/youth/src/components/youth-form/YouthForm.tsx
frontend/kesaseteli/youth/src/components/youth-form/YouthFormFields.tsx
frontend/shared/src/components/forms/inputs/SocialSecurityNumberInput.tsx
frontend/shared/src/components/forms/inputs/TextInput.tsx
frontend/shared/src/types/input-props.d.ts

Shared frontend code:
- TextInput component
- add autoComplete as input property and use it
- SocialSecurityNumberInput component
- force autoComplete="off" for this input as social security numbers
should not be auto-completed for security reasons
Kesäseteli frontend code:
- turn off autocomplete for the following fields:
- employer UI > employment accordion:
- employee_name
- summer_voucher_serial_number
- employee_ssn (i.e. employee's social security number)
- employee_postcode
- employee_phone_number
- employment_description
- youth UI > application form:
- first_name
- last_name
- social_security_number
- postcode
- phone_number
- email
- youth UI > additional info form:
- additional_info_description
refs YJDH-689
also make the generic error message clearer in Finnish
refs YJDH-689 …

YJDH-689 | feat: don't autocomplete youth/employee's personally identifiable fields

---

frontend/benefit/handler/src/components/applicationReview/employeeView/EmployeeView.tsx
frontend/benefit/handler/src/components/applicationReview/employmentView/EmpoymentView.tsx

Fix two small bugs that cause confusion for the handler.
Working hours was displayed as:
```
Työaika
37,5 Työaika # should be "hours per week"
```
`isLivingInHelsinki` used `associationImmediateManagerCheck` field in condition for yes/no thus only showing up for associations as yes (associationImmediateManagerCheck=true is a requirement).

fix: handler review section bugs (HL-1119)

---

backend/benefit/applications/management/commands/open_cases_in_ahjo.py
backend/benefit/applications/management/commands/seed.py
backend/benefit/applications/services/ahjo_integration.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_ahjo_integration.py
backend/benefit/applications/tests/test_ahjo_requests.py
backend/benefit/applications/tests/test_application_tasks.py

Adds a Django command `open_cases_in_ahjo` which collects applications that are in handling and are not yet sent to Ahjo and sends a open case request for each of them into the AHJO rest api. Adds some suitable test applications into the seeder.
Configure ahjo authentication as instructed [here](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/8392311697/Django+-+AHJO+Rest+API+autentikaation+kuvaus), 
run `python manage.py seed` and then `python manage.py open_cases_in_ahjo` or `python manage.py open_cases_in_ahjo --dry-run` (which does not send anything but shows how many  applications would be sent).
This command should be scheduled first in testing environment as a nightly cron job.
Performance needs to be tested in OpenShift environments, currently the command …

feat: add a command for opening cases in ahjo

---

frontend/kesaseteli/employer/src/components/application/form/TextInput.tsx
frontend/kesaseteli/youth/src/components/youth-form/YouthForm.tsx
frontend/shared/src/types/auto-complete.d.ts
frontend/shared/src/types/common/subset.d.ts
frontend/shared/src/types/input-props.d.ts
frontend/shared/src/types/tests/auto-complete.test.ts

related to:
https://github.com/City-of-Helsinki/yjdh/pull/2767#pullrequestreview-1845768040
Caveats:
- Not exact (i.e. allows combinations not allowed by HTML
specification)
- e.g. "name address-line1" is allowed here but should not be
- "inappropriate for a control" clause in HTML specification is not
handled, which means that this type allows all combinations for all
control groups, i.e. for Date, Month, Multiline, Numeric, Password,
Tel, Text, URL and Username.
- Not complete (i.e. does not allow all combinations allowed by HTML
specification)
- e.g. "section-arbitrary-named-group-name-123" is not allowed here
but should be
autocomplete in HTML specification:
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill
refs YJDH-689 (PR #2767 comment mentioned …

YJDH-689 | feat(shared): add type for autoComplete property in React

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/conftest.py

The reference attribute of the open case JSON needs to be string, not int.

fix: cast open case json reference field to string

---

backend/benefit/applications/enums.py
backend/benefit/applications/services/ahjo_integration.py
backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_ahjo_payload.py

Adds a method for updating an applications files ("records" in AHJO) by sending a PUT request to AHJO Rest API.
Payload is constructed the same way as in open case request  but now  only the "Records"-dict is send and it has a "VersionSeriesId" key/value pair and does not have the "MannerOfReceipt" key/value pair, if the record is for the application itself (the pdf-summary of the application). Example of the payload:
```
{
"records": [
{
"Title": "Hakemuksen liite",
"Type": "hakemuksen liite",
"Acquired": "2023-12-14T10:00:00+02:00",
"PublicityClass": "Salassa pidettävä",
"SecurityReasons": [
"JulkL (621/1999) 24.1 § 25 k"
],
"Language": "fi",
"PersonalData": "Sisältää erityisiä henkilötietoja",
"VersionSeriesId": "{05DC00DB-892E-CC56-A9AF-5B47E8300004}",
"Documents": [
{
"FileName": …
```

Hl 1067 ahjo update

---

backend/benefit/applications/jobs/hourly/hourly_ahjo_job.py
backend/benefit/applications/management/commands/refresh_ahjo_token.py
backend/benefit/applications/services/ahjo_authentication.py

Adds a command that can be schedule to refresh the Ahjo access token hourly.
See [here](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/8392311697/Django+-+AHJO+Rest+API+autentikaation+kuvaus) for details.

Hl 1070 token refresh

---

backend/benefit/applications/api/v1/serializers/ahjo_callback.py
backend/benefit/applications/tests/test_ahjo_integration.py

In case of a failed open case request, the callback message does not have caseGuid and caseId fields, but they were required by the serializer anyways. This PR makes them optional so that the callback is not considered invalid in those cases.

fix: make caseId and caseGuid optional

---

backend/benefit/applications/services/ahjo_payload.py

Calls to Date.isoformat() when creating the open case payload,  in the test environment, return datetime with microseconds like this
`'Acquired': '2023-08-01T12:19:07.935093+00:00'`
which is not compatible with AHJO, this PR limits the precision to seconds
like this
`'Acquired': '2024-01-07T15:51:39+00:00'
`

fix: limit precision to seconds

---

backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/applications/api/v1/views.py
backend/benefit/applications/models.py
backend/benefit/applications/services/change_history.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/locale/en/LC_MESSAGES/django.po
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/sv/LC_MESSAGES/django.po
frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/applicationList/ApplicationList.sc.ts
frontend/benefit/applicant/src/components/applications/applicationList/ApplicationList.tsx
frontend/benefit/applicant/src/components/applications/applicationList/useApplicationList.ts
frontend/benefit/applicant/src/components/applications/forms/application/step5/useApplicationFormStep5.ts
frontend/benefit/applicant/src/components/decisions/DecisionsApplicationList.sc.ts
frontend/benefit/applicant/src/components/decisions/DecisionsApplicationList.tsx
frontend/benefit/applicant/src/components/layout/Layout.tsx
frontend/benefit/applicant/src/hooks/useApplicationsQuery.ts
frontend/benefit/applicant/src/i18n.ts
frontend/benefit/applicant/src/pages/decisions.tsx
frontend/benefit/applicant/src/pages/index.tsx
frontend/benefit/shared/src/constants.ts
frontend/benefit/shared/src/types/application.d.ts

Implements the data retrieval for archived applications in the benefit applicant frontend as well as the related filter and serializer changes in the backend.
Due to the odd issues with the annotation approach that couldn't be solved for now, the logic for determining whether an application is archived is implemented in two different locations instead.

feat: list old processed applications on the archive page (HL-1011)

---

backend/kesaseteli/applications/tests/test_application_validation.py
backend/kesaseteli/applications/tests/test_youth_applications_api.py
backend/shared/shared/common/tests/names.py
backend/shared/shared/common/tests/test_validators.py
backend/shared/shared/common/validators.py
frontend/kesaseteli/youth/src/__tests__/index.test.tsx
frontend/shared/src/__tests__/constants.test.ts
frontend/shared/src/constants.ts

these now accept any other strings except empty/whitespace only strings:
- YouthApplication.first_name
- YouthApplication.last_name
- YouthApplication.school
refs YJDH-661
refs YJDH-661
[YJDH-661](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-661)
[YJDH-661]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YJDH-661 | fix: make name regular expression more permissive

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/Applications.sc.ts
frontend/benefit/applicant/src/components/applications/NoApplications.tsx
frontend/benefit/applicant/src/components/applications/applicationList/ApplicationList.sc.ts
frontend/benefit/applicant/src/components/applications/applicationList/ApplicationList.tsx
frontend/benefit/applicant/src/components/applications/applicationList/ExpandableApplicationList.tsx
frontend/benefit/applicant/src/components/applications/applicationList/PaginatedApplicationList.tsx
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListContents.tsx
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.sc.ts
frontend/benefit/applicant/src/components/applications/applicationList/listItem/ListItem.tsx
frontend/benefit/applicant/src/components/applications/applicationList/useApplicationList.ts
frontend/benefit/applicant/src/components/decisions/DecisionsApplicationList.tsx
frontend/benefit/applicant/src/pages/index.tsx
frontend/benefit/shared/src/types/application.d.ts
frontend/shared/src/utils/__tests__/string.utils.test.ts
frontend/shared/src/utils/string.utils.ts

- Update status styling
- Hide redundant date columns
- Make info needed and draft lists truncated by default and expandable
- Add link to archive page after the submitted applications list
- Update initials to represent the contact person
- Add handling for when there are no applications to show

feat: adjust benefit applicant front page appearance (HL-1108)

---

backend/docker/arm/scripts/base_setup.sh
backend/docker/arm/scripts/setup_app_folder.sh
backend/docker/arm/scripts/setup_apt_packages.sh
backend/docker/arm/scripts/setup_bash.sh
backend/docker/arm/scripts/setup_user.sh
backend/docker/arm/tools/apt-cleanup.sh
backend/docker/arm/tools/apt-install.sh
backend/docker/arm/tools/pip-install.sh
backend/docker/arm/tools/wait-for-it.sh
backend/docker/benefit-arm.Dockerfile
compose.benefit-backend.yml

Currently, MacOS use `amd64` emulation on running backend.
Copy whatever helsinkitest/python:3.9-slim is doing but mount everything on `bookworm`'s `arm` build.
https://hub.docker.com/layers/helsinkitest/python/3.9-slim/images/sha256-2a4ff79cfef2d0681699b53e3780b4cf5b192d66a99f485e29b387e250abb58c?context=explore
Usage:
`docker compose -f compose.benefit-backend.yml up --build`

feat: rip helsinkitest/python:3.9-slim to run backend on arm

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationForm/companySearch/useCompanySearch.ts
frontend/benefit/handler/src/components/applicationForm/useApplicationForm.ts
frontend/benefit/handler/src/constants.ts
frontend/benefit/handler/src/hooks/useFormActions.tsx

Fix an issue with calculation and pay subsidies showing wrong if any of these change:
* Pay subsidy type
* Apprenticeship yes/no
Also sets new expense information (salary, vacation expenses, other expenses) as calculation defaults.

fix: calculation and pay subsidies would not reset if changed on edit (hl-1110, hl-1127, hl-1130) 

---

backend/benefit/applications/tests/factories.py

Close unclosed `<p>`-tag in factory that is used for testing decision proposals.

fix: unclosed p-tag

---

backend/benefit/applications/api/v1/ahjo_integration_views.py
backend/benefit/applications/tests/test_ahjo_integration.py

Add handling for the callback received from Ahjo after updating application / records.
Basically almost the same as the callback after opening a case, except there is not any case id or case Guid in the callback payload.

feat: handle update record callback

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationForm/formContent/FormContent.tsx
frontend/benefit/handler/src/components/applicationForm/reviewChanges/ReviewEditChanges.tsx
frontend/benefit/handler/src/components/applicationForm/reviewChanges/utils.ts
frontend/benefit/handler/src/components/applicationForm/utils/applicationForm.ts
frontend/benefit/handler/src/components/applicationReview/consentView/ConsentView.tsx
frontend/benefit/handler/src/components/applicationReview/employeeView/EmployeeView.tsx
frontend/benefit/handler/src/components/applicationReview/employmentView/EmpoymentView.tsx
frontend/benefit/handler/src/components/reviewSection/ReviewSection.sc.ts

* Add / delete one or more applicant consents from handler edit view
* Do not display paper application date diff in _edit changes review_ if origin is `applicant`
* Includes some small fixes that were left from hl-1062

refactor: move applicant consent to edit view (hl-1171)

---

frontend/benefit/handler/src/hooks/useFormActions.tsx

Just reset all training compensations when submitting an application.

fix: training compensations removed from calculation (hl-1165)

---

backend/benefit/helsinkibenefit/settings.py

The default outgoing email address was changed to the no-reply one.
The environment variable for the yjdh-helsinkilisa-api-testing pipeline has also been changed. Changes to the rest of the API pipelines are pending the approval of this change.

chore: update default outgoing email address (HL-1145)

---

backend/benefit/applications/services/ahjo_payload.py

Do not send the decision XML attachments when opening a case. In a real world scenario, these cannot exist when a case is opened, but better to be sure.

fix: exclude xml attachments from open case

---

backend/benefit/applications/services/ahjo_payload.py

Records key should be "records" in lowercase for AHJO.

fix: Records in update dict to lowercase

---

backend/benefit/calculator/rules.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryBenefitCalculatorView.tsx
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryCalculatorResults/SalaryCalculatorResults.tsx
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/useSalaryBenefitCalculatorData.ts
frontend/benefit/handler/src/hooks/useHandlerReviewActions.ts

I'm about to make big changes on how the application is handled when moving towards Ahjo. Handling to accepted or rejected state will have three steps instead of just one. The calculator has been buggy and I have to make sure that it's ok before moving further from step 1.
* Handle calculator error 500 instead of crashing the app
* Raise error instead of fatally assert crash in Django
* Do not show certain calculator elements if calculator state is not 💯  ✅

fix: various calculator fixes and tweaks

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationForm/actionBar/ActionBarEdit.tsx
frontend/benefit/handler/src/components/applicationForm/formContent/attachmentsList/AttachmentsList.tsx
frontend/benefit/handler/src/components/applicationForm/formContent/attachmentsList/useAttachmentsList.ts
frontend/benefit/handler/src/components/applicationForm/useApplicationForm.ts
frontend/shared/src/components/attachments/AttachmentsList.tsx

Add a couple of missing nags with `window.confirm()`. It's lacking the cool HDS modal styles but at least it's working 😏  
Also set default paper application date if it's untouched.

fix: require confirmation on attachment removal and when cancelling edit

---

backend/benefit/locale/fi/LC_MESSAGES/django.po

Shorten the salary benefit finnish translation from "Palkan Helsinki-lisä" to "Helsinki-Lisä".

feat: remove "Palkan" from salary benefit locale

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json

Missing localizations added.
commissionAmount is not anymore in use, but it was seen in one test case showing
changes.fields.commissionAmount.label:
(tyhjä)->(tyhjä)

fix: localization keys added to change messages hl-1213

---

frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/utils/validation.ts
frontend/benefit/handler/browser-tests/pages/1-new-application.testcafe.ts
frontend/benefit/handler/browser-tests/pages/2-edit-application.testcafe.ts
frontend/benefit/shared/src/utils/dates.ts
frontend/shared/src/utils/date.utils.ts
frontend/shared/src/utils/file.utils.ts

Just noticed some bad import practice with date-fns and thought I'd make a change. There's still date-fns dependency in HDS that imports the whole lib, thus having two versions of date-fns in the bundle.

fix: import date-fns properly

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_ahjo_payload.py

AHJO UI has a 151 character limit for the case title, this PR makes the title shorter so it should fit into that limit.

Hl 1140 ahjo title

---

backend/benefit/applications/admin.py

Add decision texts to Django Admin

feat: add decision texts to Django admin

---

backend/benefit/requirements.txt

Prepare for new authorization tech by updating helusers library. I've tested this on localhost and authentication works just like before on both handler and applicant (with `NEXT_PUBLIC_MOCK_FLAG=0` ofc).

chore: bump django-helusers to 0.11.0

---

backend/benefit/applications/services/ahjo_integration.py
backend/benefit/applications/tests/test_ahjo_integration.py

Deleting / cancelling a case in AHJO was missing a couple of query parameters, this PR
adds the params so that the query is done with a query string like this:
`https://ahjohyte.hel.fi:9802/ahjorest/v1/cases/HEL%202024-000091?draftsmanid=kissa123&reason=applicationretracted&apireqlang=fi`

fix:  missing query parameters for AHJO delete

---

backend/benefit/applications/services/ahjo_integration.py
backend/benefit/applications/services/ahjo_xml_builder.py
backend/benefit/applications/templates/secret_decision.xml
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/factories.py
backend/benefit/applications/tests/test_ahjo_decisions.py
backend/benefit/applications/tests/test_ahjo_integration.py
backend/benefit/applications/tests/test_ahjo_xml_builder.py
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/sv/LC_MESSAGES/django.po

[HL-1207](https://helsinkisolutionoffice.atlassian.net/browse/HL-1207?atlOrigin=eyJpIjoiYWZhYmYzNjIyYWUyNDk5MzhiYjU0ZmNlZTYxMDIxYTMiLCJwIjoiaiJ9) format the secret decision XML according to the new design (see screenshots).
Refactor the XML building to a class, as ahjo_integration.py is already doing way too much stuff.
Add more tests for the XML strings.
[HL-1242](https://helsinkisolutionoffice.atlassian.net/browse/HL-1242?atlOrigin=eyJpIjoiMmFkOGRlYmVjYWIyNGIwOTljNzExNDBkZTZlMTEzMjMiLCJwIjoiaiJ9) Rename the generated XML files to format requested by AHJO.
`pytest applications/tests/test_ahjo_xml_builder.py`
To manually check what kind of XML files are created run
`python manage.py shell_plus`
`from applications.services.ahjo_integration import generate_application_attachment`
`from …

feat: secret xml attachment as per the  new design

---

backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/applications/models.py
backend/benefit/applications/tests/test_applications_api.py

Only includes the old batch based solution as discussed. Checks for both this and for applicant-side archive status according to the new Ahjo integration will be implemented later.

fix: defer accepted/rejected status until the decision has been accepted in Ahjo (HL-1241)

---

backend/benefit/applications/tests/before_after.py
backend/benefit/applications/tests/test_ahjo_integration.py
backend/benefit/applications/tests/test_application_batch_api.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/applications/tests/test_applications_report.py

Get rid of seeding issues. Sometimes we're running into unique constrains when factory generates similar objects in CI. Prevent that by using a "before each" reseed function. 
Reseed itself uses the test file's name as time is frozen and `random` gives the tame value every time.
Idea is that you'd use a snippet for a file once a test starts acting out:
```
@pytest.fixture(autouse=True)
def run_before_and_after_tests():
from applications.tests.before_after import before_test_reseed
before_test_reseed(["test_skip_this_test_definition"])
yield  # actual test run
```
That way the reseeding is controlled and can be enabled for each test case. A single test can also be excluded from reseed by giving `before_test_reseed` a list of test names (here, `test_skip_this_test_definition`). This gives …

test(backend): option to reseed each test file and single test

---

frontend/benefit/applicant/src/components/applications/forms/application/step2/ApplicationFormStep2.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step5/useApplicationFormStep5.ts
frontend/benefit/applicant/src/components/applications/forms/application/step6/useApplicationFormStep6.ts
frontend/benefit/applicant/src/hooks/useDependentFieldsEffect.ts

Clicking pay subsidy and apprenticeship selection in GUI resulted to situation where apprenticeship is required even if pay subsidy type is selected as "no pay subsidy". Force the value to the backend as selecting null with formik/yup/radio is a serious PITA. 
Also removed some old code from days when there were more benefit types than just 1 (salary).

fix: no apprenticeship information should be required for applicant without pay subsidy (HL-1257)

---

frontend/benefit/handler/src/components/applicationForm/utils/validation.ts

Use same validation as in #2908

fix: validation minimum for start date should be 4 months earlier, not today (HL-1224)

---

backend/benefit/applications/templates/secret_decision.xml

Justify two th elements to the right in the secret xml attachment.

fix: justify th elements to the right

---

frontend/benefit/applicant/browser-tests/page-model/ApplicantPageComponent.ts
frontend/benefit/applicant/browser-tests/page-model/step1.ts
frontend/benefit/applicant/browser-tests/page-model/step2.ts

Make applicant tests run a bit faster by using a function that has fewer browser input steps. Also remove the nag that is caused because of masking the radio button's native `<input>`.

Test improvements

---

backend/benefit/applications/services/change_history.py

Hotfix to show something more than "empty" when uploading new files by applicant when status is "additional_information_required".

fix: show filename on change set when applicant adds a new file

---

backend/benefit/README.md
backend/benefit/applications/api/v1/serializers/attachment.py
backend/benefit/applications/enums.py
backend/benefit/applications/templates/application.html
backend/benefit/helsinkibenefit/settings.py
backend/benefit/locale/en/LC_MESSAGES/django.po
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/sv/LC_MESSAGES/django.po

`makemessages` and `compilemessages` didn't catch some of the translations that were called programmatically using enum as `msgid`. This brought problems least in application print - both in applicant gui and new ahjo process.  Invoke `gettext` to register them.

chore: fix missing backend translations

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/sidebar/ChangeList.tsx

Add a "empty state" to handler sidebar if there's no changes detected.

feat: add 'empty' text to unchanged app's change set

---

backend/benefit/applications/management/commands/refresh_ahjo_token.py
backend/benefit/applications/services/ahjo_authentication.py
backend/benefit/applications/services/ahjo_integration.py
backend/benefit/applications/tests/test_ahjo_authentication.py

The retrieval of the AHJO rest api access token was previously failing because the expiration date was based on created_at and the token  refresh was updating an existing token which kept the create_at date unchanged. This PR changes the logic so that an access token is only ever created and custom exceptions are raised if anything token-related is not behaving as intended or is configured incorrectly. 
Also adds `expiry_datetime()` and `has_expired()` methods and a  new string representation for the `AhjoToken` class, which can be used in error logs etc.
With (huolto.hel.fi) BIG-IP EDGE VPN turned on:
Get an ahjo code from  [here](https://johdontyopoytahyte.hel.fi/ids4/Account/Login?ReturnUrl=%2Fids4%2Fconnect%2Fauthorize%2Fcallback%3Fscope%3Dopenid%2520offline_access%26response_type%3Dco …

fix: failing ahjo token refresh

---

backend/benefit/applications/management/commands/create-proposal-drafts.py

Tool to create missing proposal drafts for older applications.
0. have some old applications or create with `python manage.py seed --number=10`
1. `git checkout main && git pull`
2. migrate by restarting backend docker container
3. run `python manage.py create-proposal-drafts`
4. you can re-run command by removing created rows from `bf_applications_decision_proposal_draft` table

chore: add a migration command to create needed proposal drafts

---

frontend/benefit/handler/src/components/applicationForm/formContent/companySection/deMinimisAid/utils/validation.ts
frontend/benefit/handler/src/constants.ts

Previously, paper filled application's de minimis row's date could be filled with arbitrary numbers like 111 and the parsing would fail completely, leaving blank value to the row. 
Copy & paste behaviour from applicant's validation schema 😅 🪄 🎩 🐰  works like a charm.

fix(handler): de minimis date validation as in applicant form (HL-1204)

---

frontend/benefit/applicant/src/components/applications/forms/application/deMinimisAid/list/useDeminimisAidsList.ts
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationForm/formContent/companySection/deMinimisAid/DeMinimisAidForm.tsx
frontend/benefit/handler/src/components/applicationForm/formContent/companySection/deMinimisAid/utils/validation.ts
frontend/benefit/handler/src/components/applicationForm/useApplicationForm.ts
frontend/benefit/handler/src/constants.ts
frontend/benefit/handler/src/context/DeMinimisContext.tsx
frontend/benefit/handler/src/context/DeMinimisProvider.tsx

Add validation for handler's de minimis form when creating a new application.

feat(handler): add error validation logic and toast for de minimis aid form (HL-1202)

---

backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/applications/management/commands/set_cancelled_as_archived.py
backend/benefit/applications/tests/factories.py
backend/benefit/applications/tests/test_command_set_as_archived.py

Previously, the cancelled applications where queried for but not marked for archieved. Mark them as archived to that filter works like intended.
I've also added a command which goes through all cancelled apps and marks them as archived:
`python manage.py set_cancelled_as_archived`

fix(handler): archived page to show cancelled applications (hl-1287)

---

backend/benefit/applications/admin.py

Add application's ahjo statuses to the Application view in Django admin

feat: add ahjo_status to Django admin

---

backend/benefit/applications/services/ahjo_xml_builder.py
backend/benefit/applications/tests/test_ahjo_xml_builder.py

Cast all benefit numbers in the decision XML as integers to remove decimal zeroes.

feat: cast row amounts to integers

---

backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/applications/api/v1/serializers/batch.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationHeader/ApplicationHeader.tsx
frontend/benefit/handler/src/components/applicationList/ApplicationList.sc.ts
frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/components/applicationList/HandlerIndex.tsx
frontend/benefit/handler/src/components/applicationList/useApplicationListData.ts
frontend/benefit/handler/src/components/batchProcessing/useApplicationsHandled.ts
frontend/benefit/handler/src/components/header/Header.tsx
frontend/benefit/handler/src/components/header/TemporaryAhjoModeSwitch.tsx
frontend/benefit/handler/src/components/header/useHeader.ts
frontend/benefit/handler/src/hooks/useApplicationsQuery.ts
frontend/benefit/shared/src/types/application.d.ts

* Move ahjo mode toggle to main `<Header>` as custom item
* Fork from default behaviour index to `<HandlerIndex />`
* New fork has some changes on how to filter the apps to the list, `<ApplicationsHandled>` is no longer used
* Some changes to API: allow filtering for `ahjo_case_id`
* Add color to application status `<Tag>`

feat: prepare handler application index for new ahjo integration (hl-1278)

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/test_ahjo_payload.py

Ahjo adds a date also to the title for the application record, so we remove the date from the JSON payload.

feat: remove date from application record title

---

frontend/benefit/applicant/package.json
frontend/benefit/handler/package.json
frontend/kesaseteli/employer/package.json
frontend/kesaseteli/handler/package.json
frontend/kesaseteli/youth/package.json
frontend/tet/admin/package.json
frontend/tet/youth/package.json

e.g. Windows needs cross-env to handle setting environment variables in package.json scripts
refs YJDH-697 (noticed cross-env being used inconsistently)

fix(frontend): use cross-env in scripts to make them cross-platform

---

frontend/benefit/applicant/package.json
frontend/benefit/handler/package.json
frontend/kesaseteli/employer/package.json
frontend/kesaseteli/handler/package.json
frontend/kesaseteli/youth/package.json
frontend/tet/admin/package.json
frontend/tet/youth/package.json

**This reverts PR** #2964!
This reverts commit 7307e5797d6b0a0bc24eded97d6724a5724a4547
refs YJDH-697 (noticed the missing cross-env uses)

(Revert PR #2964) fix(frontend): don't use cross-env in scripts, didn't work in pipelines

---

backend/benefit/applications/services/ahjo_decision_service.py

Add missing function call to populate justification text $variables with appropriate values.

fix: enable justification text variable replacement (hl-1290)

---

frontend/kesaseteli/handler/public/locales/fi/common.json
frontend/kesaseteli/handler/src/components/form/ActionButtons.tsx
frontend/kesaseteli/handler/src/components/form/HandlerForm.tsx
frontend/kesaseteli/handler/src/components/form/VtjInfo.tsx
frontend/kesaseteli/handler/src/constants/vtj-exceptions.ts
frontend/kesaseteli/shared/src/types/youth-application.d.ts
frontend/shared/src/utils/mask-gdpr-data.ts

TODO:
- Add UI for creating youth applications without social security number
refs YJDH-697 (handler UI for showing/accepting/rejecting)
[YJDH-697](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-697)
Local testing:
- checkout the PR's branch
- `cp .env.kesaseteli.example .env.kesaseteli`
- Terminal 1:
- `docker compose -f compose.employer.yml up --build` to spin up **backend** at `localhost:8000`
- The employer docker compose file is the least resource heavy docker compose file that spins up the Kesäseteli API so that's why using it
- Terminal 2:
- `docker exec -it kesaseteli-backend bash` to enter backend
- `python manage.py shell_plus` to start Django shell inside backend
- `from common.tests.factories import *`
- `str(AcceptableNonVtjYouthApplicationFactory(non_vtj_home_munici …

YJDH-697 | feat(ks-handler): show/accept/reject youth applications that have no SSN

---

backend/benefit/applications/services/ahjo_decision_service.py
backend/benefit/applications/tests/test_ahjo_decisions.py
frontend/benefit/handler/src/components/applicationReview/CalculationReview.tsx

Remove cent fractions from benefit calculation when making a decision for application.

fix: do not show cents for benefit amount (hl-1294)

---

frontend/.gitignore

refs YJDH-697 (noticed the need for adding this file to .gitignore)

chore: add tsconfig.tsbuildinfo to frontend/.gitignore

---

backend/benefit/applications/api/v1/serializers/attachment.py
compose.benefit-backend.yml
frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/step3/attachmentsList/useAttachmentsList.ts
frontend/shared/src/components/toast/show-error-toast.ts

Not implemented by the design as this would have resulted to a bigger effort.
* Upload error notifications can be set to dismiss later than after 5 seconds
* Improvements to error notifications:
* In case of malwared file: report the malware
* In case of malformed file: show _Epäkelpo PDF/kuvatiedosto. Lataamasi tiedosto on viallinen. Tarkistathan että tiedostomuoto on oikea eikä sen koko ylitä sallittua maksimikokoa._
* In case of unknown upload problem: show generic error notification
* Cleanup: remove frontends from backend compose file

feat: enhance error notifications when uploading malformed or malwared file (hl-1267)

---

backend/benefit/applications/jobs/quarter_hourly/quarter_hourly_ahjo_job.py
backend/benefit/applications/models.py
backend/benefit/applications/tests/test_ahjo_integration.py

Fix quarter hourly jobs so that decision request is run only once instead of twice.
Adjust the query for decision request so that it will fetch applications  which have been `accepted` or` rejected`, their talpa status is `not_processed_by_talpa`, they have a `ahjo_case_id`, a `decisiontext` and their **latest** `ahjo_status` is `case_opened`.

Hl 1300 automation fix

---

backend/benefit/applications/api/v1/application_batch_views.py
backend/benefit/applications/api/v1/serializers/batch.py
frontend/benefit/applicant/browser-tests/pages/company.testcafe.ts
frontend/benefit/handler/src/components/applicationList/HandlerIndex.tsx
frontend/benefit/handler/src/pages/index.tsx

Filter out ahjo integration batches in views, not just the applications.

fix: filter batches using auto_generated_by_ahjo value (hl-1304)

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/test_ahjo_payload.py

Fix missing ahjo_version_series_id when sending update records request to Ahjo.

fix: send ahjo_version_series_id in update payload

---

backend/benefit/applications/models.py
backend/benefit/applications/tests/test_ahjo_integration.py

Query only the applications that have a ahjo_case_id AND that have one or more attachments that are not downloaded by Ahjo.

fix: query for the undownloaded attachments

---

backend/benefit/applications/api/v1/ahjo_decision_views.py
backend/benefit/applications/tests/test_ahjo_decision_proposal_drafts.py

Wrap the decision text parts in
`<section id="paatos"><h1>{_("Päätös")}</h1></section>`
and 
`<section id="paatosteksti"><h1>{_("Päätöksen perustelut")}</h1></section>`
as required by the schema, when saving the decision into the database.

fix: add missing tags when saving decision text

---

backend/benefit/applications/admin.py
backend/shared/shared/audit_log/admin.py

Some adjustments to make the admin panel more convenient when testing application batches and AHJO-integration.
Remove ssn from the employee page as it's not really needed there.

Hl 1306 admin changes

---

backend/benefit/applications/management/commands/seed.py
frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/header/useHeader.ts

* Add a few dummy messages with seed tool
* Display chat toggle in header on "accepted", "rejected" status
New chat messages are disabled for now for the "accepted" and "rejected" status. To allow this in backend, serializer validation might require some attention.
Later, one can allow new chat in frontend, look for line
```const canWriteNewMessages = !application?.batch;```
and change it according to need.

feat(applicant): display chat icon in app view for statuses "accepted", "rejected" (hl-1292)

---

backend/benefit/applications/api/v1/ahjo_integration_views.py
backend/benefit/applications/tests/test_ahjo_integration.py

Ahjo gets confused if the Helsinki-lisä responds to a failing callback request with 400 Bad request, so the 
response status needs to be changed to 200 OK.

feat:  change failure response to ahjo as 200 ok

---

backend/benefit/messages/serializers.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/header/Header.tsx
frontend/benefit/handler/src/components/sidebar/Messages.tsx
frontend/benefit/shared/src/types/application.d.ts
frontend/shared/src/components/messaging/Message.tsx
frontend/shared/src/components/messaging/Messaging.sc.tsx

Handler messenger displays the status of seen by applicant when applicant has read the message.

feat(handler): add seen by applicant in the messaging bar

---

backend/benefit/applications/management/commands/send_ahjo_requests.py
backend/benefit/applications/models.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_ahjo_integration.py

The previous version of the query that  fetches the applications for open case request only queried applications in handling status, which could result in a scenario in where a handler handles an application before it has been picked up for open case request and it's status had changed into decided or rejected and it would not be picked up for future open case requests.
This PR fixes the query so that it includes applications which are handled but do not yet have an ahjo_case_id.

fix: query handled applications for open case

---

backend/benefit/applications/models.py
backend/benefit/applications/tests/test_ahjo_integration.py

[HL-1347](https://helsinkisolutionoffice.atlassian.net/browse/HL-1347?atlOrigin=eyJpIjoiNGJlNTNhZjU3MTQ4NGY4NGJhYjZmMTEyZTA4MjdlNzkiLCJwIjoiaiJ9)
Ahjo decision texts were not sent for applications that had new attachments uploaded after open case request, because their latests ahjo_status was `new_record_received`. This PR modifies the query for decision requests to include applications with that status as well.
[HL-1347]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: send decision also after new records are sent

---

backend/benefit/applications/api/v1/serializers/application_alteration.py
frontend/benefit/handler/src/components/alterationHandling/useAlterationHandlingForm.ts

It looks like I broke the submit button in the last PR by accident at the last minute while fixing a code quality violation reported by sonarcloud.
I basically went from `handleAlteration: formik.submitForm` to `handleAlteration: () => void formik.submitForm` which actually doesn't call the function anymore.

fix: nonfunctional alteration submission and misc. oversights in date overlap detection

---

backend/benefit/applications/admin.py

[HL-1306
](https://github.com/City-of-Helsinki/yjdh/pull/3048)
caused some admin fields for application to go missing.
This PR makes them visible again.

fix: return missing admin fields

---

backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/applications/tests/test_applications_api.py
frontend/benefit/applicant/src/components/header/useHeader.ts
frontend/benefit/shared/src/types/application.d.ts

[HL-1329](https://helsinkisolutionoffice.atlassian.net/browse/HL-1329?atlOrigin=eyJpIjoiNjYyMjExOTU5M2Q2NGZhYzk0ZDJmY2FhYmYyM2EyYmYiLCJwIjoiaiJ9)
Fixes the issue where an applications that has a batch has been opened for the application for editing and updating the application fails as the backend expects a Dict for the update request and receives a boolean instead.
[HL-1239]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HL-1329]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: batch in applicantApplication error

---

backend/benefit/applications/api/v1/serializers/application.py
frontend/benefit/applicant/src/components/applications/forms/application/step2/useApplicationFormStep2.ts
frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/__tests__/dates.test.ts
frontend/benefit/handler/src/components/applicationForm/utils/applicationForm.ts
frontend/benefit/shared/src/utils/dates.ts

* Check if user is staff and skip some of the date validation in application serializer
* Remove some deprecated `BENEFIT_TYPE` code
This new behaviour will lead to a rare case bug where:
* handler edits application and  sets start and end dates wildly over the applicant's date range options
* handler sets application to additional information is required from applicant
* applicant then goes to form -> start and end date field cannot be saved as the fields are now invalid
I'll write a new bug ticket to JIRA when this is merged. We'll have to ask the stakeholders if this is ok or if the issue should be covered.

chore: loosen validation on application start/end dates (hl-1324 & hl-1174)

---

backend/benefit/applications/services/ahjo_xml_builder.py
backend/benefit/applications/templates/secret_decision.xml
backend/benefit/applications/tests/test_ahjo_xml_builder.py

[HL-1353](https://helsinkisolutionoffice.atlassian.net/browse/HL-1353?atlOrigin=eyJpIjoiNzAzZDAxYmNlODM0NGU3OGI4MmQ4MGUwMWQ2YTQwYzAiLCJwIjoiaiJ9)
Fix for error that occurs when AhjoXMLBuilder tries to generate a secret xml attachment for a rejected application that has no calculation.
[HL-1353]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: no calculation data for rejected applications

---

backend/benefit/applications/api/v1/ahjo_integration_views.py
backend/benefit/applications/tests/test_ahjo_integration.py

Update application.status as cancelled after application has been succesfully marked as cancelled in Ahjo.

feat:  cancelled status after ahjo delete callback

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/test_ahjo_payload.py

Full application was missing from the attachments sent in open case request, this PR includes it in the payload.

fix: excluded full_application attachment

---

frontend/benefit/applicant/src/hooks/useApplicationsQuery.ts

This adds the archive status into the query key in the query hook for the application list in the applicant UI. Previously, lists that shared the other query values but not this one would share their state.
Before this fix, this happened with the processed applications list on the front page and the list on the archive page. If one navigated between the aforementioned pages by using the "show all applications" button, before the archived applications list finished loading, the view would show the list from the front page for a brief period (which was minimal in development environment) instead of a loader skeleton element as intended.

fix: include archive status flag in application list query key

---

backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/api/v1/serializers/application.py

Previously, cancelled applications stayed on the applicant's front page view forever. After this patch, applications will move to the archive page immediately after they are cancelled.

fix: move cancelled applications to archive page (HL-1321)

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/alterationHandling/AlterationHandlingForm.tsx
frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/HandlingApplicationActions.tsx
frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/HandlingApplicationActionsAhjo.tsx
frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/useHandlingApplicationActions.ts
frontend/benefit/handler/src/components/sidebar/ChangeList.tsx
frontend/benefit/handler/src/components/sidebar/Sidebar.tsx
frontend/benefit/handler/src/components/sidebar/useSidebar.ts

- Notes can now be added even if the application has been handled
- The sidebar is now available in the alteration handling view

feat: extend access to handler sidebar notes (HL-1343)

---

frontend/benefit/handler/src/hooks/useCreateApplicationAlterationQuery.ts

The previous version somehow worked in development environment even though it shouldn't have, presumably because of the auth mock flag.

fix: use correct API endpoint for alteration creation for handler

---

backend/benefit/applications/models.py
backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_ahjo_integration.py

[HL-1361](https://helsinkisolutionoffice.atlassian.net/browse/HL-1361?atlOrigin=eyJpIjoiY2Q5NDcyMzg0MmU5NDM5ZTliNzdhZTJkOGEzMTQxMjQiLCJwIjoiaiJ9)
This time ensure, that the full application attachment is included in the pre fetch query, where it was not previously included.
[HL-1361]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Hl 1361 missing full application

---

backend/benefit/applications/api/v1/serializers/application.py

Application.ahjo_case_id (Diaarinumero) was not read_only, so in some scenarios, the frontend could update it as None which is not what we want ever.

fix: make ahjo_case_id read_only

---

frontend/benefit/handler/src/components/alterationHandling/AlterationCalculator.tsx

Previously, by setting the recovery calculator dates for an alteration to both start and end on the very first or last date of any row of the original calculation, the handler would receive an erroneous calculation of €0 since the row was not detected to intersect with the single-day range correctly.

fix: handle single-day alteration calculation on row terminus date correctly

---

frontend/benefit/applicant/src/components/header/useHeader.ts

Closing the sidebar changed the isMessagesDrawerVisible value, which was a dependency for the same useEffect that was responsible for opening it upon the query parameter in the first place. Now that function is isolated into its own useEffect and doesn't get rerun.

fix: fix applicant messager drawer refusing to close in some cases

---

backend/benefit/applications/api/v1/ahjo_integration_views.py
backend/benefit/applications/management/commands/send_ahjo_requests.py
backend/benefit/applications/services/ahjo_client.py
backend/benefit/applications/services/ahjo_integration.py

[HL-1365](https://helsinkisolutionoffice.atlassian.net/browse/HL-1365?atlOrigin=eyJpIjoiYTZiZjAwYzQ4NDU5NDEzNDliNDU1YTAwNjUzZWE1ZTMiLCJwIjoiaiJ9)
Improve logging and errors by printing timestamp and application number.
[HL-1363](https://helsinkisolutionoffice.atlassian.net/browse/HL-1363?atlOrigin=eyJpIjoiYzAyMjJjOWJiYzk2NDlmOWFlNzE2NGE4ODYyMDU3YjQiLCJwIjoiaiJ9)
When one AhjoRequest failed, the rest of the requests were not sent, this PR handles the exceptions so that the execution continues after an error is encountered and logged,this should also fix [HL-1366](https://helsinkisolutionoffice.atlassian.net/browse/HL-1366?atlOrigin=eyJpIjoiNDI2YjBmMmZjMTA3NDI1NmI3NzI0MGJhZjNiYjUzOTUiLCJwIjoiaiJ9) where PUT requests were not executed if one failed.
[HL-1365]: …

feat: HL 1365 improve logging, HL-1363 don't block ahjo requests

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/test_ahjo_payload.py

[HL-1364](https://helsinkisolutionoffice.atlassian.net/browse/HL-1364?atlOrigin=eyJpIjoiZDEwZjA3NGQ4NjQ3NDNhZWFhN2ExYmViZjg3ODE5ZTIiLCJwIjoiaiJ9)
Truncate company name in open case payload title if it is longer than 100 characters, because currently Ahjo cannot handle company names longer that 100 characters.
[HL-1364]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: truncate company name in open case request

---

backend/shared/shared/audit_log/tests/test_audit_logging.py
backend/shared/shared/common/tests/conftest.py

RemovedInDjango50Warning:
- The django.utils.timezone.utc alias is deprecated.
Please update your code to use datetime.timezone.utc instead.
refs YJDH-696
[YJDH-696](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-696)
Ran the shared backend tests locally in docker and they passed:
```bash
pytest --pyargs shared -vv
...
=== 665 passed, 9 warnings in 8.04s ===
```
[YJDH-696]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: django 5 deprecation warning by using datetime.timezone.utc

---

backend/kesaseteli/requirements-dev.txt
backend/kesaseteli/requirements.in
backend/kesaseteli/requirements.txt

elasticsearch was upgraded to v8 as part of PR #3157
"Upgrade Django to 4.2 & all dependencies except black/isort/flake8",
After merging that PR the quarter hourly cronjobs running send_audit_log
using `manage.py runjobs quarter_hourly` started failing:
```
ERROR OCCURED IN JOB: send_audit_log (APP: shared.audit_log)
TypeError: '<' not supported between instances of 'str' and 'int'
```
Similar Elasticsearch v7 downgrade was done for Helsinki benefit
application in PR #1942:
- https://github.com/City-of-Helsinki/yjdh/pull/1942
refs YJDH-696 (after elasticsearch v8 upgrade audit log sending failed)

YJDH-696 | Downgrade Kesäseteli's Elasticsearch to v7 to fix sending audit logs

---

frontend/Dockerfile
frontend/Dockerfile-localdevelopment
frontend/README.md

refs YJDH-696 (dev/test pipelines fail most of the time without this)
[YJDH-696](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-696)
[YJDH-696]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use Red Hat UBI image node.js v18 in frontends' shared Dockerfile

---

backend/docker/kesaseteli.Dockerfile

When trying to /saml2/login/ there was error
"Error: unable to load xmlsec-openssl library".
refs YJDH-696
[YJDH-696](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-696)
[YJDH-696]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YJDH-696 | Fix SAML2 login, xmlsec1-openssl library was missing

---

backend/benefit/messages/tests/test_api.py
backend/benefit/messages/views.py
frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/useHandlingApplicationActions.ts
frontend/benefit/handler/src/components/sidebar/Sidebar.tsx
frontend/benefit/handler/src/context/AppContext.tsx
frontend/benefit/handler/src/context/AppContextProvider.tsx
frontend/benefit/handler/src/layout/Layout.sc.ts
frontend/benefit/handler/src/layout/Layout.tsx
frontend/benefit/handler/src/pages/_app.tsx
frontend/shared/src/components/drawer/Drawer.sc.tsx

* Sidebar now pushes main content to the left when drawer is opened. 
* This results to a better view when handling application. Content now remains readable and is not hidden by the sidebar.
* As a bonus, mark as unread now works even though the handler had already sent a message in between.

feat: offset application content when sidebar is open (hl-1200)

---

backend/benefit/applications/services/ahjo_xml_builder.py
backend/benefit/applications/tests/test_ahjo_xml_builder.py

Ahjo cannot handle commas in filenames, so we remove the commas from the auto-generated decision xml-files.

fix: remove comma from xml filenames

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/pageContent/PageContent.tsx
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationReview/handlingView/HandlingStep1.tsx
frontend/benefit/shared/src/components/decisionSummary/DecisionSummary.tsx
frontend/benefit/shared/src/types/application.d.ts
frontend/shared/src/components/forms/section/FormSection.sc.ts

This removes all fields related to monetary matters from the decision box for applications that are rejected, cancelled, or waiting for input from the applicant. It also changes the default visibility of the decision box to be shown for cancelled and rejected applications (first of which should rarely if ever have an Ahjo case ID in a real world scenario), and adds translation strings for an application that's waiting for additional details (in this case the Ahjo case ID should be present for the box to be shown).

fix: remove irrelevant fields from decision box etc. (HL-1332, HL-1371, HL-1380)

---

backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/applications/api/v1/serializers/application_alteration.py
frontend/benefit/handler/src/components/applicationList/ApplicationList.sc.ts
frontend/benefit/handler/src/components/applicationsArchive/ApplicationArchiveList.tsx
frontend/benefit/handler/src/components/applicationsArchive/useApplicationsArchive.ts
frontend/benefit/shared/src/types/application.d.ts

* Add number of alterations
* Background is blue if any alteration is of unhandled state (`["received", "opened"])`, otherwise greyed out (`["cancelled", "handled]`) 
* In screenshot, the top two applications have alterations, which the top one has one alteration in `received` state and the second application has two alterations with only `cancelled` or `handled` alterations.

feat: add alteration count and state to archive listing

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/test_ahjo_payload.py

Ensure that the ahjo case title is  no more than 100 characters long  by truncating the company name if necessary.

fix: trim the ahjo case title to 100 characters

---

backend/benefit/applications/services/ahjo_integration.py

delete_request_sent was not saved as the latest ahjo_status after a delete request is sent to Ahjo.

fix: missing delete_request_sent ahjo_status

---

frontend/benefit/handler/src/components/applicationReview/handledView/HandledView.tsx

Add row **amount per month** for manual calculation when reviewing an accepted application. Screenshot's left side has the added row. On the right is the normal calculation.

fix: add monthly pay for manual calculation for accepted application

---

frontend/audit-ci.jsonc
frontend/benefit/applicant/package.json
frontend/benefit/handler/package.json
frontend/benefit/shared/package.json
frontend/yarn.lock

Your average security audit fail fix. Bump Axios for benefit, leave tet and kesäseteli unpatched.
More info at [https://github.com/advisories/GHSA-8hc4-vh64-cxmj](https://github.com/advisories/GHSA-8hc4-vh64-cxmj)

chore: upgrade axios and ignore audit nag in tet / ks

---

frontend/benefit/handler/src/hooks/useFormActions.tsx

**Previously**
Training compensation was left in TODO when edit was introduced. Training compensation entries would get erased when editing application, no matter which field. 
**Resolution**
Editing an application retains calculation's training compensation on save. Training compensation is only erased if apprenticeship is toggled off.

fix: retain training compensation on edit if apprenticeship is on (hl-1316)

---

frontend/benefit/applicant/src/components/applications/forms/application/step5/useApplicationFormStep5.ts
frontend/benefit/applicant/src/components/applications/forms/application/step6/useApplicationFormStep6.ts
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryBenefitCalculatorView.tsx
frontend/benefit/handler/src/components/reviewSection/ReviewSection.tsx

Preserve training compensation data if apprenticeship is on applicant makes an update when status is "additional information needed". Remove training compensations on similar update if apprenticeship is off.
Additionally, fix some input labels and UI issues in handler calculation form by breaking different form groups into visible sections.

fix: retain or remove training compensation on applicant changes (hl-1184) 

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/conftest.py

The CorporateName in open case JSON was not truncated to 100 characters previously.

fix: truncate corporateName to 100 chars

---

frontend/benefit/applicant/src/components/header/useHeader.ts

Remove conditions so that applicant can create new messages in chat a little longer. 
Logic is as follows; chat is closed when application is:
1. Is decided in Ahjo
2. Decision made >= 14 days ago

fix: chat is open until it's archived for applicant (hl-1401)

---

backend/benefit/applications/api/v1/serializers/application.py
frontend/benefit/applicant/src/components/applications/pageContent/PageContent.tsx
frontend/benefit/shared/src/constants.ts
frontend/benefit/shared/src/types/application.d.ts

Do not show decisionSummary component for applicant if latest ahjo_status is not 'details_received', which confirms it has been decided and processed in Ahjo.
Remove calculated_benefit_amount from JSON if decision details for application have not been received yet.
Screenshot 2024-08-19 at 14.36.49

feat: hide decisionSummary if details unreceived from ahjo

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_ahjo_payload.py

[HL-1422](https://helsinkisolutionoffice.atlassian.net/browse/HL-1422)
Fix case where corporateName was incorrectly truncated to empty string, add more tests cases for the open case title and conditional string truncating.
[HL-1422]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: over eager corporate name truncate

---

backend/benefit/messages/serializers.py
backend/benefit/messages/tests/test_api.py

Frontend allowed new messages for `accepted` or `rejected` but backend did not. Remove archival and batch check for new message.

fix: loosen validation rules for new messages (hl-1424)

---

backend/benefit/applications/api/v1/serializers/application.py
frontend/benefit/applicant/src/hooks/useFormActions.tsx
frontend/benefit/handler/src/hooks/useFormActions.tsx

Calculator would get ghost rows, inputs and calculations without proper reset of values when apprenticeship was toggled off or pay subsidy got changed to `not_granted`

fix: reset values when apprenticeship or pay subsidy type is changed

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json

Added localization keys:
- changes.fields.batch.label
- changes.fields.handledByAhjoAutomation.label
that are used in changed logs
Changes key:
- applications.decision.description.additionalInformationNeeded
to:
- applications.decision.description.additional_information_needed
it was used in place in CamelCase format, changed that.

fix: added missing localization keys and fixed one (hl-1406)

---

backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/applications/tests/test_applications_api.py
backend/benefit/calculator/api/v1/serializers.py

DEV / TEST environment has begun to slow down in handler views where applications are listed in numbers. Currently, in TEST, requesting the API endpoint directly **to list only 26 applications takes around 2 - 3 seconds**. In frontend it takes even more time as there's multiple requests done simultaneously. Needless to say, this would also affect production at some point.
Here, a more simpler serializer is used. This is continued work and learnings from archive / search listings, where application count would've been a major bottle neck with the "include everything" `HandlerApplicationSerializer`. The results speak for themselves.
---
Listing 1700 applications in handler frontpage:
* Before: 40 - 60s
* After: 3 - 5s
---
A more "real world" case, listing 170 applications in handler …

chore(handler): use optimized serializer to list applications (hl-1432)

---

frontend/benefit/handler/src/components/applicationReview/ApplicationReview.sc.ts

Z-index issue with new message notice box and "locked to this handler" nag.

fix: locked user notice bar was on top of new messages list (hl-1456)

---

frontend/benefit/applicant/src/components/header/useHeader.ts
frontend/benefit/applicant/src/components/layout/Layout.sc.ts
frontend/benefit/applicant/src/components/layout/Layout.tsx
frontend/benefit/applicant/src/context/AppContext.tsx
frontend/benefit/applicant/src/context/AppContextProvider.tsx
frontend/benefit/handler/src/layout/Layout.sc.ts
frontend/benefit/handler/src/layout/Layout.tsx

Remember when handler sidebar was animated based on sidebar open/close state? Do the same thing for applicant.
* Copy + paste code from handler side so that sidebar now pushes main content to the left when drawer is opened. 
* This results to a better view when reviewing application. Content now remains readable and is not hidden by the sidebar.
* Rename StyledComponents prop in handler side

feat: offset application content when sidebar is open

---

frontend/benefit/applicant/src/components/header/useHeader.ts

Applicant's language change would be reset if navigational links were clicked. Fix this by including currently selected language prefix in links.

fix(applicant): header links did not include language uri (hl-1159)

---

frontend/benefit/handler/src/components/applicationList/HandlerIndex.tsx
frontend/benefit/handler/src/constants.ts

Tab clicks gets updated in browser path now like the old ui. This helps the handler when using browsers back button.

fix: add current tab number clicks to uri when each tab is clicked (hl-1458)

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/test_ahjo_payload.py

Fix issue with open case title, limit was earlier too short, 100 chars, when actually it should have been 150.

fix: open case title limit to 150 chars

---

backend/benefit/applications/api/v1/application_views.py

Alteration csv generation had quoting turned off, which caused the csv generation to crash if there was a line break submitted by the alteration form.
Handle an alteration and add some linebreaks or other special characters to the explanation text box and try to download the csv.

fix: whitespace crash in alteration csv

---

backend/benefit/applications/management/commands/send_ahjo_requests.py
backend/benefit/applications/models.py
backend/benefit/applications/services/ahjo_client.py
backend/benefit/applications/services/ahjo_integration.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_ahjo_integration.py

[HL-1460](https://helsinkisolutionoffice.atlassian.net/browse/HL-1460?atlOrigin=eyJpIjoiN2JhOGIzNGI3NjBhNGRkZmJkNzk3NGFiNGY4NDZkYmYiLCJwIjoiaiJ9)
Add ahjo_status after records are added to a case after the case is opened.
Also allow filtering with multiple ahjo_statuses, in case status can be one of several.
[HL-1460]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: HL 1460

---

backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/test_ahjo_payload.py

If a record is added after open case, it's title should begin with "Hakemus, täydennys" etc.

fix: record title for add records request

---

backend/benefit/applications/api/v1/search_views.py
backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/applications/tests/test_application_search.py
backend/benefit/applications/tests/test_command_import_archival_applications.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationReview/employeeView/EmployeeView.tsx
frontend/benefit/handler/src/components/applicationsArchive/ApplicationsArchive.tsx
frontend/benefit/handler/src/components/applicationsArchive/useApplicationsArchive.ts
frontend/benefit/handler/src/hooks/useSearchApplicationQuery.ts

Handler can now efficiently find employee's previous benefits. 
* Modify search code to use an existing application as base to find related other applications
* List any `Application` objects with matching SSN (note that first_name and last_name can change)
* List any `ArchivalApplication` objects by matching with best guess keys: `first_name`, `last_name` and `year_of_birth` (parsed from SSN)
* Implement button to click in application view, seek for Employee section
* Refactor and implement search view
---
---

feat: find related applications for a single employee (hl-1354)

---

frontend/benefit/applicant/src/components/header/Header.tsx
frontend/benefit/applicant/src/components/header/useHeader.ts
frontend/shared/src/components/header/Header.tsx

This was me opening a can of worms. 
Previously, applicant's `/sv`, `/en` header links were fixed. This however, broke the default language Finnish links without  having the explicit `/fi` URI prefix. This is now fixed here.
Also, it turned out that in `shared/Header` component, setting active link highlight, was not considering URI locale prefixes at all. So I implemented a custom function that can optionally be passed to set active navigation item the way we want it in helsinki-benefit.

feat: fix routing; active tab function was off if locale was used

---

backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/services/clone_application.py
frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/step5/ApplicationFormStep5.tsx
frontend/benefit/applicant/src/components/header/Header.tsx
frontend/benefit/applicant/src/components/mainIngress/frontPage/FrontPageMainIngress.sc.ts
frontend/benefit/applicant/src/components/mainIngress/frontPage/FrontPageMainIngress.tsx
frontend/benefit/applicant/src/hooks/useCloneApplicationMutation.ts
frontend/benefit/shared/src/backend-api/backend-api.ts
frontend/benefit/shared/src/utils/dates.ts

Add feature to clone any application on applicant's side. Only step 1 information is cloned. There are some switches that can be used to clone work conditions, pay subsidy and employee information, but they are yet to be unused. They will be useful on later ticket when handler side cloning is added.
* Clone the latest submitted application (front page)
* Clone any application (application review page)
* Fix language prefix dropping off when clicking Helsinki logo in Header
* Fix some type issue

feat: clone application on applicant side (hl-1447)

---

backend/benefit/applications/api/v1/ahjo_integration_views.py
backend/benefit/applications/management/commands/send_ahjo_requests.py
backend/benefit/applications/tests/test_ahjo_integration.py
backend/benefit/applications/tests/test_application_tasks.py

[HL-1461](https://helsinkisolutionoffice.atlassian.net/browse/HL-1461)
AhjoRequestId was stored as application.ahjo guid, now store it at the application.ahjo_status as where it should be stored.
[HL 1466](https://helsinkisolutionoffice.atlassian.net/browse/HL-1466)
Fix an error where the decision detail callback would find multiple applications with the same ahjo_case_id, as in production there are application with handled_by_ahjo_automation=False that have share the same case_id.
[HL-1461]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HL 1461 + HL 1466 fixes

---

backend/benefit/applications/api/v1/serializers/application.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationList/ApplicationList.sc.ts
frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/components/applicationList/useApplicationListData.ts
frontend/benefit/handler/src/types/applicationList.d.ts
frontend/benefit/shared/src/types/application.d.ts

Add Ahjo error statuses to handler application listing. Clicking it opens a tooltip which gives the error message.

feat: add ahjo errors to handler's application lists (hl-1421)

---

backend/benefit/applications/api/v1/power_bi_integration_views.py
backend/benefit/applications/tests/test_power_bi_integration.py

Add missing SBOM character to the beginning of the CSV, so that the letters are not mangled.

fix: add SBOM to powerBI csv

---

backend/benefit/applications/api/v1/serializers/application.py

[HL-1477](https://helsinkisolutionoffice.atlassian.net/browse/HL-1477?atlOrigin=eyJpIjoiYTQwNWU3NzgwNjJkNDQwM2JhZDgyMDIyYTUxZTRlZjUiLCJwIjoiaiJ9)
An existing pdf_summary attachment was being deleted whenever an application was updated.
This PR excludes the attachment of type pdf_summary from the serializer code, that purges non-valid attachments.
[HL-1477]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: pdf_summary delete on application update

---

backend/benefit/applications/services/ahjo_decision_service.py
backend/benefit/applications/services/ahjo_xml_builder.py
backend/benefit/applications/tests/test_ahjo_xml_builder.py

Adding a linebreak in django admin to the decision text caused the XML generation to fail.
This PR removes common invisible characters (resulting from example copy/pasting from Word etc.) before the XML is generated.

fix: HL-1478 xml error

---

backend/benefit/applications/services/ahjo_client.py
backend/benefit/applications/services/ahjo_integration.py

Move the logic of saving the new ahjo_status into the ahjoClient class to ensure that the each of the following statuses,
```
request_to_open_case_sent,
decision_proposal_sent,
update_request_sent,
delete_request_sent,
new_record_request_sent
```
is created even if the request does not succeed so that the error_from_ahjo is stored in to the correct status.

feat: ensure ahjo_status is saved during  request

---

backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/applications/tests/test_applications_api.py

[HL-1488](https://helsinkisolutionoffice.atlassian.net/browse/HL-1488?atlOrigin=eyJpIjoiZTczNDY5M2I4Y2VkNDcwNGE0NmYzNjExNjdlZDA3ODkiLCJwIjoiaiJ9)
Resolves an issue where if handler unlocks and locks an application and it's status is updated to handling, the associated batch is removed from applications that are handled via ahjo automation.
[HL-1488]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: do not remove batch if ahjo automation

---

frontend/benefit/applicant/browser-tests/page-model/step2.ts
frontend/benefit/applicant/src/components/applications/forms/application/step2/ApplicationFormStep2.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step2/useApplicationFormStep2.ts
frontend/benefit/applicant/src/components/applications/forms/application/step2/utils/validation.ts

Applicants would just leave end date to default because of the auto-fill done after start date selection. Remove auto-fill so that applicants must explicitly specify the end date. Removal of auto-fill also fixes the free keyboard typing to the end date field.
* Remove useEffect and it's dependencies for setting endDate based on startDate input
* Rewrite validation for endDate -- it must be 30 days from start date
* Refactor test so that it fills startDate and endDate in tab order

fix: remove end date autofill and fix validation

---

frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json

New versions (fi/en/sv) of employee personal data processing pdf has been loaded to the web pages.
Links updated.

fix: links updated to new version of employee data processing pdf (hl-1474)

---

backend/benefit/applications/api/v1/serializers/ahjo_status.py
backend/benefit/applications/api/v1/serializers/application.py

When fetching ahjo status errors invoked by GUI, see if there's a validation error from ahjo. Copy that information to errorFromAhjo object if it is not existing and voilà.

feat: add ahjo validation error message (hl-1482)

---

frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/HandlingApplicationActionsAhjo.tsx

No need to check for batch existed on cancellation.

fix: do not require a batch when cancelling an application (hl-1470)

---

backend/benefit/applications/services/change_history.py
frontend/benefit/handler/src/components/sidebar/ChangeSet.tsx

Expose change history sets with zero differences but mere comment to the API response. This is used as a tool for the handler when commenting on attachment changes (or anything else, really).
As a bonus, rename some confusing variables.

fix: application history did not include change reasons with 0 diffs (hl-1484)

---

frontend/benefit/handler/src/components/applicationForm/useApplicationForm.ts
frontend/benefit/handler/src/components/applicationForm/utils/applicationForm.ts
frontend/benefit/handler/src/components/applicationForm/utils/validation.ts

If application is of applicant origin, do not write paperApplicationDate when saving application during handling edit.

fix: prevent submit of paperApplicationDate to application of applicant origin

---

frontend/benefit/applicant/src/components/applications/pageContent/PageContent.tsx
frontend/benefit/handler/src/components/applicationReview/handlingView/HandlingStep1.tsx

Accessor was accessing the wrong field. This would sometimes result to 0,00 € in benefit amount on DecisionSummary box.

fix: benefit calculation amount in decision summary was 0,00 €

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationReview/notificationView/NotificationView.tsx

Just add application number and link back to application after Ahjo submission is done.

feat: add application number to 'Ahjo submission complete' splash screen

---

frontend/benefit/handler/browser-tests/pages/7-handle-alteration.testcafe.ts
frontend/benefit/handler/src/components/alterationHandling/AlterationCsvButton.tsx
frontend/benefit/handler/src/components/alterationHandling/AlterationHandlingForm.tsx

Cont. from #3406. Do not allow handle before CSV has been downloaded.

feat: disable handle button until CSV has been downloaded (hl-1433)

---

frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/useSalaryBenefitCalculatorData.ts

Fill in calculator initial values for start date and end date. Applicant's entry is used as default.

feat: use applicant's startDate as initial value for calculation (hl-1471)

---

backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/calculator/api/v1/serializers.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/components/applicationList/HandlerIndex.tsx
frontend/benefit/handler/src/components/applicationList/useApplicationListData.ts
frontend/benefit/handler/src/types/applicationList.d.ts
frontend/benefit/shared/src/types/application.d.ts

Add two new columns to application list for applications which are "in payment". That means decision making has progressed to accepted state. application status is `accepted`, batch status is `accepted` and batch has a decision date.
1. Get applications to "in payment" state, see up for details.
2. Set application's talpa status to any of `not_sent_to_talpa` `rejected_by_talpa` `successfully_sent_to_talpa`
3. Go to [https://localhost:3100/?tab=5](https://localhost:3100/?tab=5)

feat: add talpa status and decision date to apps which are "in payment" state (hl-1307)

---

backend/benefit/applications/api/v1/serializers/application.py
frontend/benefit/applicant/src/components/applications/pageContent/PageContent.tsx

There never was a calculation object to access in applicant side. Add more logic to handle non-ahjo-automated cases for the calculated_benefit_amount field.

fix: resolve issues in alteration sum for the applicant (hl-1504 cont.)

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/services/pdf_templates/benefit_template.html
backend/benefit/applications/tests/test_ahjo_payload.py

[HL-1524](https://helsinkisolutionoffice.atlassian.net/browse/HL-1524)
Use application.company.name instead of application.company_name as the latter is not always present.
[HL-1524]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: use company.name instead of app.company_name

---

frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/alterationHandling/AlterationHandling.tsx
frontend/benefit/handler/src/components/alterationHandling/AlterationHandlingForm.tsx
frontend/benefit/handler/src/components/applicationForm/ApplicationForm.tsx
frontend/benefit/handler/src/components/applicationHeader/ApplicationHeader.tsx
frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/HandlingApplicationActions.tsx
frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/HandlingApplicationActionsAhjo.tsx
frontend/benefit/handler/src/components/applicationReview/actions/receivedApplicationActions/ReceivedApplicationActions.tsx
frontend/benefit/handler/src/components/statusLabel/StatusLabel.tsx
frontend/benefit/handler/src/hooks/applicationHandling/useRouterNavigation.ts
frontend/benefit/handler/src/hooks/useFormActions.tsx
frontend/benefit/handler/src/hooks/useHandlerReviewActions.ts
frontend/benefit/handler/src/pages/_app.tsx
frontend/shared/src/utils/localstorage.utils.ts

Handler side changes. Back buttons each had custom function calls to next router. Use centralized hook to perform these actions with different logic and use cases.
* Use one function to invoke when Back buttons are pressed
* Usually, go back from application to corresponding tab with matching status
* Go to archive if the application is archived
* One special case where similar applications were searched for with `?appNo=123456` param
* Go to alterations if it was previously visited
* If no other means is provided, route back to root of the app
* Browsing is now recorded to window.sessionStorage to allow for history tracking and usage where needed
* Fix one `key` prop issue

feat: perform "back" actions througout the app using centralized hook (hl-1276)

---

backend/benefit/applications/tests/test_applications_api.py
backend/benefit/locale/en/LC_MESSAGES/django.po
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/sv/LC_MESSAGES/django.po
backend/benefit/messages/automatic_messages.py
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json

Better text for applicant when application opend for editing. Reminder that a resend is needed.
Added some missing localizations for handler change log.
Added localization for received application status.
However this status is not used in Applicant app, Mistake to add it there (and only in fi-file) corrected.
Text in test updated
HL-1425, HL-1486

fix: text improvements & added localizations (Hl-1425 & HL-1486)

---

backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/applications/services/clone_application.py
backend/benefit/applications/tests/test_applications_api.py

App would return 404 for cloned application's attachment because the file was written to docker container and Azure blob storage is unaware of the addition. Use a more Django-native way to handle created file as an upload with `InMemoryUploadedFile`.
In addition, fix another issue (BAD_REQUEST 400) when transitioning an application from `received` to `handling` if pay subsidy was `not_granted`.

fix: clone application fixes for attachments and status change (hl-1511)

---

backend/benefit/applications/api/v1/power_bi_integration_views.py
backend/benefit/common/authentications.py

[HL-1529](https://helsinkisolutionoffice.atlassian.net/browse/HL-1529?atlOrigin=eyJpIjoiYmJjNGZhMWIxZDRmNDcxOGE3MGUzNjZhNzE3Yjc0N2MiLCJwIjoiaiJ9)
PowerBI was using the same authentication class as Talpa Robot, so the credentials were the same, this adds a separate authentication class for PowerBI api.
[HL-1529]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: separate credentials for PowerBI

---

backend/benefit/applications/tests/test_application_batch_api.py
frontend/benefit/handler/src/components/applicationReview/CalculationReview.tsx
frontend/benefit/handler/src/components/applicationReview/calculationTable/useCalculationTable.ts
frontend/benefit/handler/src/components/applicationReview/handlingView/HandlingStep2.tsx

* return null on component mount if decision draft is still being generated
* return benefit duration zero if there is no calculation
* add loading spinner for when fetching template sections

fix: repair some app crashing bugs when drafting the decision proposal (hl-1522)

---

backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/services/applications_csv_report.py
backend/benefit/applications/services/applications_power_bi_csv_report.py
backend/benefit/applications/tests/test_ahjo_payload.py
backend/benefit/applications/tests/test_applications_report.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationReports/ApplicationReports.tsx
frontend/benefit/handler/src/components/applicationReports/ReportsSection.tsx
frontend/benefit/handler/src/components/applicationReports/useApplicationReports.ts

[HL-1475](https://helsinkisolutionoffice.atlassian.net/browse/HL-1475?atlOrigin=eyJpIjoiZGI3ZDkxNzRhZmU4NDc2NGE1OGM4ZjUyODc1ODY4OTYiLCJwIjoiaiJ9)
Use the submitted_at custom Application model attribute in the Ahjo payload and report csv:s,and  created_at if it's not present.
[HL-1362](https://helsinkisolutionoffice.atlassian.net/browse/HL-1362)
Add an alternate, more compact csv, similar to the powerbi report, to the handler's report screen for downloading.
[HL-1483](https://helsinkisolutionoffice.atlassian.net/browse/HL-1483)
Show the alteration.recovery_amount correctly in the csv report.
[HL-1475]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HL-1362]: …

Hl 1475 submitted at

---

backend/benefit/applications/services/ahjo_client.py
backend/benefit/applications/services/ahjo_error_writer.py
backend/benefit/applications/services/ahjo_integration.py
backend/benefit/applications/services/ahjo_xml_builder.py

[HL-1503](url)
1. Do not block subsequent decision requests if the XML is malformed
2. Add any xml errors to ahjo_status
3. Log the application number with XML error
[HL-1503]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: don't block ahjo requests if xml build fails

---

frontend/benefit/applicant/browser-tests/page-model/WizardStep.ts
frontend/benefit/applicant/public/locales/en/common.json
frontend/benefit/applicant/public/locales/fi/common.json
frontend/benefit/applicant/public/locales/sv/common.json
frontend/benefit/applicant/src/components/applications/forms/application/step1/ApplicationFormStep1.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step2/ApplicationFormStep2.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step3/ApplicationFormStep3.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step4/ApplicationFormStep4.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step5/ApplicationFormStep5.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step6/ApplicationFormStep6.tsx
frontend/benefit/applicant/src/components/applications/forms/application/stepperActions/StepperActions.tsx

Just changes applicant GUI's cancellation button and modal texts to "cancel" rather than "delete" if application has already been sent.

chore: wording 'delete' to 'cancel' if app is not a draft (hl-1469)

---

frontend/benefit/handler/src/components/applicationList/HandlerIndex.tsx

Add another batch status so that talpa-rejected applications are visible in the "in payment" listing.

fix: allow for talpa-rejected batches to be seen (hl-1527)

---

backend/benefit/applications/api/v1/serializers/application.py
backend/benefit/calculator/api/v1/serializers.py
backend/benefit/calculator/api/v1/views.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/components/applicationList/ApplicationListForInstalments.tsx
frontend/benefit/handler/src/components/applicationReview/handlingView/DecisionCalculationAccordion.sc.ts
frontend/benefit/handler/src/components/applicationReview/handlingView/DecisionCalculationAccordion.tsx
frontend/benefit/shared/src/types/application.d.ts

Continued from #3498. 
* Implement "Instalments" accordion into decision box
* Lists both instalments: the default one and the second too.
* Add `status` validation to `InstalmentSerializer`
* Make instalment patch endpoint change application to `archived` if second instalment is cancelled
* Cancelling 2nd instalment from `ApplicationListForInstalments` now uses popup
* Other minor details changed for `ApplicationListForInstalments`

feat: add accordion to decision box to list instalments (hl-1497)

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/test_ahjo_payload.py

[HL-1546](https://helsinkisolutionoffice.atlassian.net/browse/HL-1546)
If a new record is sent to ahjo, or the pdf summary is updated, use the created_at of the attachment, not the application, in the title.
[HL-1546]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: attachment date in add records & update reqs

---

backend/benefit/applications/api/v1/application_batch_views.py
backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/api/v1/talpa_integration_views.py
backend/benefit/applications/models.py
backend/benefit/applications/services/ahjo_integration.py
backend/benefit/applications/services/applications_csv_report.py
backend/benefit/applications/services/talpa_csv_service.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_application_batch_api.py
backend/benefit/applications/tests/test_talpa_integration.py

[HL-1495](https://helsinkisolutionoffice.atlassian.net/browse/HL-1495)
- Refactor Talpa CSV generator in it's own class for better maintainability.
- Add a custom query to Application.objects for querying applications that have due instalments.
- Show the currently due instalment amount as the payable amount in the Talpa CSV.
- Remove the unreliable logic that updated batches and applications after the robot had done a GET request, now that the callback is fully functional and operational.
- Rework the Talpa callback to update the batches like previously, if `settings.PAYMENT_INSTALMENTS_ENABLED == False`, if True, the callback updates the instalments of the successful applications and the application itself, IF the instalment is the only one or the final one (2/2). 
[HL-1495]: …

Hl 1495 talpa instalment

---

backend/benefit/applications/services/ahjo_client.py
backend/benefit/applications/services/ahjo_error_writer.py
backend/benefit/applications/tests/test_ahjo_requests.py

[HL-1514](https://helsinkisolutionoffice.atlassian.net/browse/HL-1514)
Do not create a new ahjoStatus every time a request to ahjo is attempted, but update the last one.
[HL-1515](https://helsinkisolutionoffice.atlassian.net/browse/HL-1515?atlOrigin=eyJpIjoiZmYzYWRiY2ExYTVmNGRkYTlhMmQxNWQwNGFlOTQzZWEiLCJwIjoiaiJ9)
Write possible network errors to the ahjoStatus.
[HL-1514]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HL-1515]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: don't create new status on retry, save error

---

backend/benefit/applications/api/v1/application_views.py
frontend/benefit/handler/src/components/applicationReview/actions/editAction/EditAction.tsx
frontend/benefit/handler/src/hooks/useRequireAdditionalInformation.ts
frontend/benefit/shared/src/backend-api/backend-api.ts

Fix a issue that could lead to big trouble. Changing the application status would always send the whole application as POST which could lead to data loss if there were changes done in between application load.
Instead of POSTing everything to the update endpoint, make a new endpoint that will only change the status as appropriate.

feat: use own endpoint for requesting more information

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_ahjo_payload.py

[HL-1546](https://helsinkisolutionoffice.atlassian.net/browse/HL-1546)
Remove comma after the word "täydennys".
[HL-1533](https://helsinkisolutionoffice.atlassian.net/browse/HL-1533)
Public title in the  Ahjo open case request can be 512 characters long.
[HL-1546]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HL-1533]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Hl 1533 ahjo title

---

frontend/benefit/applicant/browser-tests/utils/fieldMaps.ts
frontend/benefit/applicant/src/components/applications/alteration/AlterationAccordionItem.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step5/companyInfoView/CompanyInfoView.tsx
frontend/benefit/applicant/src/components/applications/forms/application/step5/employeeView/EmployeeView.tsx
frontend/benefit/applicant/src/components/applications/pageContent/PageContent.tsx
frontend/benefit/handler/browser-tests/pages/7-handle-alteration.testcafe.ts
frontend/benefit/handler/src/components/alterationHandling/AlterationHandlingConfirmationModal.tsx
frontend/benefit/handler/src/components/applicationForm/review/companySection/CompanySection.tsx
frontend/benefit/handler/src/components/applicationForm/review/employmentSection/EmploymentSection.tsx
frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/components/applicationList/ApplicationListForInstalments.tsx
frontend/benefit/handler/src/components/applicationReview/CalculationReview.tsx
frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/DoneModalContent/DoneModalContent.tsx
frontend/benefit/handler/src/components/applicationReview/applicationProcessingView/ApplicationProcessingView.tsx
frontend/benefit/handler/src/components/applicationReview/calculationTable/useCalculationTable.ts
frontend/benefit/handler/src/components/applicationReview/deminimisView/DeminimisView.tsx
frontend/benefit/handler/src/components/applicationReview/employmentView/EmpoymentView.tsx
frontend/benefit/handler/src/components/applicationReview/handledView/HandledView.tsx
frontend/benefit/handler/src/components/applicationReview/handlingView/AlterationAccordionItem.tsx
frontend/benefit/handler/src/components/applicationReview/handlingView/DecisionCalculationAccordion.tsx
frontend/benefit/handler/src/components/applicationReview/handlingView/HandlingStep1.tsx
frontend/benefit/handler/src/components/applicationReview/handlingView/InstalmentAccordionSections.tsx
frontend/benefit/handler/src/components/applicationReview/handlingView/useInstalmentAccordionSections.ts
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryCalculatorResults/SalaryCalculatorHighlight.tsx
frontend/benefit/handler/src/components/applicationReview/salaryBenefitCalculatorView/SalaryCalculatorResults/SalaryCalculatorResults.tsx
frontend/benefit/handler/src/components/batchProcessing/BatchApplicationList.tsx
frontend/shared/src/utils/string.utils.ts

Use new function wrapper to cover most currency conversions in display. No cents are really necessary to display even though they might be paid in some very specific cases.

refactor: harmonise float to currency conversions (hl-1506)

---

frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/handler/src/components/applicationList/ApplicationListForInstalments.tsx
frontend/benefit/handler/src/components/applicationReview/handlingView/InstalmentAccordionSections.tsx
frontend/benefit/handler/src/components/applicationReview/handlingView/useInstalmentAccordionSections.ts
frontend/benefit/handler/src/types/applicationList.d.ts
frontend/benefit/handler/src/utils/applications.ts
frontend/benefit/shared/src/types/application.d.ts

* implement tag wrapper for talpa status for 1st instalments that have gone through ahjo process
* fix issue where 1st instalment was zero or negative
* ahjo process incomplete
* above and with two instalments
* make JSX logic easier to read

fix: instalment issues (hl-1496 cont.)

---

backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/services/clone_application.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationReview/actions/handlingApplicationActions/HandlingApplicationActionsAhjo.tsx

* in frontend, change translation for clone button and hide them in decision proposal steps
* add missing ahjo status "submitted_but_not_sent_to_ahjo"
* ensure duplicated application is of type "applicant" if applicant is creating the clone
* clone only specific attachments
* copy some test values on handler clone if address information is missing

fix: various cloning issues (hl-1539)

---

backend/benefit/locale/en/LC_MESSAGES/django.po
backend/benefit/locale/fi/LC_MESSAGES/django.po
backend/benefit/locale/sv/LC_MESSAGES/django.po
backend/benefit/messages/tests/test_api.py
backend/benefit/messages/views.py
backend/benefit/users/api/v1/views.py
frontend/benefit/handler/src/components/header/useHeader.tsx

Override default `GET / list()` endpoint and add rejected application comment and calculation comment as notes.
* Include manual calculation comment into notes (`calculation.override_manual_benefit_amount_comment`)
* Include accepted/rejected comment into notes (`log_entry` with transition to `rejected` or `accepted`)
* Send handler language preference to backend so that correct django translations are loaded
* force Finnish for now

feat: add two calculation and application fields as notes (hl-1550)

---

backend/benefit/applications/api/v1/ahjo_integration_views.py
backend/benefit/applications/api/v1/serializers/ahjo_callback.py
backend/benefit/applications/management/commands/send_ahjo_requests.py
backend/benefit/applications/models.py
backend/benefit/applications/services/ahjo/exceptions.py
backend/benefit/applications/services/ahjo_authentication.py
backend/benefit/applications/services/ahjo_client.py
backend/benefit/applications/services/ahjo_decision_service.py
backend/benefit/applications/services/ahjo_error_writer.py
backend/benefit/applications/services/ahjo_integration.py
backend/benefit/applications/tests/test_ahjo_requests.py
backend/benefit/applications/tests/test_application_tasks.py
backend/benefit/applications/tests/test_talpa_integration.py

[HL-1564](https://helsinkisolutionoffice.atlassian.net/browse/HL-1564)
Talpa CSV query did not check application status correctly, when querying is based on instalments, added a check for application.status == 'accepted'.
[HL 1558](https://helsinkisolutionoffice.atlassian.net/browse/HL-1558) and [HL-1549](https://helsinkisolutionoffice.atlassian.net/browse/HL-1549)
Fix for a situation where a successful add_records ahjo request caused an already successful send_decision_proposal request to be sent again. Move some of the exceptions in a separate file and improve the error formatting for XML errors show that they are shown in the handler UI.
[chore: refactor ahjo exceptions into one place](https://github.com/City-of-Helsinki/yjdh/pull/3565/commits/3d2eb397c6d1a4fc37688f01b4fdc4b1ad6243ca) …

fix: HL 1558 ahjo fixes

---

backend/benefit/applications/api/v1/application_batch_views.py

[HL-1565](https://helsinkisolutionoffice.atlassian.net/browse/HL-1565)
[Sentry issue](https://sentry.hel.fi/organizations/city-of-helsinki/issues/38195/?query=is%3Aunresolved&referrer=issue-stream)
The talpa csv was a unquoted csv string without an escape character, which causes the csv generation to fail when there are semicolons in the data. Add quoting so any special chars are escaped automatically.
[HL-1565]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: quotes crashing talpa csv

---

backend/benefit/applications/services/ahjo_authentication.py

[HL-1563](https://helsinkisolutionoffice.atlassian.net/browse/HL-1563?atlOrigin=eyJpIjoiODljOTRiNjRiOGQzNGU2OThhYzE1N2Y0ZjNmNDA2ZWEiLCJwIjoiaiJ9)
Use the longer expiry date of the refresh token to check if token is expired.
[HL-1563]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: token expiry based on refresh token expiry

---

compose.employer.yml
compose.handler.yml
frontend/Dockerfile-localdevelopment

- added `WATCHPACK_POLLING=true` by default so hot reload should work
for most platforms out of the box now (e.g. on Windows 11 + Docker
Desktop + WSL2 with the files volume mapped from the host filesystem
to the docker container hot reload now works)
- made sure `frontend/Dockerfile-localdevelopment` sets up the
project's `.next` directory so that the express server can access its
files
refs YJDH-718 (making kesaseteli frontend docker development usable)
[YJDH-718](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-718)
Permission problems using `docker compose -f compose.handler.yml up --build` before/during this PR development, but not after this PR:
```
triggerUncaughtException(err, true /* fromPromise */);
^
[Error: EACCES: permission denied, open …
```

YJDH-718 | Fix Kesäseteli's frontend docker developing, hot reload & permissions

---

backend/benefit/applications/services/ahjo_payload.py
backend/benefit/applications/services/ahjo_xml_builder.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_ahjo_xml_builder.py

[HL-1549](https://helsinkisolutionoffice.atlassian.net/browse/HL-1549)
Exception was not raised after xml validation error so an invalid xml could be sent to Ahjo.
[HL-1568](https://helsinkisolutionoffice.atlassian.net/browse/HL-1568)
Fix ampersand issue in Ahjo decision XML.
[HL-1549]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HL-1568]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Hl 1549 xml exception

---

backend/benefit/applications/enums.py
backend/benefit/applications/jobs/daily/daily_application_jobs.py
backend/benefit/applications/management/commands/ahjo_base_command.py
backend/benefit/applications/management/commands/get_signer.py
backend/benefit/applications/management/commands/seed.py
backend/benefit/applications/services/ahjo/enums.py
backend/benefit/applications/services/ahjo/request_handler.py
backend/benefit/applications/services/ahjo/setting_response_handler.py
backend/benefit/applications/services/ahjo_client.py
backend/benefit/applications/services/ahjo_integration.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_ahjo_request_handler.py
backend/benefit/applications/tests/test_ahjo_requests.py
backend/benefit/applications/tests/test_ahjo_response_handler.py

[HL-1559](https://helsinkisolutionoffice.atlassian.net/browse/HL-1559)
Get signers name and AD id from ahjo rest api via daily cron and store it into ahjo settings.
[HL1534](https://helsinkisolutionoffice.atlassian.net/browse/HL-1534)
Better error handling if decisionmaker (and now signer) request fails.
[HL-1559]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: HL 1559 signer api

---

backend/benefit/applications/enums.py
backend/benefit/applications/management/commands/send_ahjo_requests.py
backend/benefit/applications/models.py
backend/benefit/applications/services/ahjo/request_handler.py
backend/benefit/applications/services/ahjo/response_handler.py
backend/benefit/applications/services/ahjo_decision_service.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_ahjo_decisions.py
backend/benefit/applications/tests/test_ahjo_response_handler.py
backend/benefit/applications/tests/test_models.py
backend/benefit/calculator/rules.py
backend/benefit/calculator/tests/test_calculator_api.py

Actually  fix for HL-1564(https://helsinkisolutionoffice.atlassian.net/browse/HL-1564?atlOrigin=eyJpIjoiNTViYjY0YTcyYmFiNGYzMzhlOTMzOTNmYzNjYTEzYjYiLCJwIjoiaiJ9)
- Instalments are now updated as accepted only after decision details are received from Ahjo REST api
- Initial instalment status is now WAITING
- move decision details response handling away from the cli command and into its own handler, for more testable code, also write test for the handling of the decision detail response and improve error handling

feat: Hl 1498 talpa errors

---

backend/benefit/applications/services/applications_csv_report.py
backend/benefit/applications/services/applications_power_bi_csv_report.py
backend/benefit/applications/services/talpa_csv_service.py
backend/benefit/applications/tests/conftest.py
backend/benefit/applications/tests/test_applications_report.py
backend/benefit/applications/tests/test_talpa_integration.py

[HL-1576](https://helsinkisolutionoffice.atlassian.net/browse/HL-1576)
Add new columns to handler csv reports and PowerBI report:
- the decided amount for instalment 1 and 2
- the actual payable amount for instalment 2
- the due date of instalment 2
Should fix [HL-1571](https://helsinkisolutionoffice.atlassian.net/browse/HL-1571?atlOrigin=eyJpIjoiNmJiMmU4MDUwNzJiNDU5NWIyNTZhN2U5NTNhYjEwMGMiLCJwIjoiaiJ9) also.
Change pruned_applications_csv_service to talpa_applications_csv in tests, because the name was confusing.
Use the recovered_amount property of instalment in talpa CSV export  and the other csv reports.
[HL-1576]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HL-1571]: …

feat: 2nd instalment due date into csv

---

backend/benefit/applications/services/ahjo/response_handler.py
backend/benefit/applications/tests/test_ahjo_response_handler.py

[HL-1577](https://helsinkisolutionoffice.atlassian.net/browse/HL-1577)
Update only the first instalment as accepted after decision details are received from Ahjo.
[HL-1577]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update only 1st instalment after decision cb

---

frontend/benefit/handler/src/components/applicationList/ApplicationList.tsx
frontend/benefit/shared/src/types/application.d.ts

Ahjo error, depending on the case, might be inside an array, object, or string. 
Try mapping as array first:`[{"id": 1234, "message":"Hello ErrorArray}]`
Next, try as object: `{"id": 1234, "message": "Hello ErrorObject"}`
Finally, fallback to string: `"Hello ErrorString"`
All of these 3 cases are possible to store into backend database.

fix: try to parse all kinds of ahjo errors

---

backend/benefit/applications/api/v1/search_views.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationsArchive/ApplicationsArchive.tsx
frontend/benefit/handler/src/components/applicationsArchive/useApplicationsArchive.ts
frontend/benefit/handler/src/hooks/useSearchApplicationQuery.ts

Production is a bit slow in the archive page. No need to display every item that exists; usually there's no point in that. Limit initial query to some 30 items only. User can then click "Load more" button to retrieve all items.

fix: limit search list items to 30 without user action

---

backend/benefit/applications/management/commands/send_ahjo_requests.py

[HL-1518](https://helsinkisolutionoffice.atlassian.net/browse/HL-1518)
If version_series_id is missing for some reason, store the error into ahjoStatus.
[HL-1518]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: save missing version_series_id error

---

backend/benefit/calculator/api/v1/validators.py
frontend/benefit/handler/public/locales/en/common.json
frontend/benefit/handler/public/locales/fi/common.json
frontend/benefit/handler/public/locales/sv/common.json
frontend/benefit/handler/src/components/applicationList/ApplicationListForInstalments.tsx
frontend/benefit/handler/src/components/applicationList/ApplicationTableFooter.tsx
frontend/benefit/handler/src/components/applicationList/InstalmentButton.tsx

[HL-1575](https://helsinkisolutionoffice.atlassian.net/browse/HL-1575)
Enable the returning of an instalment from error_in_talpa status to accepted or paid status via  handlerUI.
[HL-1575]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Hl 1575 instalment to accepted

---

backend/benefit/applications/api/v1/application_views.py
backend/benefit/applications/api/v1/serializers/application_alteration.py
backend/benefit/applications/services/applications_csv_report.py
backend/benefit/applications/services/applications_power_bi_csv_report.py
backend/benefit/applications/tests/test_alteration_api.py

[HL-1490](https://helsinkisolutionoffice.atlassian.net/browse/HL-1490?atlOrigin=eyJpIjoiYmMxNzY5OWU0ZGEyNGJkMGEyMTJhZGE2OWQwZmJkZDEiLCJwIjoiaiJ9)
Round alteration.recovery_amount down when it is saved or updated.
[HL-1502](https://helsinkisolutionoffice.atlassian.net/browse/HL-1502)
Show both instalments in the csv reports, even if they are not due yet.
[HL-1490]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HL-1502]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: round alteration recovery amount down

---

backend/benefit/applications/services/clone_application.py
backend/benefit/applications/tests/test_application_clone.py

Force application origin to be applicant
[hl-1547](https://helsinkisolutionoffice.atlassian.net/browse/HL-1547)
In application cloning it was possible to clone paper application and have new paper application that had problem with full application attachment

fix: In application cloning force origin to be applicant

---

backend/tet/tet/views.py

Currently CSRF token is provided only once during the end of authentication. If the user loses the CSRF token, there is no way to retrieve it without logging out and logging back in.
- APIView does not set CSRF token because it defaults to csrf_exempt
- CsrfViewMiddleware does not set a new token if cookie is missing
CSRF token can be forced into the response by calling get_token, so it is added to the userinfo endpoint to improve the chances of it being delivered to the browser.
Refs: TETP-306
https://helsinkisolutionoffice.atlassian.net/browse/TETP-306

fix: include CSRF token in tet userinfo endpoint response

---

backend/tet/tet/settings.py

HELSINKI_PROFILE_SCOPE must be set to access_token in tunnistus
OIDC_RP_SCOPES must not include the profile scope in tunnistus
OIDC_RP_SCOPES should include email in tunnistus so that the token has email information for django-helusers.
refs: TETP-310, TETP-314

fix: tunnistus related settings

---

backend/tet/tet/settings.py

hp_client requires that the setting exists even if it is not going to be used.
refs: TETP-310, TETP-314

fix: restore required setting TUNNISTAMO_API_TOKENS_ENDPOINT

---

frontend/kesaseteli/employer/public/locales/en/common.json
frontend/kesaseteli/employer/public/locales/fi/common.json
frontend/kesaseteli/employer/public/locales/sv/common.json
frontend/kesaseteli/youth/public/locales/en/common.json
frontend/kesaseteli/youth/public/locales/fi/common.json
frontend/kesaseteli/youth/public/locales/sv/common.json

YJDH-724.
The term for "terms of service" and the target of the link changed after new refinement and specification https://helsinkisolutionoffice.atlassian.net/browse/YJDH-724?focusedCommentId=141405.
The term for "rekisteriseloste" changed to "tietosuojaseloste". Also renamed the links in other languages to
match the title of the related document.
Changed to a new language specific accessibility statement link.

Fix Kesäseteli's terms and links related to TOS and a11y statement to match new spec
